<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['validation_error'] = 'Revise los datos introducidos.';
$messages['definition_not_found'] = 'No se encontró la definición del flujo de trabajo.';
$messages['duplicate_workflow_key'] = 'La clave del flujo de trabajo ya existe.';
$messages['form_new_title'] = 'Nuevo objetivo';
$messages['form_edit_title'] = 'Editar objetivo';
$messages['form_subtitle'] = 'Editar flujo de trabajo';
$messages['form_new_info'] = 'Cree un nuevo objetivo y defina lo que se necesita para alcanzarlo.';
$messages['form_edit_info'] = 'Edite el objetivo y defina lo que se necesita para alcanzarlo.';
$messages['list_label'] = 'Lista';
$messages['save_label'] = 'Guardar';
$messages['action_form'] = 'Editar / confirmar';
$messages['action_select'] = 'Seleccionar';
$messages['action_create'] = 'Crear nuevo';
$messages['action_module'] = 'Abrir formulario del módulo';
$messages['action_module_short'] = 'Formulario del módulo';
$messages['kind_input'] = 'Entrada';
$messages['kind_action'] = 'Acción';
$messages['kind_check'] = 'Comprobación';
$messages['kind_decision'] = 'Decisión';
$messages['automation_manual'] = 'Editar manualmente';
$messages['automation_observe'] = 'Comprobar automáticamente; en caso contrario, manualmente';
$messages['mode_single'] = 'Un valor';
$messages['mode_multiple'] = 'Varios valores';
$messages['validation_exactly_one'] = 'Exactamente un valor';
$messages['validation_at_least_one'] = 'Al menos un valor';
$messages['validation_not_empty'] = 'No vacío';
$messages['validation_positive_integer'] = 'Entero mayor que 0';
$messages['validation_confirmed'] = 'Confirmado expresamente';
$messages['default_value_label'] = 'Dato';
$messages['default_question'] = '¿Está “{label}” completo y correcto?';
$messages['default_missing_message'] = 'Falta {label} o está incompleto; el flujo de trabajo está incompleto.';
$messages['resolver_form'] = 'Abrir formulario de entrada';
$messages['resolver_select'] = 'Abrir formulario de selección';
$messages['resolver_create'] = 'Abrir formulario de creación';
$messages['resolver_module'] = 'Abrir formulario del módulo';
$messages['depends_always'] = 'Mostrar siempre';
$messages['step_move'] = 'Mover paso';
$messages['new_task'] = 'Nueva tarea';
$messages['no_result'] = 'Todavía no hay texto de resultado';
$messages['automation_badge'] = 'Automático';
$messages['step_remove'] = 'Eliminar paso';
$messages['field_building_block'] = 'Bloque';
$messages['field_label'] = 'Nombre';
$messages['field_key'] = 'Clave interna';
$messages['field_result'] = 'Resultado / estado posterior';
$messages['field_allowed_actions'] = 'Acciones permitidas';
$messages['field_default_action'] = 'Acción predeterminada';
$messages['field_automation'] = 'Automatización';
$messages['field_values'] = 'Valores';
$messages['field_required'] = 'Obligatorio';
$messages['required_yes'] = 'Obligatorio';
$messages['required_no'] = 'Opcional';
$messages['field_module_confirmation'] = 'Confirmación tras el formulario del módulo';
$messages['external_actions_confirmed'] = 'Las acciones externas permanecen confirmadas';
$messages['automatic_check'] = 'Comprobación automática';
$messages['automatic_check_hint'] = 'Se genera a partir de este paso y no requiere mantenimiento independiente.';
$messages['field_question'] = 'Pregunta de comprobación';
$messages['field_validation'] = 'Completo cuando';
$messages['field_resolver'] = 'Formulario adecuado';
$messages['field_missing_message'] = 'Mensaje para un dato ausente o incorrecto';
$messages['field_depends'] = 'Requisito / línea desde';
$messages['field_depends_value'] = 'Solo con el resultado';
$messages['field_options'] = 'Resultados de selección / decisión';
$messages['field_hint'] = 'Nota para el editor';
$messages['placeholder_label'] = 'Seleccionar artículo';
$messages['placeholder_key'] = 'seleccionar_articulo';
$messages['placeholder_result'] = 'Artículo seleccionado';
$messages['placeholder_module_confirmation'] = 'La tarea se completó en el formulario especializado.';
$messages['placeholder_question'] = '¿Qué dato está seleccionado?';
$messages['placeholder_resolver'] = 'Abrir formulario de selección';
$messages['placeholder_missing'] = 'Ninguna selección; flujo de trabajo incompleto.';
$messages['placeholder_depends_value'] = 'p. ej., aprobado; vacío = siempre';
$messages['placeholder_options'] = 'valor=Texto, un resultado por línea';
$messages['placeholder_hint'] = '¿Qué debe completarse, confirmarse o comprobarse?';
$messages['preview_required'] = 'Obligatorio';
$messages['preview_optional'] = 'Opcional';
$messages['finish_default'] = 'Finalizar {result}';
$messages['validation_step_key_missing'] = 'El paso {step} no tiene clave interna.';
$messages['validation_step_key_duplicate'] = 'La clave interna “{key}” se utiliza más de una vez.';
$messages['validation_decision_options'] = 'La decisión “{label}” requiere al menos dos resultados posibles.';
$messages['validation_dependency_missing'] = 'El requisito “{dependency}” de “{key}” no existe.';
$messages['validation_dependency_order'] = 'El paso “{key}” debe estar situado después de su requisito “{dependency}”.';
$messages['validation_minimum_step'] = 'Se necesita al menos un paso del flujo de trabajo.';
$messages['js_new_input'] = 'Nueva entrada';
$messages['js_new_action'] = 'Nueva acción';
$messages['js_new_check'] = 'Nueva comprobación';
$messages['js_new_decision'] = 'Nueva decisión';
$messages['js_input_complete'] = 'Entrada completa';
$messages['js_action_complete'] = 'Acción ejecutada';
$messages['js_check_complete'] = 'Comprobación finalizada';
$messages['js_decision_complete'] = 'Decisión tomada';
$messages['js_requirement_singular'] = 'requisito';
$messages['js_requirement_plural'] = 'requisitos';
$messages['js_direct_after_previous'] = 'Directamente después del paso anterior';
$messages['js_error_label_missing'] = 'El paso {step} necesita un nombre.';
$messages['js_error_key_missing'] = 'El paso {step} necesita una clave interna.';
$messages['js_error_key_duplicate'] = 'La clave “{key}” se utiliza más de una vez.';
$messages['js_error_question_missing'] = 'Falta la pregunta de comprobación utilizada automáticamente para “{label}”.';
$messages['js_error_decision_options'] = 'La decisión “{label}” necesita al menos dos resultados.';
$messages['js_warning_automation'] = 'La automatización de “{label}” solo es adecuada como comprobación o decisión.';
$messages['js_warning_select_source'] = 'El formulario de selección de “{label}” todavía no tiene valores ni fuente de datos.';
$messages['js_warning_module_link'] = 'Todavía no se ha configurado ningún formulario de módulo para “{label}”.';
$messages['js_error_dependency_missing'] = 'La dependencia “{dependency}” de “{key}” no existe.';
$messages['js_error_dependency_order'] = '“{key}” debe estar situado después de su requisito “{dependency}”.';
$messages['js_status_invalid'] = 'El flujo de trabajo todavía no se puede guardar';
$messages['js_status_warning'] = 'El flujo de trabajo se puede guardar; revise las notas';
$messages['js_status_valid'] = 'Comprobación derivada automáticamente';
$messages['js_status_valid_detail'] = '{steps} pasos proporcionan {requirements} requisitos de comprobación con la vía de edición adecuada.';
$messages['js_no_free_step'] = 'No quedan pasos libres';
$messages['js_no_free_step_detail'] = 'Guarde y vuelva a abrir el flujo de trabajo para añadir más pasos.';
$messages['js_default_event'] = 'Dato completo';
$messages['js_yes'] = 'Sí';
$messages['js_no'] = 'No';
$messages['js_payment_label'] = 'Condiciones de pago';
$messages['js_payment_event'] = 'Condiciones de pago seleccionadas';
$messages['js_payment_question'] = '¿Qué condiciones de pago están seleccionadas?';
$messages['js_payment_missing'] = 'No se han seleccionado condiciones de pago; el flujo de trabajo está incompleto.';
$messages['js_payment_resolver'] = 'Seleccionar condiciones de pago';
$messages['js_payment_hint'] = 'Seleccione el plazo de pago que debe aplicarse a este proceso.';
$messages['js_payment_options'] = "inmediato=Vencimiento inmediato\n7_dias=7 días netos\n14_dias=14 días netos\n30_dias=30 días netos";


$addField = function($name, $type, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']='';
   $field['length']=$extra['length'] ?? '';
   $field['default']=$extra['default'] ?? '';
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']='';
   $field['protect']='0';
   $field['mask']='';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$addField('workflow_key','varchar','Workflow Key','parameter|min=2|max=80','text-label',array('placeholder'=>'invoice_demo'));
$addField('title','varchar','Nombre','*|min=2|max=160','text-label',array('placeholder'=>'Publicar artículos sobre eBay'));
$addField('result_label','varchar','Objetivo','*|min=2|max=160','text-label',array('placeholder'=>'Artículo publicado en eBay'));
$addField('description','mediumtext','Descripción','*|max=3000','textarea-label',array('data'=>'rows=2'));
$addField('definition_json','mediumtext','Definición','*|min=2|max=20000','textarea-label',array('data'=>'rows=16'));
$addField('active','int','Activo','int','checkbox-label',array('default'=>'1'));

?>
