<?php
$messages = array();
$messages['validation_error'] = 'Bitte Eingaben prüfen.';
$messages['definition_not_found'] = 'Workflow-Definition nicht gefunden.';
$messages['duplicate_workflow_key'] = 'Der Workflow Key existiert bereits.';
$messages['form_new_title'] = 'Neues Ziel';
$messages['form_edit_title'] = 'Ziel bearbeiten';
$messages['form_subtitle'] = 'Workflow bearbeiten';
$messages['form_new_info'] = 'Neues Ziel anlegen und definieren, was dafür notwendig ist.';
$messages['form_edit_info'] = 'Ziel bearbeiten und festlegen, was dafür notwendig ist.';
$messages['list_label'] = 'Liste';
$messages['save_label'] = 'Speichern';
$messages['action_form'] = 'Bearbeiten / bestätigen';
$messages['action_select'] = 'Auswählen';
$messages['action_create'] = 'Neu anlegen';
$messages['action_module'] = 'Modulformular öffnen';
$messages['action_module_short'] = 'Modulformular';
$messages['kind_input'] = 'Eingabe';
$messages['kind_action'] = 'Aktion';
$messages['kind_check'] = 'Prüfung';
$messages['kind_decision'] = 'Entscheidung';
$messages['automation_manual'] = 'Manuell bearbeiten';
$messages['automation_observe'] = 'Automatisch prüfen, sonst manuell';
$messages['mode_single'] = 'Ein Wert';
$messages['mode_multiple'] = 'Mehrere Werte';
$messages['validation_exactly_one'] = 'Genau ein Wert';
$messages['validation_at_least_one'] = 'Mindestens ein Wert';
$messages['validation_not_empty'] = 'Nicht leer';
$messages['validation_positive_integer'] = 'Ganzzahl größer 0';
$messages['validation_confirmed'] = 'Ausdrücklich bestätigt';
$messages['default_value_label'] = 'Angabe';
$messages['default_question'] = 'Ist „{label}“ vollständig und richtig?';
$messages['default_missing_message'] = '{label} fehlt oder ist nicht vollständig – der Workflow ist unvollständig.';
$messages['resolver_form'] = 'Eingabeformular öffnen';
$messages['resolver_select'] = 'Auswahlformular öffnen';
$messages['resolver_create'] = 'Erfassungsformular öffnen';
$messages['resolver_module'] = 'Modulformular öffnen';
$messages['depends_always'] = 'Immer anzeigen';
$messages['step_move'] = 'Schritt verschieben';
$messages['new_task'] = 'Neue Aufgabe';
$messages['no_result'] = 'Noch kein Ergebnistext';
$messages['automation_badge'] = 'Automatik';
$messages['step_remove'] = 'Schritt entfernen';
$messages['field_building_block'] = 'Baustein';
$messages['field_label'] = 'Bezeichnung';
$messages['field_key'] = 'Interner Schlüssel';
$messages['field_result'] = 'Ergebnis / Status danach';
$messages['field_allowed_actions'] = 'Erlaubte Bearbeitungen';
$messages['field_default_action'] = 'Standardbearbeitung';
$messages['field_automation'] = 'Automatisierung';
$messages['field_values'] = 'Werte';
$messages['field_required'] = 'Pflicht';
$messages['required_yes'] = 'Notwendig';
$messages['required_no'] = 'Optional';
$messages['field_module_confirmation'] = 'Bestätigung nach Modulformular';
$messages['external_actions_confirmed'] = 'Externe Aktionen bleiben bestätigt';
$messages['automatic_check'] = 'Automatische Prüfung';
$messages['automatic_check_hint'] = 'Wird aus diesem Schritt erzeugt und muss nicht separat gepflegt werden.';
$messages['field_question'] = 'Prüffrage';
$messages['field_validation'] = 'Vollständig, wenn';
$messages['field_resolver'] = 'Passendes Formular';
$messages['field_missing_message'] = 'Meldung bei fehlender oder falscher Angabe';
$messages['field_depends'] = 'Voraussetzung / Linie von';
$messages['field_depends_value'] = 'Nur bei Ergebnis';
$messages['field_options'] = 'Auswahl- / Entscheidungsergebnisse';
$messages['field_hint'] = 'Hinweis für Bearbeiter';
$messages['placeholder_label'] = 'Artikel auswählen';
$messages['placeholder_key'] = 'artikel_auswaehlen';
$messages['placeholder_result'] = 'Artikel ausgewählt';
$messages['placeholder_module_confirmation'] = 'Aufgabe wurde im Fachformular erledigt.';
$messages['placeholder_question'] = 'Welche Angabe ist ausgewählt?';
$messages['placeholder_resolver'] = 'Auswahlformular öffnen';
$messages['placeholder_missing'] = 'Keine Auswahl – Workflow unvollständig.';
$messages['placeholder_depends_value'] = 'z. B. freigegeben; leer = immer';
$messages['placeholder_options'] = 'wert=Anzeige, je Zeile ein Ergebnis';
$messages['placeholder_hint'] = 'Was muss erledigt, bestätigt oder geprüft werden?';
$messages['preview_required'] = 'Pflicht';
$messages['preview_optional'] = 'Optional';
$messages['finish_default'] = '{result} abschließen';
$messages['validation_step_key_missing'] = 'Schritt {step} hat keinen internen Schlüssel.';
$messages['validation_step_key_duplicate'] = 'Der interne Schlüssel „{key}“ wird mehrfach verwendet.';
$messages['validation_decision_options'] = 'Die Entscheidung „{label}“ benötigt mindestens zwei mögliche Ergebnisse.';
$messages['validation_dependency_missing'] = 'Die Voraussetzung „{dependency}“ für „{key}“ existiert nicht.';
$messages['validation_dependency_order'] = 'Der Schritt „{key}“ muss hinter seiner Voraussetzung „{dependency}“ liegen.';
$messages['validation_minimum_step'] = 'Mindestens ein Workflow-Schritt ist erforderlich.';
$messages['js_new_input'] = 'Neue Eingabe';
$messages['js_new_action'] = 'Neue Aktion';
$messages['js_new_check'] = 'Neue Prüfung';
$messages['js_new_decision'] = 'Neue Entscheidung';
$messages['js_input_complete'] = 'Eingabe vollständig';
$messages['js_action_complete'] = 'Aktion ausgeführt';
$messages['js_check_complete'] = 'Prüfung abgeschlossen';
$messages['js_decision_complete'] = 'Entscheidung getroffen';
$messages['js_requirement_singular'] = 'Anforderung';
$messages['js_requirement_plural'] = 'Anforderungen';
$messages['js_direct_after_previous'] = 'Direkt nach vorherigem Schritt';
$messages['js_error_label_missing'] = 'Schritt {step} braucht eine Bezeichnung.';
$messages['js_error_key_missing'] = 'Schritt {step} braucht einen internen Schlüssel.';
$messages['js_error_key_duplicate'] = 'Der Schlüssel „{key}“ wird mehrfach verwendet.';
$messages['js_error_question_missing'] = 'Für „{label}“ fehlt die automatisch verwendete Prüffrage.';
$messages['js_error_decision_options'] = 'Die Entscheidung „{label}“ braucht mindestens zwei Ergebnisse.';
$messages['js_warning_automation'] = 'Automatik bei „{label}“ ist nur sinnvoll als Prüfung oder Entscheidung.';
$messages['js_warning_select_source'] = 'Das Auswahlformular für „{label}“ hat noch keine Auswahlwerte oder Datenquelle.';
$messages['js_warning_module_link'] = 'Für „{label}“ ist noch kein Modulformular hinterlegt.';
$messages['js_error_dependency_missing'] = 'Die Abhängigkeit „{dependency}“ von „{key}“ existiert nicht.';
$messages['js_error_dependency_order'] = '„{key}“ muss hinter seiner Voraussetzung „{dependency}“ liegen.';
$messages['js_status_invalid'] = 'Workflow noch nicht speicherbar';
$messages['js_status_warning'] = 'Workflow ist speicherbar – Hinweise prüfen';
$messages['js_status_valid'] = 'Prüfung wurde automatisch abgeleitet';
$messages['js_status_valid_detail'] = '{steps} Schritte liefern {requirements} Prüfanforderungen samt passendem Bearbeitungsweg.';
$messages['js_no_free_step'] = 'Kein freier Schritt mehr';
$messages['js_no_free_step_detail'] = 'Workflow speichern und erneut öffnen, um weitere Schritte anzulegen.';
$messages['js_default_event'] = 'Angabe vollständig';
$messages['js_yes'] = 'Ja';
$messages['js_no'] = 'Nein';
$messages['js_payment_label'] = 'Zahlungsbedingung';
$messages['js_payment_event'] = 'Zahlungsbedingung ausgewählt';
$messages['js_payment_question'] = 'Welche Zahlungsbedingung ist ausgewählt?';
$messages['js_payment_missing'] = 'Keine Zahlungsbedingung ausgewählt – der Workflow ist unvollständig.';
$messages['js_payment_resolver'] = 'Zahlungsbedingung auswählen';
$messages['js_payment_hint'] = 'Wähle die Zahlungsfrist, die für diesen Vorgang gelten soll.';
$messages['js_payment_options'] = "sofort=Sofort fällig\n7_tage=7 Tage netto\n14_tage=14 Tage netto\n30_tage=30 Tage netto";


$add_field = function($name, $type, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']='';
   $field['length']=$extra['length'] ?? '';
   $field['default']=$extra['default'] ?? '';
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']='';
   $field['protect']='0';
   $field['mask']='';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$add_field('workflow_key','varchar','Workflow Key','parameter|min=2|max=80','text-label',array('placeholder'=>'invoice_demo'));
$add_field('title','varchar','Name','*|min=2|max=160','text-label',array('placeholder'=>'Artikel bei eBay veroeffentlichen'));
$add_field('result_label','varchar','Ziel','*|min=2|max=160','text-label',array('placeholder'=>'Bestehender Artikel ist bei eBay veroeffentlicht'));
$add_field('description','mediumtext','Beschreibung','*|max=3000','textarea-label',array('data'=>'rows=2'));
$add_field('definition_json','mediumtext','Definition','*|min=2|max=20000','textarea-label',array('data'=>'rows=16'));
$add_field('active','int','Aktiv','int','checkbox-label',array('default'=>'1'));

?>
