<?php
$messages = array();
$messages['save_success'] = 'Data was saved';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Data could not be saved';
$messages['validation_error'] = 'Please check your entries.';
$messages['definition_not_found'] = 'Workflow definition not found.';
$messages['duplicate_workflow_key'] = 'The workflow key already exists.';
$messages['form_new_title'] = 'New goal';
$messages['form_edit_title'] = 'Edit goal';
$messages['form_subtitle'] = 'Edit workflow';
$messages['form_new_info'] = 'Create a new goal and define what is required for it.';
$messages['form_edit_info'] = 'Edit the goal and define what is required for it.';
$messages['list_label'] = 'List';
$messages['save_label'] = 'Save';
$messages['action_form'] = 'Edit / confirm';
$messages['action_select'] = 'Select';
$messages['action_create'] = 'Create new';
$messages['action_module'] = 'Open module form';
$messages['action_module_short'] = 'Module form';
$messages['kind_input'] = 'Input';
$messages['kind_action'] = 'Action';
$messages['kind_check'] = 'Check';
$messages['kind_decision'] = 'Decision';
$messages['automation_manual'] = 'Edit manually';
$messages['automation_observe'] = 'Check automatically, otherwise manually';
$messages['mode_single'] = 'One value';
$messages['mode_multiple'] = 'Multiple values';
$messages['validation_exactly_one'] = 'Exactly one value';
$messages['validation_at_least_one'] = 'At least one value';
$messages['validation_not_empty'] = 'Not empty';
$messages['validation_positive_integer'] = 'Integer greater than 0';
$messages['validation_confirmed'] = 'Explicitly confirmed';
$messages['default_value_label'] = 'Value';
$messages['default_question'] = 'Is “{label}” complete and correct?';
$messages['default_missing_message'] = '{label} is missing or incomplete – the workflow is incomplete.';
$messages['resolver_form'] = 'Open input form';
$messages['resolver_select'] = 'Open selection form';
$messages['resolver_create'] = 'Open creation form';
$messages['resolver_module'] = 'Open module form';
$messages['depends_always'] = 'Always show';
$messages['step_move'] = 'Move step';
$messages['new_task'] = 'New task';
$messages['no_result'] = 'No result text yet';
$messages['automation_badge'] = 'Automatic';
$messages['step_remove'] = 'Remove step';
$messages['field_building_block'] = 'Building block';
$messages['field_label'] = 'Label';
$messages['field_key'] = 'Internal key';
$messages['field_result'] = 'Result / status afterwards';
$messages['field_allowed_actions'] = 'Allowed actions';
$messages['field_default_action'] = 'Default action';
$messages['field_automation'] = 'Automation';
$messages['field_values'] = 'Values';
$messages['field_required'] = 'Required';
$messages['required_yes'] = 'Required';
$messages['required_no'] = 'Optional';
$messages['field_module_confirmation'] = 'Confirmation after module form';
$messages['external_actions_confirmed'] = 'External actions remain confirmed';
$messages['automatic_check'] = 'Automatic check';
$messages['automatic_check_hint'] = 'Generated from this step and does not need separate maintenance.';
$messages['field_question'] = 'Check question';
$messages['field_validation'] = 'Complete when';
$messages['field_resolver'] = 'Matching form';
$messages['field_missing_message'] = 'Message for a missing or invalid value';
$messages['field_depends'] = 'Dependency / line from';
$messages['field_depends_value'] = 'Only for result';
$messages['field_options'] = 'Selection / decision results';
$messages['field_hint'] = 'Note for editor';
$messages['placeholder_label'] = 'Select item';
$messages['placeholder_key'] = 'select_item';
$messages['placeholder_result'] = 'Item selected';
$messages['placeholder_module_confirmation'] = 'Task was completed in the specialist form.';
$messages['placeholder_question'] = 'Which value is selected?';
$messages['placeholder_resolver'] = 'Open selection form';
$messages['placeholder_missing'] = 'No selection – workflow incomplete.';
$messages['placeholder_depends_value'] = 'e.g. approved; empty = always';
$messages['placeholder_options'] = 'value=Label, one result per line';
$messages['placeholder_hint'] = 'What must be completed, confirmed or checked?';
$messages['preview_required'] = 'Required';
$messages['preview_optional'] = 'Optional';
$messages['finish_default'] = 'Complete {result}';
$messages['validation_step_key_missing'] = 'Step {step} has no internal key.';
$messages['validation_step_key_duplicate'] = 'The internal key “{key}” is used more than once.';
$messages['validation_decision_options'] = 'The decision “{label}” requires at least two possible results.';
$messages['validation_dependency_missing'] = 'The dependency “{dependency}” for “{key}” does not exist.';
$messages['validation_dependency_order'] = 'Step “{key}” must be placed after its dependency “{dependency}”.';
$messages['validation_minimum_step'] = 'At least one workflow step is required.';
$messages['js_new_input'] = 'New input';
$messages['js_new_action'] = 'New action';
$messages['js_new_check'] = 'New check';
$messages['js_new_decision'] = 'New decision';
$messages['js_input_complete'] = 'Input complete';
$messages['js_action_complete'] = 'Action completed';
$messages['js_check_complete'] = 'Check completed';
$messages['js_decision_complete'] = 'Decision made';
$messages['js_requirement_singular'] = 'requirement';
$messages['js_requirement_plural'] = 'requirements';
$messages['js_direct_after_previous'] = 'Directly after the previous step';
$messages['js_error_label_missing'] = 'Step {step} needs a label.';
$messages['js_error_key_missing'] = 'Step {step} needs an internal key.';
$messages['js_error_key_duplicate'] = 'The key “{key}” is used more than once.';
$messages['js_error_question_missing'] = 'The automatically used check question for “{label}” is missing.';
$messages['js_error_decision_options'] = 'The decision “{label}” needs at least two results.';
$messages['js_warning_automation'] = 'Automation for “{label}” is only useful as a check or decision.';
$messages['js_warning_select_source'] = 'The selection form for “{label}” has no selection values or data source yet.';
$messages['js_warning_module_link'] = 'No module form has been configured for “{label}” yet.';
$messages['js_error_dependency_missing'] = 'The dependency “{dependency}” of “{key}” does not exist.';
$messages['js_error_dependency_order'] = '“{key}” must be placed after its dependency “{dependency}”.';
$messages['js_status_invalid'] = 'Workflow cannot be saved yet';
$messages['js_status_warning'] = 'Workflow can be saved – review the notes';
$messages['js_status_valid'] = 'Check derived automatically';
$messages['js_status_valid_detail'] = '{steps} steps provide {requirements} check requirements including a suitable editing path.';
$messages['js_no_free_step'] = 'No free step available';
$messages['js_no_free_step_detail'] = 'Save and reopen the workflow to add more steps.';
$messages['js_default_event'] = 'Value complete';
$messages['js_yes'] = 'Yes';
$messages['js_no'] = 'No';
$messages['js_payment_label'] = 'Payment terms';
$messages['js_payment_event'] = 'Payment terms selected';
$messages['js_payment_question'] = 'Which payment terms are selected?';
$messages['js_payment_missing'] = 'No payment terms selected – the workflow is incomplete.';
$messages['js_payment_resolver'] = 'Select payment terms';
$messages['js_payment_hint'] = 'Select the payment period that should apply to this process.';
$messages['js_payment_options'] = "due=Due immediately\n7_days=7 days net\n14_days=14 days net\n30_days=30 days net";


$addField = function($name, $type, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']='';
   $field['length']=$extra['length'] ?? '';
   $field['default']=$extra['default'] ?? '';
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']='';
   $field['protect']='0';
   $field['mask']='';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$addField('workflow_key','varchar','Workflow Key','parameter|min=2|max=80','text-label',array('placeholder'=>'invoice_demo'));
$addField('title','varchar','Name','*|min=2|max=160','text-label',array('placeholder'=>'Publish articles on eBay'));
$addField('result_label','varchar','Goal','*|min=2|max=160','text-label',array('placeholder'=>'Existing article published on eBay'));
$addField('description','mediumtext','Description','*|max=3000','textarea-label',array('data'=>'rows=2'));
$addField('definition_json','mediumtext','Definition','*|min=2|max=20000','textarea-label',array('data'=>'rows=16'));
$addField('active','int','Active','int','checkbox-label',array('default'=>'1'));

?>
