<?php
$messages = array();
$messages['login_info'] = 'Inicie sesión con su nombre de usuario y contraseña';
$messages['login_error'] = 'No se encontró el nombre de usuario y/o la contraseña';
$messages['login_success'] = 'Inicio de sesión correcto';

$field = array();
$field['name'] = 'username';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '120';
$field['default'] = '';
$field['label'] = 'Nombre de usuario o correo electrónico';
$field['rules'] = 'varchar|min=4|max=120';
$field['tooltip'] = '';
$field['errormsg'] = 'Por favor introduzca su nombre de usuario o dirección de correo electrónico.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-person&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'password';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Contraseña';
$field['rules'] = 'varchar|min=6|max=128';
$field['tooltip'] = '';
$field['errormsg'] = 'La contraseña debe tener al menos 6 caracteres de largo.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-key&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-password-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;
