<?php
$messages = array();
$messages['save_success'] = 'Daten wurden gespeichert';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Daten konnten nicht gespeichert werden';
$messages['login_info'] = 'Bitte mit Benutzername und Passwort anmelden';
$messages['login_error'] = 'Benutzername und/oder Passwort nicht gefunden';
$messages['login_success'] = 'Login erfolgreich';

$field = array();
$field['name'] = 'username';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '120';
$field['default'] = '';
$field['label'] = 'Benutzername oder E-Mail';
$field['rules'] = 'varchar|min=4|max=120';
$field['tooltip'] = '';
$field['errormsg'] = 'Bitte Benutzername oder E-Mail-Adresse eingeben.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-person&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'password';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Passwort';
$field['rules'] = 'varchar|min=6|max=128';
$field['tooltip'] = '';
$field['errormsg'] = 'Das Passwort muss mindestens 6 Zeichen lang sein.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-key&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-password-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;
