<?php
$messages = array();
$messages['save_success'] = 'Data was saved';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Data could not be saved';
$messages['page_title'] = 'Registration';
$messages['bar_title'] = 'Register';
$messages['bar_subtitle'] = 'Create an account and confirm your email address';
$messages['form_info'] = 'Register with {domain}.';
$messages['password_mismatch'] = 'The passwords do not match.';
$messages['user_exists'] = 'The user name or email address already exists.';
$messages['register_success'] = 'Registration was saved. Please confirm your email address using the link in the email.';
$messages['confirm_mail_error'] = 'The user was created, but the confirmation email could not be sent.';
$messages['register_error'] = 'The user could not be created.';
$messages['validation_error'] = 'Please check your entries.';

$field = array();
$field['name'] = 'uname';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'Login name';
$field['rules'] = 'parameter|min=4|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'The login name must be at least 4 characters long and must contain only letters, numbers, dot, underscore and hyphen.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-person-badge&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'Name';
$field['rules'] = 'words|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'The name may contain letters, numbers, spaces and simple punctuation marks.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-person-vcard&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'email';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'E-mail';
$field['rules'] = 'email|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'Please enter a valid email address.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-envelope&field_class=dbx-auth-field-wide';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'password';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Password';
$field['rules'] = 'varchar|min=6|max=128';
$field['tooltip'] = '';
$field['errormsg'] = 'The password must be at least 6 characters long.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-key&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-password-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'password2';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Repeat the password';
$field['rules'] = 'varchar|min=6|max=128';
$field['tooltip'] = '';
$field['errormsg'] = 'Please repeat the password.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-key-fill&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-password-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'language';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '3';
$field['default'] = 'de';
$field['label'] = 'Language';
$field['rules'] = 'parameter|min=2|max=3';
$field['tooltip'] = '';
$field['errormsg'] = 'Please select a language.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-translate&field_class=dbx-auth-field-wide';
$field['options'] = 'de=German&en=English&es=Spanish';
$field['tpl'] = 'auth-select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;
