<?php
$messages = array();
$messages['save_success'] = 'Daten wurden gespeichert';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Daten konnten nicht gespeichert werden';
$messages['page_title'] = 'Registrierung';
$messages['bar_title'] = 'Registrieren';
$messages['bar_subtitle'] = 'Konto anlegen und E-Mail-Adresse bestätigen';
$messages['form_info'] = 'Bei {domain} anmelden.';
$messages['password_mismatch'] = 'Passwörter stimmen nicht überein.';
$messages['user_exists'] = 'Benutzer oder E-Mail existiert bereits.';
$messages['register_success'] = 'Registrierung gespeichert. Bitte bestätigen Sie Ihre E-Mail-Adresse über den Link in der E-Mail.';
$messages['confirm_mail_error'] = 'Der Benutzer wurde angelegt, aber die Bestätigungs-E-Mail konnte nicht gesendet werden.';
$messages['register_error'] = 'Der Benutzer konnte nicht angelegt werden.';
$messages['validation_error'] = 'Bitte prüfen Sie Ihre Eingaben.';

$field = array();
$field['name'] = 'uname';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'Loginname';
$field['rules'] = 'parameter|min=4|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'Der Loginname muss mindestens 4 Zeichen lang sein und darf nur Buchstaben, Zahlen, Punkt, Unterstrich und Bindestrich enthalten.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-person-badge&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'Name';
$field['rules'] = 'words|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'Der Name darf Buchstaben, Zahlen, Leerzeichen und einfache Satzzeichen enthalten.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-person-vcard&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'email';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'E-Mail';
$field['rules'] = 'email|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'Bitte eine gueltige E-Mail-Adresse eingeben.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-envelope&field_class=dbx-auth-field-wide';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'password';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Passwort';
$field['rules'] = 'varchar|min=6|max=128';
$field['tooltip'] = '';
$field['errormsg'] = 'Das Passwort muss mindestens 6 Zeichen lang sein.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-key&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-password-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'password2';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Passwort wiederholen';
$field['rules'] = 'varchar|min=6|max=128';
$field['tooltip'] = '';
$field['errormsg'] = 'Bitte das Passwort wiederholen.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-key-fill&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-password-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'language';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '3';
$field['default'] = 'de';
$field['label'] = 'Sprache';
$field['rules'] = 'parameter|min=2|max=3';
$field['tooltip'] = '';
$field['errormsg'] = 'Bitte eine Sprache auswaehlen.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-translate&field_class=dbx-auth-field-wide';
$field['options'] = 'de=Deutsch&en=English&es=Español';
$field['tpl'] = 'auth-select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;
