<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['page_title'] = 'Registro';
$messages['bar_title'] = 'Registrarse';
$messages['bar_subtitle'] = 'Crear una cuenta y confirmar la dirección de correo electrónico';
$messages['form_info'] = 'Regístrese en {domain}.';
$messages['password_mismatch'] = 'Las contraseñas no coinciden.';
$messages['user_exists'] = 'El nombre de usuario o la dirección de correo electrónico ya existen.';
$messages['register_success'] = 'El registro se guardó. Confirme su dirección de correo electrónico mediante el enlace del mensaje.';
$messages['confirm_mail_error'] = 'Se creó el usuario, pero no se pudo enviar el correo electrónico de confirmación.';
$messages['register_error'] = 'No se pudo crear el usuario.';
$messages['validation_error'] = 'Revise los datos introducidos.';

$field = array();
$field['name'] = 'uname';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'Nombre de usuario';
$field['rules'] = 'parameter|min=4|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'El nombre de usuario debe tener al menos 4 caracteres y solo puede contener letras, números, puntos, guiones bajos y guiones.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-person-badge&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'Nombre';
$field['rules'] = 'words|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'El nombre puede contener letras, números, espacios y signos de puntuación sencillos.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-person-vcard&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'email';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '60';
$field['default'] = '';
$field['label'] = 'E-mail';
$field['rules'] = 'email|max=60';
$field['tooltip'] = '';
$field['errormsg'] = 'Por favor, introduzca una dirección de correo electrónico válida.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-envelope&field_class=dbx-auth-field-wide';
$field['options'] = '';
$field['tpl'] = 'auth-text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'password';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Contraseña';
$field['rules'] = 'varchar|min=6|max=128';
$field['tooltip'] = '';
$field['errormsg'] = 'La contraseña debe tener al menos 6 caracteres de largo.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-key&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-password-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'password2';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Repita la contraseña';
$field['rules'] = 'varchar|min=6|max=128';
$field['tooltip'] = '';
$field['errormsg'] = 'Por favor, repita la contraseña.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-key-fill&field_class=';
$field['options'] = '';
$field['tpl'] = 'auth-password-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'language';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '3';
$field['default'] = 'de';
$field['label'] = 'Idioma';
$field['rules'] = 'parameter|min=2|max=3';
$field['tooltip'] = '';
$field['errormsg'] = 'Por favor, seleccione un idioma.';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = 'icon=bi-translate&field_class=dbx-auth-field-wide';
$field['options'] = 'de=Alemán&en=Inglés&es=Español';
$field['tpl'] = 'auth-select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;
