<?php
$messages = array();
$messages['save_success'] = 'Daten wurden gespeichert';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Daten konnten nicht gespeichert werden';
$messages['bar_title'] = 'Content';
$messages['bar_subtitle'] = 'Seiten der aktuell gewählten Sprache.';
$messages['stats_title'] = 'Content-Kennzahlen';
$messages['stats_pages'] = 'Seiten';
$messages['stats_active'] = 'Aktiv';
$messages['stats_inactive'] = 'Inaktiv';
$messages['column_title'] = 'Titel';
$messages['column_permalink'] = 'Permalink';
$messages['column_folder'] = 'Ordner';
$messages['column_active'] = 'Aktiv';
$messages['column_updated'] = 'Geändert';
$messages['status_active'] = 'Aktiv';
$messages['status_inactive'] = 'Inaktiv';
$messages['cms_label'] = 'Content CMS';
$messages['section_folders_title'] = 'Ordner';
$messages['section_folders_subtitle'] = 'Content-Ordner der aktuell gewählten Sprache.';
$messages['section_media_title'] = 'Medien';
$messages['section_media_subtitle'] = 'Zentrale Medien aus dbxMedia.';
$messages['section_templates_title'] = 'Content-Templates';
$messages['section_templates_subtitle'] = 'Verfügbare Templates aus dbxContent/tpl/htm.';
$messages['column_template'] = 'Template';
$messages['column_read_rights'] = 'Leserechte';
$messages['column_preview'] = 'Vorschau';
$messages['column_type'] = 'Typ';
$messages['column_provider'] = 'Provider';
$messages['column_usage'] = 'Verwendung';
$messages['column_module'] = 'Modul';
$messages['column_bytes'] = 'Bytes';
$messages['edit_template'] = 'Template bearbeiten';
$messages['edit_in_cms'] = 'Im Content CMS bearbeiten';
$messages['edit_folder_in_cms'] = 'Content-Ordner im CMS bearbeiten';
$messages['confirm_folder_delete'] = 'Diesen Content-Ordner wirklich löschen?';
$messages['confirm_media_delete'] = 'Dieses Medium wirklich löschen?';
$messages['confirm_template_delete'] = 'Dieses Content-Template wirklich löschen?';
$messages['media_not_found'] = 'Medium nicht gefunden.';
$messages['template_deleted'] = 'Template gelöscht: {name}.htm';
$messages['template_delete_error'] = 'Template konnte nicht gelöscht werden.';
$messages['template_create_error'] = 'Template konnte nicht angelegt werden.';
$messages['template_name_validation'] = 'Bitte den rot markierten Template-Namen prüfen.';
$messages['template_new_title'] = 'Neues Content-Template';
$messages['template_new_info'] = 'Einen eindeutigen Namen für das neue c-* Content-Template eingeben.';
$messages['template_name_label'] = 'Template-Name';
$messages['template_name_error'] = 'Der Name muss mit c- beginnen und darf nur Buchstaben, Zahlen, Bindestrich und Unterstrich enthalten.';
$messages['section_undefined'] = 'Content-Bereich „{section}“ ist nicht definiert.';
$messages['template_invalid_name'] = 'Ungültiger Template-Name. Erlaubt: c-name mit Buchstaben, Zahlen, Bindestrich und Unterstrich.';
$messages['template_path_error'] = 'Template-Pfad konnte nicht ermittelt werden.';
$messages['template_exists'] = 'Template existiert bereits: {name}.htm';
$messages['template_created'] = 'Template angelegt: {name}.htm';
$messages['template_new_button'] = 'Neues Template';
$messages['template_new_action_title'] = 'Neues c-* Template anlegen';


$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['default']='25';
$field['label']='Anz.Seite';
$field['rules']='int';
$field['options']='10=10&25=25&50=50&100=100';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='title';
$field['label']='Sortierung';
$field['rules']='parameter';
$field['options']='id=ID&title=Titel&permalink=Permalink&update_date=Geaendert';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='ASC';
$field['label']='Auf/Ab';
$field['rules']='parameter';
$field['options']='ASC=Aufsteigend&DESC=Absteigend';
$fields[]=$field;
