<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['bar_title'] = 'Contenido';
$messages['bar_subtitle'] = 'Páginas del idioma seleccionado actualmente.';
$messages['stats_title'] = 'Indicadores de contenido';
$messages['stats_pages'] = 'Páginas';
$messages['stats_active'] = 'Activo';
$messages['stats_inactive'] = 'Inactivo';
$messages['column_title'] = 'Título';
$messages['column_permalink'] = 'Enlace permanente';
$messages['column_folder'] = 'Carpeta';
$messages['column_active'] = 'Activo';
$messages['column_updated'] = 'Actualizado';
$messages['status_active'] = 'Activo';
$messages['status_inactive'] = 'Inactivo';
$messages['cms_label'] = 'Content CMS';
$messages['section_folders_title'] = 'Carpetas';
$messages['section_folders_subtitle'] = 'Carpetas de contenido del idioma seleccionado actualmente.';
$messages['section_media_title'] = 'Medios';
$messages['section_media_subtitle'] = 'Medios centrales de dbxMedia.';
$messages['section_templates_title'] = 'Plantillas de contenido';
$messages['section_templates_subtitle'] = 'Plantillas disponibles en dbxContent/tpl/htm.';
$messages['column_template'] = 'Plantilla';
$messages['column_read_rights'] = 'Permisos de lectura';
$messages['column_preview'] = 'Vista previa';
$messages['column_type'] = 'Tipo';
$messages['column_provider'] = 'Proveedor';
$messages['column_usage'] = 'Uso';
$messages['column_module'] = 'Módulo';
$messages['column_bytes'] = 'Bytes';
$messages['edit_template'] = 'Editar plantilla';
$messages['edit_in_cms'] = 'Editar en Content CMS';
$messages['edit_folder_in_cms'] = 'Editar carpeta de contenido en CMS';
$messages['confirm_folder_delete'] = '¿Eliminar esta carpeta de contenido?';
$messages['confirm_media_delete'] = '¿Eliminar este medio?';
$messages['confirm_template_delete'] = '¿Eliminar esta plantilla de contenido?';
$messages['media_not_found'] = 'No se encontró el medio.';
$messages['template_deleted'] = 'Plantilla eliminada: {name}.htm';
$messages['template_delete_error'] = 'No se pudo eliminar la plantilla.';
$messages['template_create_error'] = 'No se pudo crear la plantilla.';
$messages['template_name_validation'] = 'Revise el nombre de plantilla marcado en rojo.';
$messages['template_new_title'] = 'Nueva plantilla de contenido';
$messages['template_new_info'] = 'Introduzca un nombre único para la nueva plantilla de contenido c-* .';
$messages['template_name_label'] = 'Nombre de plantilla';
$messages['template_name_error'] = 'El nombre debe empezar por c- y solo puede contener letras, números, guiones y guiones bajos.';
$messages['section_undefined'] = 'La sección de contenido “{section}” no está definida.';
$messages['template_invalid_name'] = 'Nombre de plantilla no válido. Se permite c-name con letras, números, guiones y guiones bajos.';
$messages['template_path_error'] = 'No se pudo determinar la ruta de la plantilla.';
$messages['template_exists'] = 'La plantilla ya existe: {name}.htm';
$messages['template_created'] = 'Plantilla creada: {name}.htm';
$messages['template_new_button'] = 'Nueva plantilla';
$messages['template_new_action_title'] = 'Crear una nueva plantilla c-*';


$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['default']='25';
$field['label']='Número';
$field['rules']='int';
$field['options']='10=10&25=25&50=50&100=100';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='title';
$field['label']='Orden';
$field['rules']='parameter';
$field['options']='id=ID&title=Título&permalink=Permalink&update_date=Modificado';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='ASC';
$field['label']='Dirección';
$field['rules']='parameter';
$field['options']='ASC=Ascendente&DESC=Descendente';
$fields[]=$field;
