<?php
$messages = array();
$messages['bar_title'] = 'Content';
$messages['bar_subtitle'] = 'Pages in the currently selected language.';
$messages['stats_title'] = 'Content metrics';
$messages['stats_pages'] = 'Pages';
$messages['stats_active'] = 'Active';
$messages['stats_inactive'] = 'Inactive';
$messages['column_title'] = 'Title';
$messages['column_permalink'] = 'Permalink';
$messages['column_folder'] = 'Folder';
$messages['column_active'] = 'Active';
$messages['column_updated'] = 'Updated';
$messages['status_active'] = 'Active';
$messages['status_inactive'] = 'Inactive';
$messages['cms_label'] = 'Content CMS';
$messages['section_folders_title'] = 'Folders';
$messages['section_folders_subtitle'] = 'Content folders in the currently selected language.';
$messages['section_media_title'] = 'Media';
$messages['section_media_subtitle'] = 'Central media from dbxMedia.';
$messages['section_templates_title'] = 'Content templates';
$messages['section_templates_subtitle'] = 'Available templates from dbxContent/tpl/htm.';
$messages['column_template'] = 'Template';
$messages['column_read_rights'] = 'Read permissions';
$messages['column_preview'] = 'Preview';
$messages['column_type'] = 'Type';
$messages['column_provider'] = 'Provider';
$messages['column_usage'] = 'Usage';
$messages['column_module'] = 'Module';
$messages['column_bytes'] = 'Bytes';
$messages['edit_template'] = 'Edit template';
$messages['edit_in_cms'] = 'Edit in Content CMS';
$messages['edit_folder_in_cms'] = 'Edit content folder in CMS';
$messages['confirm_folder_delete'] = 'Delete this content folder?';
$messages['confirm_media_delete'] = 'Delete this medium?';
$messages['confirm_template_delete'] = 'Delete this content template?';
$messages['media_not_found'] = 'Medium not found.';
$messages['template_deleted'] = 'Template deleted: {name}.htm';
$messages['template_delete_error'] = 'The template could not be deleted.';
$messages['template_create_error'] = 'The template could not be created.';
$messages['template_name_validation'] = 'Please check the template name highlighted in red.';
$messages['template_new_title'] = 'New content template';
$messages['template_new_info'] = 'Enter a unique name for the new c-* content template.';
$messages['template_name_label'] = 'Template name';
$messages['template_name_error'] = 'The name must begin with c- and may contain only letters, numbers, hyphens and underscores.';
$messages['section_undefined'] = 'Content section “{section}” is not defined.';
$messages['template_invalid_name'] = 'Invalid template name. Allowed: c-name with letters, numbers, hyphens and underscores.';
$messages['template_path_error'] = 'The template path could not be determined.';
$messages['template_exists'] = 'Template already exists: {name}.htm';
$messages['template_created'] = 'Template created: {name}.htm';
$messages['template_new_button'] = 'New template';
$messages['template_new_action_title'] = 'Create a new c-* template';


$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['default']='25';
$field['label']='Number';
$field['rules']='int';
$field['options']='10=10&25=25&50=50&100=100';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='title';
$field['label']='Sorting';
$field['rules']='parameter';
$field['options']='id=ID&title=Title&permalink=Permalink&update_date=Modified';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='ASC';
$field['label']='Direction';
$field['rules']='parameter';
$field['options']='ASC=Ascending&DESC=Descending';
$fields[]=$field;
