<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['bar_title'] = 'Formulario de contacto';
$messages['bar_subtitle'] = 'Envíenos un mensaje';
$messages['request_success'] = 'Su solicitud de contacto se envió correctamente.';
$messages['validation_error'] = 'Revise los campos obligatorios resaltados.';
$messages['form_warning'] = 'Revise la información del formulario de contacto.';
$messages['try_limit'] = 'Demasiados intentos fallidos. Espere {sec} segundos y vuelva a intentarlo.';
$messages['spam_error'] = 'Su solicitud no se envió porque la entrada fue identificada como spam.';
$messages['spam_field_error'] = 'Posible spam. Revise su entrada.';
$messages['store_error'] = 'No se pudo guardar la solicitud de contacto.';
$messages['admin_mail_error'] = 'La solicitud se guardó, pero no se pudo enviar la notificación por correo electrónico.';
$messages['email_field_error'] = 'No se pudo enviar el correo electrónico.';
$messages['confirm_mail_error'] = 'La solicitud se guardó, pero no se pudo enviar el correo electrónico de confirmación.';
$messages['confirm_email_field_error'] = 'No se pudo enviar el correo electrónico de confirmación.';
$messages['confirm_title'] = 'Solicitud enviada';
$messages['confirm_subtitle'] = 'Resumen de su mensaje';
$messages['confirm_lead'] = '¡Gracias! Hemos recibido su solicitud de contacto.';
$messages['confirm_received'] = 'Hemos recibido su mensaje y lo tramitaremos.';
$messages['confirm_number'] = 'Número de solicitud: <strong>#{rid}</strong>.';
$messages['confirm_mail_sent'] = 'Se envió una confirmación a <strong>{email}</strong>.';
$messages['confirm_mail_failed'] = 'No se pudo enviar ahora el correo de confirmación. Su solicitud está guardada.';
$messages['confirm_mail_pending'] = 'En breve recibirá una confirmación en <strong>{email}</strong>.';
$messages['confirm_reply'] = 'Nos pondremos en contacto con usted lo antes posible.';


$field=array();
$field['name']='name';
$field['type']='varchar';
$field['index']='';
$field['length']='160';
$field['default']='';
$field['label']='Nombre';
$field['rules']='words|min=2|max=160';
$field['tooltip']='';
$field['errormsg']='Por favor, escriba un nombre.';
$field['placeholder']='Su nombre';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='email';
$field['type']='varchar';
$field['index']='';
$field['length']='180';
$field['default']='';
$field['label']='E-mail';
$field['rules']='email|min=6|max=180';
$field['tooltip']='';
$field['errormsg']='Por favor, introduzca una dirección de correo electrónico válida.';
$field['placeholder']='name@example.org';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='phone';
$field['type']='varchar';
$field['index']='';
$field['length']='80';
$field['default']='';
$field['label']='Teléfono';
$field['rules']='varchar|max=80';
$field['tooltip']='';
$field['errormsg']='';
$field['placeholder']='opcional';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='subject';
$field['type']='varchar';
$field['index']='';
$field['length']='220';
$field['default']='';
$field['label']='Asunto';
$field['rules']='varchar|min=3|max=220';
$field['tooltip']='';
$field['errormsg']='Introduzca un asunto.';
$field['placeholder']='Asunto';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='message';
$field['type']='mediumtext';
$field['index']='';
$field['length']='-1';
$field['default']='';
$field['label']='Mensaje';
$field['rules']='*|min=8|max=5000';
$field['tooltip']='';
$field['errormsg']='Por favor introduzca un mensaje con al menos 8 caracteres.';
$field['placeholder']='Su mensaje';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='rows=8';
$field['options']='';
$field['tpl']='textarea-label';
$fields[]=$field;
