<?php
$messages = array();
$messages['bar_title'] = 'Contact form';
$messages['bar_subtitle'] = 'Send us a message';
$messages['request_success'] = 'Your contact request was sent successfully.';
$messages['validation_error'] = 'Please check the highlighted required fields.';
$messages['form_warning'] = 'Please review the information about the contact form.';
$messages['try_limit'] = 'Too many unsuccessful attempts. Please wait {sec} seconds and then try again.';
$messages['spam_error'] = 'Your request was not sent because the entry was identified as spam.';
$messages['spam_field_error'] = 'Suspected spam. Please check your entry.';
$messages['store_error'] = 'The contact request could not be saved.';
$messages['admin_mail_error'] = 'The contact request was saved, but the email notification could not be sent.';
$messages['email_field_error'] = 'The email could not be sent.';
$messages['confirm_mail_error'] = 'The contact request was saved, but the confirmation email could not be sent.';
$messages['confirm_email_field_error'] = 'The confirmation email could not be sent.';
$messages['confirm_title'] = 'Request sent';
$messages['confirm_subtitle'] = 'Summary of your message';
$messages['confirm_lead'] = 'Thank you! We have received your contact request.';
$messages['confirm_received'] = 'Your message has been received and will be processed.';
$messages['confirm_number'] = 'Your request number: <strong>#{rid}</strong>.';
$messages['confirm_mail_sent'] = 'A confirmation was sent to <strong>{email}</strong>.';
$messages['confirm_mail_failed'] = 'The confirmation email could not be sent at the moment. Your request is still saved.';
$messages['confirm_mail_pending'] = 'A confirmation will shortly be sent to <strong>{email}</strong>.';
$messages['confirm_reply'] = 'We will get back to you as soon as possible.';


$field=array();
$field['name']='name';
$field['type']='varchar';
$field['index']='';
$field['length']='160';
$field['default']='';
$field['label']='Name';
$field['rules']='words|min=2|max=160';
$field['tooltip']='';
$field['errormsg']='Please enter a name.';
$field['placeholder']='Your name';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='email';
$field['type']='varchar';
$field['index']='';
$field['length']='180';
$field['default']='';
$field['label']='E-mail';
$field['rules']='email|min=6|max=180';
$field['tooltip']='';
$field['errormsg']='Please enter a valid email address.';
$field['placeholder']='name@example.org';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='phone';
$field['type']='varchar';
$field['index']='';
$field['length']='80';
$field['default']='';
$field['label']='Telephone';
$field['rules']='varchar|max=80';
$field['tooltip']='';
$field['errormsg']='';
$field['placeholder']='optional';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='subject';
$field['type']='varchar';
$field['index']='';
$field['length']='220';
$field['default']='';
$field['label']='Subject';
$field['rules']='varchar|min=3|max=220';
$field['tooltip']='';
$field['errormsg']='Please enter a subject.';
$field['placeholder']='Subject';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='message';
$field['type']='mediumtext';
$field['index']='';
$field['length']='-1';
$field['default']='';
$field['label']='Message';
$field['rules']='*|min=8|max=5000';
$field['tooltip']='';
$field['errormsg']='Please enter a message with at least 8 characters.';
$field['placeholder']='Your message';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='rows=8';
$field['options']='';
$field['tpl']='textarea-label';
$fields[]=$field;
