<?php
$messages = array();
$messages['bar_title'] = 'Kontaktformular';
$messages['bar_subtitle'] = 'Nachricht an uns senden';
$messages['request_success'] = 'Ihre Kontaktanfrage wurde erfolgreich übermittelt.';
$messages['validation_error'] = 'Bitte prüfen Sie die rot markierten Pflichtfelder.';
$messages['form_warning'] = 'Bitte prüfen Sie die Hinweise zum Kontaktformular.';
$messages['try_limit'] = 'Zu viele fehlerhafte Versuche. Bitte warten Sie {sec} Sekunden und versuchen Sie es dann erneut.';
$messages['spam_error'] = 'Ihre Anfrage wurde nicht versendet, weil die Eingabe als Spam erkannt wurde.';
$messages['spam_field_error'] = 'Spam-Verdacht. Bitte prüfen Sie Ihre Eingabe.';
$messages['store_error'] = 'Die Kontaktanfrage konnte nicht gespeichert werden.';
$messages['admin_mail_error'] = 'Die Kontaktanfrage wurde gespeichert, aber die E-Mail-Benachrichtigung konnte nicht versendet werden.';
$messages['email_field_error'] = 'Die E-Mail konnte nicht versendet werden.';
$messages['confirm_mail_error'] = 'Die Kontaktanfrage wurde gespeichert, aber die Bestätigungs-E-Mail konnte nicht versendet werden.';
$messages['confirm_email_field_error'] = 'Die Bestätigungs-E-Mail konnte nicht versendet werden.';
$messages['confirm_title'] = 'Anfrage gesendet';
$messages['confirm_subtitle'] = 'Zusammenfassung Ihrer Nachricht';
$messages['confirm_lead'] = 'Vielen Dank! Ihre Kontaktanfrage wurde übernommen.';
$messages['confirm_received'] = 'Ihre Nachricht ist bei uns eingegangen und wird bearbeitet.';
$messages['confirm_number'] = 'Ihre Anfragenummer: <strong>#{rid}</strong>.';
$messages['confirm_mail_sent'] = 'Eine Bestätigung wurde an <strong>{email}</strong> gesendet.';
$messages['confirm_mail_failed'] = 'Die Bestätigungs-E-Mail konnte gerade nicht versendet werden. Ihre Anfrage ist dennoch gespeichert.';
$messages['confirm_mail_pending'] = 'Sie erhalten in Kürze eine Bestätigung an <strong>{email}</strong>.';
$messages['confirm_reply'] = 'Wir melden uns so bald wie möglich bei Ihnen.';


$field=array();
$field['name']='name';
$field['type']='varchar';
$field['index']='';
$field['length']='160';
$field['default']='';
$field['label']='Name';
$field['rules']='words|min=2|max=160';
$field['tooltip']='';
$field['errormsg']='Bitte einen Namen eintragen.';
$field['placeholder']='Ihr Name';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='email';
$field['type']='varchar';
$field['index']='';
$field['length']='180';
$field['default']='';
$field['label']='E-Mail';
$field['rules']='email|min=6|max=180';
$field['tooltip']='';
$field['errormsg']='Bitte eine gueltige E-Mail-Adresse eintragen.';
$field['placeholder']='name@example.org';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='phone';
$field['type']='varchar';
$field['index']='';
$field['length']='80';
$field['default']='';
$field['label']='Telefon';
$field['rules']='varchar|max=80';
$field['tooltip']='';
$field['errormsg']='';
$field['placeholder']='optional';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='subject';
$field['type']='varchar';
$field['index']='';
$field['length']='220';
$field['default']='';
$field['label']='Betreff';
$field['rules']='varchar|min=3|max=220';
$field['tooltip']='';
$field['errormsg']='Bitte einen Betreff eintragen.';
$field['placeholder']='Betreff';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$field['tpl']='text-label';
$fields[]=$field;

$field=array();
$field['name']='message';
$field['type']='mediumtext';
$field['index']='';
$field['length']='-1';
$field['default']='';
$field['label']='Nachricht';
$field['rules']='*|min=8|max=5000';
$field['tooltip']='';
$field['errormsg']='Bitte eine Nachricht mit mindestens 8 Zeichen eintragen.';
$field['placeholder']='Ihre Nachricht';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='rows=8';
$field['options']='';
$field['tpl']='textarea-label';
$fields[]=$field;
