<?php

$table['server']='dbxContact|dbxContact.db3';
$table['table']='contact_message';
$table['datadic']='contactMessage';
$table['primary']='id';
$table['language']='0';
$table['version']='1.0';
$table['autosync']='1';
$table['cache']='0';
$table['trash']='1';
$table['trace']='0';
$table['update_sql']='';
$table['default_sort']='create_date ASC';
$table['form-dd-table']='';
$table['read']='admin';
$table['create']='admin';
$table['update']='admin';
$table['delete']='admin';
$table['read_owner']='admin';
$table['create_owner']='admin';
$table['update_owner']='admin';
$table['delete_owner']='admin';

$field=array();
$field['name']='id';
$field['type']='int';
$field['index']='PRI';
$field['length']='11';
$field['default']='';
$field['label']='ID';
$field['rules']='int';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='create_date';
$field['type']='datetime';
$field['index']='MUL';
$field['length']='-1';
$field['default']='';
$field['label']='Datum';
$field['rules']='datetime';
$field['convert']='date_time';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='create_uid';
$field['type']='int';
$field['index']='MUL';
$field['length']='11';
$field['default']='0';
$field['label']='Erstellt von';
$field['rules']='int';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='update_date';
$field['type']='datetime';
$field['index']='';
$field['length']='-1';
$field['default']='';
$field['label']='Aktualisiert';
$field['rules']='datetime';
$field['convert']='date_time';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='update_uid';
$field['type']='int';
$field['index']='MUL';
$field['length']='11';
$field['default']='0';
$field['label']='Aktualisiert von';
$field['rules']='int';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='owner';
$field['type']='int';
$field['index']='MUL';
$field['length']='11';
$field['default']='0';
$field['label']='Owner';
$field['rules']='int';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='trash';
$field['type']='int';
$field['index']='MUL';
$field['length']='1';
$field['default']='0';
$field['label']='Trash';
$field['rules']='int';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='ticket_id';
$field['type']='int';
$field['index']='MUL';
$field['length']='11';
$field['default']='0';
$field['label']='Ticket';
$field['rules']='int';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='author_uid';
$field['type']='int';
$field['index']='MUL';
$field['length']='11';
$field['default']='0';
$field['label']='Autor';
$field['rules']='int';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='author_type';
$field['type']='varchar';
$field['index']='MUL';
$field['length']='24';
$field['default']='system';
$field['label']='Absender';
$field['rules']='parameter|max=24';
$field['options']='requester=Anfragender&admin=Support&system=System';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='message_type';
$field['type']='varchar';
$field['index']='MUL';
$field['length']='24';
$field['default']='message';
$field['label']='Typ';
$field['rules']='parameter|max=24';
$field['options']='request=Anfrage&message=Nachricht&reply=Antwort&note=Interne Notiz&status=Status';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='visibility';
$field['type']='varchar';
$field['index']='MUL';
$field['length']='16';
$field['default']='public';
$field['label']='Sichtbarkeit';
$field['rules']='parameter|max=16';
$field['options']='public=Oeffentlich&internal=Intern';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='body';
$field['type']='mediumtext';
$field['index']='';
$field['length']='-1';
$field['default']='';
$field['label']='Nachricht';
$field['rules']='*|max=10000';
$field['data']='rows=9';
$field['tpl']='textarea-label';
$fields[]=$field;

$field=array();
$field['name']='status_from';
$field['type']='varchar';
$field['index']='';
$field['length']='24';
$field['default']='';
$field['label']='Status vorher';
$field['rules']='parameter|max=24';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='status_to';
$field['type']='varchar';
$field['index']='MUL';
$field['length']='24';
$field['default']='';
$field['label']='Status nachher';
$field['rules']='parameter|max=24';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='mail_sent';
$field['type']='int';
$field['index']='MUL';
$field['length']='1';
$field['default']='0';
$field['label']='E-Mail versendet';
$field['rules']='int';
$field['tpl']='hidden';
$fields[]=$field;

$field=array();
$field['name']='mail_sent_date';
$field['type']='datetime';
$field['index']='';
$field['length']='-1';
$field['default']='';
$field['label']='E-Mail versendet am';
$field['rules']='datetime';
$field['convert']='date_time';
$field['tpl']='hidden';
$fields[]=$field;
