blank_issues_enabled: false
contact_links:
  - name: Sicherheitslücke vertraulich melden
    url: https://github.com/ecb-dbxApp/dbxapp/security/advisories/new
    about: Bitte keine ungepatchten Sicherheitslücken öffentlich melden.
