<?php
$table['table']='abtest';
$table['autosync']='0';
$table['server']='dbxModules';
$table['version']='1';
$table['cache']='0';
$table['trash']='0';
$table['trace']='0';
$table['read']='admin';
$table['create']='admin';
$table['update']='admin';
$table['delete']='admin';
$table['read_owner']='admin';
$table['create_owner']='admin';
$table['update_owner']='admin';
$table['delete_owner']='admin';
$table['datadic']='abtest';

?>
