<?php
$messages = array();
$messages['save_success'] = 'Data was saved';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Data could not be saved';
$messages['form_new_title'] = 'New product';
$messages['form_edit_title'] = 'Edit product';
$messages['form_new_subtitle'] = 'Create master data';
$messages['form_info'] = 'Edit the product master data. Groups, attributes and images are maintained with the corresponding shop administration functions.';
$messages['field_product_group'] = 'Product group';
$messages['product_save_success'] = 'The product was saved.';
$messages['product_save_error'] = 'The product could not be saved. Please check the SKU and URL name in particular.';
$messages['validation_error'] = 'Please check your entries.';
$messages['help_edit'] = 'Help: edit product';
$messages['save_title'] = 'Save product';
$messages['save_label'] = 'Save';
$messages['view_product'] = 'View product';
$messages['preview'] = 'Preview';
$messages['product_attributes'] = 'Product attributes';
$messages['attributes'] = 'Attributes';
$messages['delete_title'] = 'Delete product';
$messages['delete_confirm'] = 'Do you really want to delete this product?';
$messages['delete_label'] = 'Delete';
$messages['product_list_title'] = 'Back to the product list';
$messages['product_list'] = 'Product list';
$messages['images_title'] = 'Product images';
$messages['save_first_images'] = 'Save the product first; images can then be assigned.';
$messages['select_images_title'] = 'Add images from the media browser to the product';
$messages['selection'] = 'Select';
$messages['new_primary'] = 'Use the new image as the primary image';
$messages['no_images'] = 'No images have been assigned yet.';
$messages['image_source_product'] = 'Product image';
$messages['image_source_group'] = 'Group image';
$messages['primary'] = 'Primary';
$messages['unlink_image_title'] = 'Remove image assignment';
$messages['unlink_image_question'] = 'Do you really want to remove this image assignment?';
$messages['unlink_image_hint'] = 'The file remains in the media browser. Only the shop assignment is removed. Group images affect the group and therefore other products in that group.';
$messages['unlink_image_label'] = 'Remove assignment';
$messages['media_hint'] = 'Uploads, selection, cropping, resizing, batch processing and maintenance use the existing media browser.';
$messages['channels_title'] = 'Channels';
$messages['save_first_channels'] = 'Save the product first; channels can then be set individually.';
$messages['channels_info'] = 'Direct product selection. This setting takes precedence over channel groups.';
$messages['no_channels'] = 'No channels have been created yet.';
$messages['table_channel'] = 'Channel';
$messages['table_status'] = 'Status';
$messages['table_export'] = 'Export';
$messages['table_action'] = 'Action';
$messages['channel_direct_active'] = 'directly active';
$messages['channel_direct_inactive'] = 'directly inactive';
$messages['channel_from_group_title'] = 'from group: {groups}';
$messages['channel_from_group'] = 'from group';
$messages['channel_not_set'] = 'not set';
$messages['channel_not_exported'] = 'not exported';
$messages['mapping_title'] = 'Channel mapping: {channel}';
$messages['mapping_label'] = 'Mapping';
$messages['export_title'] = 'Export to channel';
$messages['export_question'] = 'Export the product to {channel} now?';
$messages['export_hint'] = 'The connector only sends when the required provider credentials and mandatory fields are available. Status and response are stored with the product.';
$messages['export_button_title'] = 'Export to this channel';

$addField = function($name, $type, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']='';
   $field['length']=$extra['length'] ?? '';
   $field['default']=$extra['default'] ?? '';
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']='';
   $field['protect']='0';
   $field['mask']='';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$addField('sku','varchar','Product number','parameter|min=2|max=80','text-label');
$addField('slug','varchar','URL name','parameter|min=2|max=120','text-label');
$addField('title','varchar','Title','*|min=2|max=180','text-label');
$addField('category','varchar','Category','parameter|max=80','select-single-label',array('options'=>'Software=Software&Dienstleistung=Services&Merchandise=Merchandise'));
$addField('product_group_id','int','Product group','int','select-single-label');
$addField('product_type','varchar','Product type','parameter|max=24','select-single-label',array('options'=>'digital=Digital&service=Services&physical=Physical'));
$addField('summary','varchar','Short description','*|max=255','textarea-label',array('data'=>'rows=2'));
$addField('description','mediumtext','Description','*|max=5000','textarea-label',array('data'=>'rows=6'));
$addField('price_gross','decimal','Gross price','decimal','text-label');
$addField('tax_mode','varchar','VAT Source','parameter|max=24','select-single-label',array('options'=>'group=From group&individual=Individual'));
$addField('tax_rate','decimal','VAT % individual','decimal','text-label');
$addField('shipping_mode','varchar','Dispatch source','parameter|max=24','select-single-label',array('options'=>'group=From group&individual=Individual'));
$addField('shipping_gross','decimal','Shipment gross individually','decimal','text-label');
$addField('stock','int','Stock','int','text-label');
$addField('active','int','Active','int','checkbox-label',array('default'=>'1'));
$addField('sorter','int','Sorting','int','text-label');
$addField('badge','varchar','Badge','*|max=80','text-label');
$addField('image_icon','varchar','icon','parameter|max=80','text-label');
$addField('logo_variant','varchar','Logo variant','parameter|max=80','text-label');
?>
