<?php
$messages = array();
$messages['form_new_title'] = 'Neuer Artikel';
$messages['form_edit_title'] = 'Artikel bearbeiten';
$messages['form_new_subtitle'] = 'Stammdaten anlegen';
$messages['form_info'] = 'Artikel-Stammdaten bearbeiten. Gruppen, Attribute und Bilder werden über die jeweiligen Shop-Admin-Funktionen gepflegt.';
$messages['field_product_group'] = 'Artikelgruppe';
$messages['product_save_success'] = 'Artikel wurde gespeichert.';
$messages['product_save_error'] = 'Artikel konnte nicht gespeichert werden. Bitte prüfen Sie insbesondere SKU und URL-Name.';
$messages['validation_error'] = 'Bitte prüfen Sie die Eingaben.';
$messages['help_edit'] = 'Hilfe: Artikel bearbeiten';
$messages['save_title'] = 'Artikel speichern';
$messages['save_label'] = 'Speichern';
$messages['view_product'] = 'Artikel ansehen';
$messages['preview'] = 'Vorschau';
$messages['product_attributes'] = 'Artikelattribute';
$messages['attributes'] = 'Attribute';
$messages['delete_title'] = 'Artikel löschen';
$messages['delete_confirm'] = 'Diesen Artikel wirklich löschen?';
$messages['delete_label'] = 'Löschen';
$messages['product_list_title'] = 'Zur Produktliste';
$messages['product_list'] = 'Produktliste';
$messages['images_title'] = 'Artikelbilder';
$messages['save_first_images'] = 'Speichern Sie den Artikel zuerst; danach können Bilder zugeordnet werden.';
$messages['select_images_title'] = 'Bilder aus dem Medienbrowser zum Artikel hinzufügen';
$messages['selection'] = 'Auswahl';
$messages['new_primary'] = 'Neues Bild als Primärbild';
$messages['no_images'] = 'Noch keine Bilder zugeordnet.';
$messages['image_source_product'] = 'Artikelbild';
$messages['image_source_group'] = 'Gruppenbild';
$messages['primary'] = 'Primär';
$messages['unlink_image_title'] = 'Bild-Zuordnung aufheben';
$messages['unlink_image_question'] = 'Diese Bild-Zuordnung wirklich aufheben?';
$messages['unlink_image_hint'] = 'Die Datei im Medienbrowser bleibt erhalten. Entfernt wird nur die Shop-Zuordnung. Bei Gruppenbildern betrifft das die Gruppe und damit auch andere Artikel dieser Gruppe.';
$messages['unlink_image_label'] = 'Zuordnung aufheben';
$messages['media_hint'] = 'Upload, Auswahl, Zuschneiden, Größenänderung, Stapelverarbeitung und Wartung laufen über den vorhandenen Medienbrowser.';
$messages['channels_title'] = 'Channels';
$messages['save_first_channels'] = 'Speichern Sie den Artikel zuerst; danach können Channels individuell gesetzt werden.';
$messages['channels_info'] = 'Direkte Artikel-Auswahl. Diese Einstellung hat Vorrang vor Channel-Gruppen.';
$messages['no_channels'] = 'Noch keine Channels angelegt.';
$messages['table_channel'] = 'Channel';
$messages['table_status'] = 'Status';
$messages['table_export'] = 'Export';
$messages['table_action'] = 'Aktion';
$messages['channel_direct_active'] = 'direkt aktiv';
$messages['channel_direct_inactive'] = 'direkt deaktiviert';
$messages['channel_from_group_title'] = 'aus Gruppe: {groups}';
$messages['channel_from_group'] = 'aus Gruppe';
$messages['channel_not_set'] = 'nicht gesetzt';
$messages['channel_not_exported'] = 'nicht exportiert';
$messages['mapping_title'] = 'Channel-Mapping: {channel}';
$messages['mapping_label'] = 'Mapping';
$messages['export_title'] = 'Channel exportieren';
$messages['export_question'] = 'Artikel jetzt zu {channel} exportieren?';
$messages['export_hint'] = 'Der Connector sendet nur, wenn die für den Anbieter notwendigen Zugangsdaten und Pflichtfelder vorhanden sind. Status und Antwort werden am Artikel gespeichert.';
$messages['export_button_title'] = 'Zu diesem Channel exportieren';

$add_field = function($name, $type, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']='';
   $field['length']=$extra['length'] ?? '';
   $field['default']=$extra['default'] ?? '';
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']='';
   $field['protect']='0';
   $field['mask']='';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$add_field('sku','varchar','Artikelnummer','parameter|min=2|max=80','text-label');
$add_field('slug','varchar','URL-Name','parameter|min=2|max=120','text-label');
$add_field('title','varchar','Titel','*|min=2|max=180','text-label');
$add_field('category','varchar','Kategorie','parameter|max=80','select-single-label',array('options'=>'Software=Software&Dienstleistung=Dienstleistung&Merchandise=Merchandise'));
$add_field('product_group_id','int','Artikelgruppe','int','select-single-label');
$add_field('product_type','varchar','Produkttyp','parameter|max=24','select-single-label',array('options'=>'digital=Digital&service=Dienstleistung&physical=Physisch'));
$add_field('summary','varchar','Kurzbeschreibung','*|max=255','textarea-label',array('data'=>'rows=2'));
$add_field('description','mediumtext','Beschreibung','*|max=5000','textarea-label',array('data'=>'rows=6'));
$add_field('price_gross','decimal','Bruttopreis','decimal','text-label');
$add_field('tax_mode','varchar','MwSt.-Quelle','parameter|max=24','select-single-label',array('options'=>'group=Aus Gruppe&individual=Individuell'));
$add_field('tax_rate','decimal','MwSt. % individuell','decimal','text-label');
$add_field('shipping_mode','varchar','Versand-Quelle','parameter|max=24','select-single-label',array('options'=>'group=Aus Gruppe&individual=Individuell'));
$add_field('shipping_gross','decimal','Versand brutto individuell','decimal','text-label');
$add_field('stock','int','Lagerbestand','int','text-label');
$add_field('active','int','Aktiv','int','checkbox-label',array('default'=>'1'));
$add_field('sorter','int','Sortierung','int','text-label');
$add_field('badge','varchar','Badge','*|max=80','text-label');
$add_field('image_icon','varchar','Icon','parameter|max=80','text-label');
$add_field('logo_variant','varchar','Logo-Variante','parameter|max=80','text-label');
?>
