<?php
$messages = array();
$messages['save_success'] = 'Daten wurden gespeichert';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Daten konnten nicht gespeichert werden';

require dirname(__DIR__) . '/dd/shopProductChannel.dd.php';

$messages['mapping_title'] = 'Channel-Mapping';
$messages['mapping_missing'] = 'Artikel oder Channel fehlt.';
$messages['mapping_not_found'] = 'Artikel oder Channel wurde nicht gefunden.';
$messages['mapping_saved'] = 'Channel-Mapping gespeichert.';
$messages['mapping_help'] = 'Hilfe: Channel-Mapping je Artikel';
$messages['mapping_save'] = 'Speichern';
$messages['mapping_export_title'] = 'Channel exportieren';
$messages['mapping_export_confirm'] = 'Artikel jetzt exportieren?';
$messages['mapping_export_label'] = 'Exportieren';
$messages['mapping_intro'] = 'Hier werden die produktbezogenen Werte für diesen Channel gepflegt. Globale API-Zugangsdaten bleiben in der Channel-Verwaltung.';
$messages['mapping_values_title'] = 'Channel-Werte';
$messages['mapping_export_status_title'] = 'Exportstatus';
$messages['mapping_not_exported'] = 'nicht exportiert';
$messages['mapping_current_selection'] = 'Aktuelle Auswahl: {value}';
$messages['mapping_group_default'] = 'Artikelgruppen-Vorgabe: {value}';
$messages['mapping_channel_default'] = 'Channel-Vorgabe: {value}';
$messages['mapping_ebay_category'] = 'eBay-Kategorie';
$messages['mapping_ebay_category_hint'] = 'Die Liste ist eine Vorgabe. Für weitere IDs können Shop-Einstellungen oder später die eBay-Taxonomy-Anbindung genutzt werden.';
$messages['mapping_category_software'] = 'Software / digitale Produkte';
$messages['mapping_category_clothing'] = 'Kleidung & Accessoires';
$messages['mapping_category_electronics'] = 'Elektronik';
$messages['mapping_category_home'] = 'Haus & Garten';
$messages['mapping_category_business'] = 'Business & Industrie';
$messages['mapping_location_key'] = 'Location-Key';
$messages['mapping_location_placeholder'] = 'in Channel-Konfiguration setzen';
$messages['mapping_location_hint'] = 'Kommt aus der eBay-Channel-Konfiguration.';
$messages['mapping_condition'] = 'Zustand';
$messages['mapping_condition_new'] = 'Neu';
$messages['mapping_condition_used_excellent'] = 'Gebraucht – sehr gut';
$messages['mapping_condition_used_good'] = 'Gebraucht – gut';
$messages['mapping_ebay_aspects'] = 'eBay-Aspekte';
$messages['mapping_requirements'] = 'Anforderungen';
$messages['mapping_requirements_listing'] = 'Listing';
$messages['mapping_requirements_product'] = 'Produktdaten';
$messages['mapping_requirements_offer'] = 'Angebot';
$messages['mapping_brand'] = 'Marke';
$messages['mapping_amazon_attributes'] = 'Amazon-Attribute';
$messages['mapping_amazon_hint'] = 'Amazon verlangt je Produkttyp unterschiedliche Pflichtattribute. Diese Maske speichert einfache key=value-Werte; der Connector wandelt sie in SP-API-Attribute um.';
$messages['mapping_vehicle_model'] = 'Modell';
$messages['mapping_vehicle_registration'] = 'Erstzulassung';
$messages['mapping_vehicle_mileage'] = 'Kilometer';
$messages['mapping_vehicle_fuel'] = 'Kraftstoff';
$messages['mapping_vehicle_power'] = 'Leistung kW';
$messages['mapping_vehicle_category'] = 'Fahrzeugart';
$messages['mapping_vehicle_extra'] = 'Weitere mobile.de-Fahrzeugfelder';
$messages['mapping_mobile_hint'] = 'mobile.de ist nur für Fahrzeuganzeigen vorgesehen. Normale Shop-Artikel werden vom Connector bewusst blockiert.';
$messages['mapping_classified_category'] = 'Kategorie/Partner-Kategorie';
$messages['mapping_place'] = 'Ort/Standort';
$messages['mapping_contact_name'] = 'Kontaktname';
$messages['mapping_phone'] = 'Telefon';
$messages['mapping_classified_attributes'] = 'Kleinanzeigen-/Middleware-Attribute';
$messages['mapping_classified_hint'] = 'Ohne freigegebene Partner- oder Middleware-API erfolgt kein automatischer Upload zu kleinanzeigen.de. Die Daten sind dann für die manuelle Übergabe vorbereitet.';
$messages['mapping_endpoint'] = 'Aktion/Endpoint';
$messages['mapping_middleware_attributes'] = 'Middleware-Attribute';
?>
