<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['form_new_title'] = 'Nuevo producto';
$messages['form_edit_title'] = 'Editar producto';
$messages['form_new_subtitle'] = 'Crear datos maestros';
$messages['form_info'] = 'Edite los datos maestros del producto. Los grupos, atributos e imágenes se mantienen con las correspondientes funciones de administración de la tienda.';
$messages['field_product_group'] = 'Grupo de productos';
$messages['product_save_success'] = 'El producto se guardó.';
$messages['product_save_error'] = 'No se pudo guardar el producto. Revise especialmente el SKU y el nombre de la URL.';
$messages['validation_error'] = 'Revise los datos introducidos.';
$messages['help_edit'] = 'Ayuda: editar producto';
$messages['save_title'] = 'Guardar producto';
$messages['save_label'] = 'Guardar';
$messages['view_product'] = 'Ver producto';
$messages['preview'] = 'Vista previa';
$messages['product_attributes'] = 'Atributos del producto';
$messages['attributes'] = 'Atributos';
$messages['delete_title'] = 'Eliminar producto';
$messages['delete_confirm'] = '¿Desea realmente eliminar este producto?';
$messages['delete_label'] = 'Eliminar';
$messages['product_list_title'] = 'Volver a la lista de productos';
$messages['product_list'] = 'Lista de productos';
$messages['images_title'] = 'Imágenes del producto';
$messages['save_first_images'] = 'Guarde primero el producto; después podrá asignar imágenes.';
$messages['select_images_title'] = 'Añadir imágenes del navegador de medios al producto';
$messages['selection'] = 'Seleccionar';
$messages['new_primary'] = 'Usar la nueva imagen como imagen principal';
$messages['no_images'] = 'Todavía no se han asignado imágenes.';
$messages['image_source_product'] = 'Imagen del producto';
$messages['image_source_group'] = 'Imagen del grupo';
$messages['primary'] = 'Principal';
$messages['unlink_image_title'] = 'Eliminar asignación de imagen';
$messages['unlink_image_question'] = '¿Desea realmente eliminar esta asignación de imagen?';
$messages['unlink_image_hint'] = 'El archivo permanece en el navegador de medios. Solo se elimina la asignación de la tienda. Las imágenes de grupo afectan al grupo y, por tanto, a otros productos del mismo.';
$messages['unlink_image_label'] = 'Eliminar asignación';
$messages['media_hint'] = 'La carga, selección, recorte, cambio de tamaño, procesamiento por lotes y mantenimiento usan el navegador de medios existente.';
$messages['channels_title'] = 'Canales';
$messages['save_first_channels'] = 'Guarde primero el producto; después podrá configurar los canales individualmente.';
$messages['channels_info'] = 'Selección directa del producto. Esta configuración tiene prioridad sobre los grupos de canales.';
$messages['no_channels'] = 'Todavía no se han creado canales.';
$messages['table_channel'] = 'Canal';
$messages['table_status'] = 'Estado';
$messages['table_export'] = 'Exportación';
$messages['table_action'] = 'Acción';
$messages['channel_direct_active'] = 'activo directamente';
$messages['channel_direct_inactive'] = 'inactivo directamente';
$messages['channel_from_group_title'] = 'del grupo: {groups}';
$messages['channel_from_group'] = 'del grupo';
$messages['channel_not_set'] = 'sin configurar';
$messages['channel_not_exported'] = 'no exportado';
$messages['mapping_title'] = 'Asignación del canal: {channel}';
$messages['mapping_label'] = 'Asignación';
$messages['export_title'] = 'Exportar al canal';
$messages['export_question'] = '¿Exportar ahora el producto a {channel}?';
$messages['export_hint'] = 'El conector solo envía cuando están disponibles las credenciales y los campos obligatorios del proveedor. El estado y la respuesta se guardan con el producto.';
$messages['export_button_title'] = 'Exportar a este canal';

$addField = function($name, $type, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']='';
   $field['length']=$extra['length'] ?? '';
   $field['default']=$extra['default'] ?? '';
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']='';
   $field['protect']='0';
   $field['mask']='';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$addField('sku','varchar','Número de artículo','parameter|min=2|max=80','text-label');
$addField('slug','varchar','Nombre de URL','parameter|min=2|max=120','text-label');
$addField('title','varchar','Título','*|min=2|max=180','text-label');
$addField('category','varchar','Categoría','parameter|max=80','select-single-label',array('options'=>'Software=Software&Dienstleistung=Servicios&Merchandise=Merchandise'));
$addField('product_group_id','int','Grupo de artículos','int','select-single-label');
$addField('product_type','varchar','Tipo de producto','parameter|max=24','select-single-label',array('options'=>'digital=Digital&service=Servicios&physical=Física'));
$addField('summary','varchar','Descripción breve','*|max=255','textarea-label',array('data'=>'rows=2'));
$addField('description','mediumtext','Descripción','*|max=5000','textarea-label',array('data'=>'rows=6'));
$addField('price_gross','decimal','Precio bruto','decimal','text-label');
$addField('tax_mode','varchar','IVA','parameter|max=24','select-single-label',array('options'=>'group=Del grupo&individual=Individual'));
$addField('tax_rate','decimal','IVA % individual','decimal','text-label');
$addField('shipping_mode','varchar','Fuente de distribución','parameter|max=24','select-single-label',array('options'=>'group=Del grupo&individual=Individual'));
$addField('shipping_gross','decimal','Envíos brutos individualmente','decimal','text-label');
$addField('stock','int','Existencias','int','text-label');
$addField('active','int','Activo','int','checkbox-label',array('default'=>'1'));
$addField('sorter','int','Orden','int','text-label');
$addField('badge','varchar','Badge','*|max=80','text-label');
$addField('image_icon','varchar','icono','parameter|max=80','text-label');
$addField('logo_variant','varchar','Variante de logotipo','parameter|max=80','text-label');
?>
