<?php
$messages = array();
$messages['save_success'] = 'Daten wurden gespeichert';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Daten konnten nicht gespeichert werden';
$messages['frame_title'] = 'Kontaktanfragen und Tickets';
$messages['frame_subtitle'] = 'Anfragen, Antworten, Status und vollständiger Verlauf';
$messages['install'] = 'Installation';
$messages['refresh'] = 'Aktualisieren';
$messages['confirm_delete'] = 'Kontaktanfrage löschen?';
$messages['delete_tooltip'] = 'Anfrage löschen';
$messages['delete_title'] = '<i class=\'bi bi-trash\'></i> Kontaktanfrage löschen';
$messages['report_title'] = 'Kontaktanfragen';
$messages['delete_question'] = 'Kontaktanfrage #{id} wirklich löschen?';
$messages['delete_hint_thread'] = '<small>Zu dieser Anfrage gehört ein Verlauf mit {count} Nachricht(en). Der gesamte Verlauf wird gelöscht.</small>';
$messages['delete_hint_empty'] = '<small>Zu dieser Anfrage ist kein separater Verlauf vorhanden. Die Anfrage wird endgültig gelöscht.</small>';
$messages['delete_success'] = 'Kontaktanfrage #{id} und der zugehörige Verlauf wurden gelöscht.';
$messages['delete_error'] = 'Kontaktanfrage #{id} konnte nicht gelöscht werden.';
$messages['column_ticket'] = 'Ticket';
$messages['column_activity'] = 'Letzte Aktivität';
$messages['column_status'] = 'Status';
$messages['column_priority'] = 'Priorität';
$messages['column_user'] = 'Benutzer';
$messages['column_name'] = 'Name';
$messages['column_email'] = 'E-Mail';
$messages['column_subject'] = 'Betreff';
$messages['column_action'] = 'Aktion';
$messages['status_open'] = 'Offen';
$messages['status_in_progress'] = 'In Bearbeitung';
$messages['status_waiting_customer'] = 'Rückfrage';
$messages['status_answered'] = 'Beantwortet';
$messages['status_closed'] = 'Geschlossen';
$messages['priority_low'] = 'Niedrig';
$messages['priority_normal'] = 'Normal';
$messages['priority_high'] = 'Hoch';
$messages['priority_urgent'] = 'Dringend';
$messages['guest'] = 'Gast';
$messages['user_hidden'] = 'Vom Benutzer ausgeblendet';
$messages['user_visible'] = 'Im Benutzerkonto sichtbar';
$messages['ticket_not_found'] = 'Ticket nicht gefunden.';
$messages['timeline_internal_note'] = 'Interne Notiz';
$messages['timeline_support'] = 'Support';
$messages['timeline_requester'] = 'Anfragender';
$messages['timeline_system'] = 'System';
$messages['timeline_internal_only'] = 'Nur intern';
$messages['timeline_status'] = 'Status: {status}';
$messages['timeline_mail_sent'] = 'E-Mail versendet';
$messages['timeline_empty'] = 'Noch keine Meldungen vorhanden.';
$messages['stat_open'] = 'Offen';
$messages['stat_progress'] = 'In Bearbeitung';
$messages['stat_waiting'] = 'Rückfragen';
$messages['stat_answered'] = 'Beantwortet';
$messages['stat_closed'] = 'Geschlossen';


$field=array();
$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['default']='30';
$field['label']='Pro Seite';
$field['rules']='int';
$field['options']='10=10&20=20&30=30&50=50&100=100';
$fields[]=$field;

$field=array();
$field['name']='dbx_rstatus';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='all';
$field['label']='Status';
$field['rules']='parameter';
$field['options']='all=Alle&open=Offen&in_progress=In Bearbeitung&waiting_customer=Rueckfrage&answered=Beantwortet&closed=Geschlossen';
$fields[]=$field;

$field=array();
$field['name']='dbx_rpriority';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='all';
$field['label']='Prioritaet';
$field['rules']='parameter';
$field['options']='all=Alle&low=Niedrig&normal=Normal&high=Hoch&urgent=Dringend';
$fields[]=$field;

$field=array();
$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='last_activity_date';
$field['label']='Sortierung';
$field['rules']='parameter';
$field['options']='last_activity_date=Letzte Aktivitaet&create_date=Erstellt&id=ID&status=Status&priority=Prioritaet&subject=Betreff';
$fields[]=$field;

$field=array();
$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='DESC';
$field['label']='Richtung';
$field['rules']='parameter';
$field['options']='DESC=Absteigend&ASC=Aufsteigend';
$fields[]=$field;

$field=array();
$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['default']='';
$field['label']='Suchen';
$field['rules']='sqlsearch|max=100';
$fields[]=$field;
