<?php
$messages = array();
$messages['frame_title'] = 'Solicitudes de contacto y tickets';
$messages['frame_subtitle'] = 'Solicitudes, respuestas, estado e historial completo';
$messages['install'] = 'Instalación';
$messages['refresh'] = 'Actualizar';
$messages['confirm_delete'] = '¿Eliminar la solicitud de contacto?';
$messages['delete_tooltip'] = 'Eliminar solicitud';
$messages['delete_title'] = '<i class=\'bi bi-trash\'></i> Eliminar solicitud de contacto';
$messages['report_title'] = 'Solicitudes de contacto';
$messages['delete_question'] = '¿Eliminar la solicitud de contacto #{id}?';
$messages['delete_hint_thread'] = '<small>Esta solicitud tiene un historial con {count} mensaje(s). Se eliminará todo el historial.</small>';
$messages['delete_hint_empty'] = '<small>Esta solicitud no tiene un historial independiente. Se eliminará definitivamente.</small>';
$messages['delete_success'] = 'Se eliminaron la solicitud de contacto #{id} y su historial.';
$messages['delete_error'] = 'No se pudo eliminar la solicitud de contacto #{id}.';
$messages['column_ticket'] = 'Ticket';
$messages['column_activity'] = 'Última actividad';
$messages['column_status'] = 'Estado';
$messages['column_priority'] = 'Prioridad';
$messages['column_user'] = 'Usuario';
$messages['column_name'] = 'Nombre';
$messages['column_email'] = 'Correo electrónico';
$messages['column_subject'] = 'Asunto';
$messages['column_action'] = 'Acción';
$messages['status_open'] = 'Abierta';
$messages['status_in_progress'] = 'En curso';
$messages['status_waiting_customer'] = 'Esperando al cliente';
$messages['status_answered'] = 'Respondida';
$messages['status_closed'] = 'Cerrada';
$messages['priority_low'] = 'Baja';
$messages['priority_normal'] = 'Normal';
$messages['priority_high'] = 'Alta';
$messages['priority_urgent'] = 'Urgente';
$messages['guest'] = 'Invitado';
$messages['user_hidden'] = 'Oculta por el usuario';
$messages['user_visible'] = 'Visible en la cuenta del usuario';
$messages['ticket_not_found'] = 'No se encontró el ticket.';
$messages['timeline_internal_note'] = 'Nota interna';
$messages['timeline_support'] = 'Soporte';
$messages['timeline_requester'] = 'Solicitante';
$messages['timeline_system'] = 'Sistema';
$messages['timeline_internal_only'] = 'Solo interno';
$messages['timeline_status'] = 'Estado: {status}';
$messages['timeline_mail_sent'] = 'Correo electrónico enviado';
$messages['timeline_empty'] = 'Aún no hay mensajes.';
$messages['stat_open'] = 'Abiertas';
$messages['stat_progress'] = 'En curso';
$messages['stat_waiting'] = 'Respuestas del cliente';
$messages['stat_answered'] = 'Respondidas';
$messages['stat_closed'] = 'Cerradas';


$field=array();
$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['default']='30';
$field['label']='Por página';
$field['rules']='int';
$field['options']='10=10&20=20&30=30&50=50&100=100';
$fields[]=$field;

$field=array();
$field['name']='dbx_rstatus';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='all';
$field['label']='Estado';
$field['rules']='parameter';
$field['options']='all=Todos&open=Abierta&in_progress=En curso&waiting_customer=Esperando al cliente&answered=Respondida&closed=Cerrada';
$fields[]=$field;

$field=array();
$field['name']='dbx_rpriority';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='all';
$field['label']='Prioridad';
$field['rules']='parameter';
$field['options']='all=Todos&low=Baja&normal=Normal&high=Alta&urgent=Urgente';
$fields[]=$field;

$field=array();
$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='last_activity_date';
$field['label']='Ordenación';
$field['rules']='parameter';
$field['options']='last_activity_date=Última actividad&create_date=Creado&id=ID&status=Estado&priority=Prioridad&subject=Asunto';
$fields[]=$field;

$field=array();
$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='DESC';
$field['label']='Dirección';
$field['rules']='parameter';
$field['options']='DESC=Descendente&ASC=Ascendente';
$fields[]=$field;

$field=array();
$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['default']='';
$field['label']='Buscar';
$field['rules']='sqlsearch|max=100';
$fields[]=$field;
