<?php
$messages = array();
$messages['save_success'] = 'Data was saved';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Data could not be saved';
$messages['frame_title'] = 'Contact requests and tickets';
$messages['frame_subtitle'] = 'Requests, replies, status and complete history';
$messages['install'] = 'Installation';
$messages['refresh'] = 'Refresh';
$messages['confirm_delete'] = 'Delete contact request?';
$messages['delete_tooltip'] = 'Delete request';
$messages['delete_title'] = '<i class=\'bi bi-trash\'></i> Delete contact request';
$messages['report_title'] = 'Contact requests';
$messages['delete_question'] = 'Delete contact request #{id}?';
$messages['delete_hint_thread'] = '<small>This request has a history with {count} message(s). The complete history will be deleted.</small>';
$messages['delete_hint_empty'] = '<small>This request has no separate history. The request will be deleted permanently.</small>';
$messages['delete_success'] = 'Contact request #{id} and its history were deleted.';
$messages['delete_error'] = 'Contact request #{id} could not be deleted.';
$messages['column_ticket'] = 'Ticket';
$messages['column_activity'] = 'Last activity';
$messages['column_status'] = 'Status';
$messages['column_priority'] = 'Priority';
$messages['column_user'] = 'User';
$messages['column_name'] = 'Name';
$messages['column_email'] = 'Email';
$messages['column_subject'] = 'Subject';
$messages['column_action'] = 'Action';
$messages['status_open'] = 'Open';
$messages['status_in_progress'] = 'In progress';
$messages['status_waiting_customer'] = 'Waiting for customer';
$messages['status_answered'] = 'Answered';
$messages['status_closed'] = 'Closed';
$messages['priority_low'] = 'Low';
$messages['priority_normal'] = 'Normal';
$messages['priority_high'] = 'High';
$messages['priority_urgent'] = 'Urgent';
$messages['guest'] = 'Guest';
$messages['user_hidden'] = 'Hidden by the user';
$messages['user_visible'] = 'Visible in the user account';
$messages['ticket_not_found'] = 'Ticket not found.';
$messages['timeline_internal_note'] = 'Internal note';
$messages['timeline_support'] = 'Support';
$messages['timeline_requester'] = 'Requester';
$messages['timeline_system'] = 'System';
$messages['timeline_internal_only'] = 'Internal only';
$messages['timeline_status'] = 'Status: {status}';
$messages['timeline_mail_sent'] = 'E-mail sent';
$messages['timeline_empty'] = 'No messages are available yet.';
$messages['stat_open'] = 'Open';
$messages['stat_progress'] = 'In progress';
$messages['stat_waiting'] = 'Customer replies';
$messages['stat_answered'] = 'Answered';
$messages['stat_closed'] = 'Closed';


$field=array();
$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['default']='30';
$field['label']='Per page';
$field['rules']='int';
$field['options']='10=10&20=20&30=30&50=50&100=100';
$fields[]=$field;

$field=array();
$field['name']='dbx_rstatus';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='all';
$field['label']='Status';
$field['rules']='parameter';
$field['options']='all=All&open=Open&in_progress=In progress&waiting_customer=Waiting for customer&answered=Answered&closed=Closed';
$fields[]=$field;

$field=array();
$field['name']='dbx_rpriority';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='all';
$field['label']='Priority';
$field['rules']='parameter';
$field['options']='all=All&low=Low&normal=Normal&high=High&urgent=Urgent';
$fields[]=$field;

$field=array();
$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='last_activity_date';
$field['label']='Sorting';
$field['rules']='parameter';
$field['options']='last_activity_date=Last activity&create_date=Created&id=ID&status=Status&priority=Priority&subject=Subject';
$fields[]=$field;

$field=array();
$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['default']='DESC';
$field['label']='Direction';
$field['rules']='parameter';
$field['options']='DESC=Descending&ASC=Ascending';
$fields[]=$field;

$field=array();
$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['default']='';
$field['label']='Search';
$field['rules']='sqlsearch|max=100';
$fields[]=$field;
