<?php
// Felddefinitionen fuer dbx/modules/dbx/cfg/config.php (System-Config).

$field = array();
$field['name'] = 'version';
$field['type'] = 'int';
$field['length'] = '4';
$field['default'] = '1';
$field['label'] = 'Versionsnummer';
$field['rules'] = 'int';
$field['tooltip'] = 'Interne Config-Versionsnummer des dbx-Moduls.';
$field['errormsg'] = 'Version muss eine Zahl sein.';
$field['placeholder'] = '1';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'activ';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '1';
$field['label'] = 'Modul aktiv';
$field['rules'] = '*';
$field['tooltip'] = 'Schaltet das Kernmodul dbx ein oder aus.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'groups';
$field['type'] = 'varchar';
$field['length'] = '256';
$field['default'] = '*';
$field['label'] = 'Zugriff';
$field['rules'] = '*';
$field['tooltip'] = 'Benutzergruppen mit Zugriff auf das Systemmodul.';
$field['options'] = 'sql:dbxUser_groups|name|description|active = 1|name ASC|88';
$field['tpl'] = 'select-multible-label';
$fields[] = $field;

$field = array();
$field['name'] = 'default_lng';
$field['type'] = 'varchar';
$field['length'] = '3';
$field['default'] = 'de';
$field['label'] = 'Standard-Sprache';
$field['rules'] = '*';
$field['tooltip'] = 'Fallback-Sprache des Systems.';
$field['placeholder'] = 'de';
$field['options'] = 'de=Deutsch&en=English&es=Espanol';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'accessible_lng';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = 'de';
$field['label'] = 'Verfuegbare Sprachen';
$field['rules'] = '*';
$field['tooltip'] = 'Sprachen, die Benutzer waehlen duerfen.';
$field['options'] = 'de=Deutsch&en=English&es=Espanol';
$field['tpl'] = 'select-multible-label';
$fields[] = $field;

$field = array();
$field['name'] = 'default_color';
$field['type'] = 'varchar';
$field['length'] = '16';
$field['default'] = 'blau';
$field['label'] = 'Standard-Skin';
$field['rules'] = '*';
$field['tooltip'] = 'Farbschema (Skin) fuer neue Besucher.';
$field['options'] = 'hell=Hell&gelb=Gelb&rot=Rot&gruen=Gruen&blau=Blau&dunkel=Dunkel';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'default_design_user';
$field['type'] = 'varchar';
$field['length'] = '16';
$field['default'] = 'dbxapp';
$field['label'] = 'Design (Benutzer)';
$field['rules'] = '*';
$field['tooltip'] = 'Layout-Paket fuer oeffentliche Seiten.';
$field['options'] = 'dbxapp=dbXapp&flowers=Flowers';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'default_design_admin';
$field['type'] = 'varchar';
$field['length'] = '16';
$field['default'] = 'dbxapp';
$field['label'] = 'Design (Admin)';
$field['rules'] = '*';
$field['tooltip'] = 'Layout-Paket fuer den Admin-Bereich.';
$field['options'] = 'lda=LabOrgemeinschaft&dbxapp=dbXapp&_admin=Admin&_construct=Construct&_install=Install';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'session_db';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '1';
$field['label'] = 'Session-DB speichern';
$field['rules'] = '*';
$field['tooltip'] = 'Normale HTTP-Requests und HTML-AJAX-Requests am Request-Ende in der Session-Datenbank speichern.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'permalink';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '1';
$field['label'] = 'Permalinks';
$field['rules'] = '*';
$field['tooltip'] = 'Schoene URLs / Permalink-Aufloesung aktivieren.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'cache';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'System-Cache';
$field['rules'] = '*';
$field['tooltip'] = 'Templates und Modul-Configs in der Session cachen.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'cache_content';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '1';
$field['label'] = 'Content-Cache';
$field['rules'] = '*';
$field['tooltip'] = 'Gerenderte Content-Seiten und Permalink-Index als HTML cachen.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'sys_msg_level';
$field['type'] = 'varchar';
$field['length'] = '16';
$field['default'] = 'all';
$field['label'] = 'SysMsg-Level';
$field['rules'] = 'parameter';
$field['tooltip'] = 'Steuert, welche Systemmeldungen in dbxSysMsg gespeichert werden.';
$field['options'] = 'error=Nur Error&warning=Error und Warning&all=Alles';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'performance_timer_level';
$field['type'] = 'varchar';
$field['length'] = '16';
$field['default'] = 'off';
$field['label'] = 'Performance-Level';
$field['rules'] = 'parameter';
$field['tooltip'] = 'Steuert, ob keine Performance-Daten, nur Hauptkennzahlen oder alle Detail-Timer gespeichert werden.';
$field['options'] = 'off=Aus&main=Nur Hauptkennzahlen&detail=Hauptkennzahlen und Details';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'performance_timer_sample_rate';
$field['type'] = 'int';
$field['length'] = '8';
$field['default'] = '1';
$field['label'] = 'Performance: Sample-Rate';
$field['rules'] = 'int|min=1';
$field['tooltip'] = 'Nur jeden N-ten Request messen (1 = jeder Request).';
$field['placeholder'] = '1';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'performance_timer_keep_days';
$field['type'] = 'int';
$field['length'] = '4';
$field['default'] = '14';
$field['label'] = 'Performance: Aufbewahrung (Tage)';
$field['rules'] = 'int|min=1';
$field['tooltip'] = 'Alte Performance-Daten nach X Tagen loeschen.';
$field['placeholder'] = '14';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'performance_timer_slow_ms';
$field['type'] = 'int';
$field['length'] = '8';
$field['default'] = '3000';
$field['label'] = 'Performance: Langsam ab (ms)';
$field['rules'] = 'int|min=0';
$field['tooltip'] = 'Schwellwert fuer langsame Requests im Dashboard.';
$field['placeholder'] = '3000';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'performance_timer_slow_query_ms';
$field['type'] = 'int';
$field['length'] = '8';
$field['default'] = '100';
$field['label'] = 'Performance: Query langsam ab (ms)';
$field['rules'] = 'int|min=1';
$field['tooltip'] = 'Schwellwert fuer langsame einzelne Datenbankabfragen.';
$field['placeholder'] = '100';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'intro';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Intro-Seite';
$field['rules'] = '*';
$field['tooltip'] = 'Intro beim ersten Besuch anzeigen.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'construct';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Wartungsmodus';
$field['rules'] = '*';
$field['tooltip'] = 'Anwendung als in Ueberarbeitung markieren.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'install';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Installationsmodus';
$field['rules'] = '*';
$field['tooltip'] = 'Setup-/Installationsmodus aktivieren.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'crypt_cfg';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Config verschluesseln';
$field['rules'] = '*';
$field['tooltip'] = 'Modul-Config-Dateien verschluesselt speichern.';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'secure';
$field['type'] = 'varchar';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Schluessel (secure)';
$field['rules'] = '*';
$field['tooltip'] = 'Schluessel fuer verschluesselte Config-Dateien.';
$field['placeholder'] = '';
$field['tpl'] = 'password-label';
$fields[] = $field;

$field = array();
$field['name'] = 'default_server';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = '';
$field['label'] = 'Standard-DB-Server';
$field['rules'] = '*';
$field['tooltip'] = 'Standard-SQL-Server aus config.php. Modul-SQLite (*.db3) wird von dbxDB automatisch aus dbx/modules/*/db/ aufgeloest.';
$field['options'] = '';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'default_mail';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = '';
$field['label'] = 'Standard-Mail-Profil';
$field['rules'] = '*';
$field['tooltip'] = 'Name des Mail-Eintrags aus dem Tab Mail.';
$field['placeholder'] = 'dbxApp';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field = array();
$field['name'] = 'module_images';
$field['type'] = 'varchar';
$field['length'] = '512';
$field['default'] = '';
$field['label'] = 'Modul-Bilder (Dashboard)';
$field['rules'] = '*';
$field['tooltip'] = 'Kommagetrennte Dateinamen unter files/mod/ fuer das Admin-Dashboard.';
$field['placeholder'] = 'dbx_beispiel.png';
$field['tpl'] = 'text-label';
$fields[] = $field;
