<?php
$messages = array();
$messages['save_success'] = 'Data was saved';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Data could not be saved';
$messages['bar_title'] = 'Products';
$messages['bar_subtitle'] = 'Products, orders, legal texts and withdrawals';
$messages['new_product'] = 'New product';
$messages['new_product_title'] = 'Create a new product';
$messages['products_help'] = 'Help: products';
$messages['delete_confirm'] = 'Do you really want to delete this product?';
$messages['report_info'] = 'Search and review products and edit them in a window.';
$messages['column_image'] = 'Image';
$messages['column_product'] = 'Product';
$messages['column_product_groups'] = 'Product groups';
$messages['column_attributes'] = 'Attributes';
$messages['column_shipping_groups'] = 'Shipping groups';
$messages['column_channel_groups'] = 'Channel groups';
$messages['column_channels'] = 'Channels';
$messages['column_price'] = 'Price';
$messages['column_tax'] = 'VAT';
$messages['column_shipping'] = 'Shipping';
$messages['column_status'] = 'Status';
$messages['no_results'] = 'No products were found for this search.';
$messages['no_image'] = 'no image';
$messages['no_values'] = 'no values';
$messages['status_active'] = 'Active';
$messages['status_inactive'] = 'Inactive';
$messages['action_edit'] = 'Edit product: {title}';
$messages['action_view'] = 'View product: {title}';
$messages['action_delete_confirm'] = 'Do you really want to delete product “{title}”?';
$messages['bulk_channel_placeholder'] = 'Channel';
$messages['bulk_group_placeholder'] = 'Product group';
$messages['bulk_action_placeholder'] = 'Choose an action';
$messages['bulk_delete'] = 'Delete selected products';
$messages['bulk_channel_add'] = 'Add channel';
$messages['bulk_channel_remove'] = 'Remove channel';
$messages['bulk_channel_export'] = 'Export to channel';
$messages['bulk_group_set'] = 'Set product group';
$messages['bulk_title'] = 'Bulk action';
$messages['bulk_channel_title'] = 'Channel for bulk action';
$messages['bulk_group_title'] = 'Product group for bulk action';
$messages['bulk_confirm_title'] = 'Run bulk action';
$messages['bulk_confirm_question'] = 'Apply the action to the selected products?';
$messages['bulk_confirm_hint'] = 'Deleting moves products to the trash. Select the appropriate value for channel and group actions.';
$messages['bulk_execute'] = 'Run';
$messages['product_delete_success'] = 'The product was deleted.';
$messages['product_delete_error'] = 'The product could not be deleted.';
$messages['choose_action'] = 'Please choose an action.';
$messages['select_products'] = 'Please select products first.';
$messages['choose_channel'] = 'Please choose a channel.';
$messages['choose_group'] = 'Please choose a product group.';
$messages['multi_deleted_one'] = '1 product was deleted.';
$messages['multi_deleted_many'] = '{count} products were deleted.';
$messages['channel_added'] = '{count} products were activated for channel {channel}.';
$messages['channel_removed'] = '{count} products were removed from channel {channel}.';
$messages['export_summary'] = '{ok} export(s) succeeded, {failed} failed.';
$messages['group_set'] = '{count} products were assigned to the product group.';
$messages['token_error'] = 'The action was rejected for security reasons. Please reload the page.';
$messages['tree_product_fallback'] = 'Product';
$messages['tree_group_fallback'] = 'Product group';
$messages['tree_edit_product'] = 'Edit product';
$messages['tree_toggle_group'] = 'Expand or collapse group';
$messages['tree_counts'] = '{groups} groups, {products} products';
$messages['tree_edit_groups'] = 'Edit product groups';
$messages['tree_search_placeholder'] = 'Search product group or product';
$messages['tree_search_title'] = 'Search tree';
$messages['tree_aria'] = 'Product group tree';
$messages['tree_title'] = 'Product group tree';
$messages['tree_subtitle'] = 'Assign products and move groups.';
$messages['tree_edit_groups_button'] = 'Edit groups';
$messages['tree_close'] = 'Close tree';
$messages['tree_ungrouped'] = 'Without product group';
$messages['tree_open'] = 'Show product group tree';


$field = array();
$field['name'] = 'dbx_rrows';
$field['type'] = 'int';
$field['tpl'] = 'select-single-label';
$field['default'] = '30';
$field['label'] = 'No. page';
$field['rules'] = 'int';
$field['options'] = '10=10&20=20&30=30&50=50&100=100&0=All';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rsort';
$field['type'] = 'varchar';
$field['tpl'] = 'select-single-label';
$field['default'] = 'sorter';
$field['label'] = 'Sorting';
$field['rules'] = 'parameter';
$field['options'] = 'sorter=Sorting&sku=SKU&title=Product&price_gross=Price&effective_tax_rate=VAT&effective_shipping_gross=Dispatch&active=Active';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rdesc';
$field['type'] = 'varchar';
$field['tpl'] = 'select-single-label';
$field['default'] = 'ASC';
$field['label'] = 'Direction';
$field['rules'] = 'parameter';
$field['options'] = 'ASC=Ascending&DESC=Descending';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rwhere';
$field['type'] = 'varchar';
$field['tpl'] = 'dbx|search';
$field['default'] = '';
$field['label'] = 'Search';
$field['rules'] = 'parameter|max=100';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rselect';
$field['type'] = 'int';
$field['tpl'] = 'select-single-label';
$field['default'] = '0';
$field['label'] = 'Selected';
$field['rules'] = 'int';
$field['options'] = '0=All&1=Selected';
$fields[] = $field;
