<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['bar_title'] = 'Productos';
$messages['bar_subtitle'] = 'Productos, pedidos, textos legales y desistimientos';
$messages['new_product'] = 'Nuevo producto';
$messages['new_product_title'] = 'Crear un nuevo producto';
$messages['products_help'] = 'Ayuda: productos';
$messages['delete_confirm'] = '¿Desea realmente eliminar este producto?';
$messages['report_info'] = 'Busque y revise productos y edítelos en una ventana.';
$messages['column_image'] = 'Imagen';
$messages['column_product'] = 'Producto';
$messages['column_product_groups'] = 'Grupos de productos';
$messages['column_attributes'] = 'Atributos';
$messages['column_shipping_groups'] = 'Grupos de envío';
$messages['column_channel_groups'] = 'Grupos de canales';
$messages['column_channels'] = 'Canales';
$messages['column_price'] = 'Precio';
$messages['column_tax'] = 'IVA';
$messages['column_shipping'] = 'Envío';
$messages['column_status'] = 'Estado';
$messages['no_results'] = 'No se encontraron productos para esta búsqueda.';
$messages['no_image'] = 'sin imagen';
$messages['no_values'] = 'sin valores';
$messages['status_active'] = 'Activo';
$messages['status_inactive'] = 'Inactivo';
$messages['action_edit'] = 'Editar producto: {title}';
$messages['action_view'] = 'Ver producto: {title}';
$messages['action_delete_confirm'] = '¿Desea realmente eliminar el producto «{title}»?';
$messages['bulk_channel_placeholder'] = 'Canal';
$messages['bulk_group_placeholder'] = 'Grupo de productos';
$messages['bulk_action_placeholder'] = 'Elegir una acción';
$messages['bulk_delete'] = 'Eliminar productos seleccionados';
$messages['bulk_channel_add'] = 'Añadir canal';
$messages['bulk_channel_remove'] = 'Eliminar canal';
$messages['bulk_channel_export'] = 'Exportar al canal';
$messages['bulk_group_set'] = 'Asignar grupo de productos';
$messages['bulk_title'] = 'Acción múltiple';
$messages['bulk_channel_title'] = 'Canal para la acción múltiple';
$messages['bulk_group_title'] = 'Grupo de productos para la acción múltiple';
$messages['bulk_confirm_title'] = 'Ejecutar acción múltiple';
$messages['bulk_confirm_question'] = '¿Aplicar la acción a los productos seleccionados?';
$messages['bulk_confirm_hint'] = 'Al eliminar, los productos se mueven a la papelera. Seleccione el valor correspondiente para las acciones de canal y grupo.';
$messages['bulk_execute'] = 'Ejecutar';
$messages['product_delete_success'] = 'El producto se eliminó.';
$messages['product_delete_error'] = 'No se pudo eliminar el producto.';
$messages['choose_action'] = 'Seleccione una acción.';
$messages['select_products'] = 'Seleccione primero los productos.';
$messages['choose_channel'] = 'Seleccione un canal.';
$messages['choose_group'] = 'Seleccione un grupo de productos.';
$messages['multi_deleted_one'] = 'Se eliminó 1 producto.';
$messages['multi_deleted_many'] = 'Se eliminaron {count} productos.';
$messages['channel_added'] = 'Se activaron {count} productos para el canal {channel}.';
$messages['channel_removed'] = 'Se eliminaron {count} productos del canal {channel}.';
$messages['export_summary'] = '{ok} exportación(es) correcta(s), {failed} fallida(s).';
$messages['group_set'] = 'Se asignaron {count} productos al grupo de productos.';
$messages['token_error'] = 'La acción fue rechazada por motivos de seguridad. Vuelva a cargar la página.';
$messages['tree_product_fallback'] = 'Producto';
$messages['tree_group_fallback'] = 'Grupo de productos';
$messages['tree_edit_product'] = 'Editar producto';
$messages['tree_toggle_group'] = 'Expandir o contraer el grupo';
$messages['tree_counts'] = '{groups} grupos, {products} productos';
$messages['tree_edit_groups'] = 'Editar grupos de productos';
$messages['tree_search_placeholder'] = 'Buscar grupo de productos o producto';
$messages['tree_search_title'] = 'Buscar en el árbol';
$messages['tree_aria'] = 'Árbol de grupos de productos';
$messages['tree_title'] = 'Árbol de grupos de productos';
$messages['tree_subtitle'] = 'Asignar productos y mover grupos.';
$messages['tree_edit_groups_button'] = 'Editar grupos';
$messages['tree_close'] = 'Cerrar árbol';
$messages['tree_ungrouped'] = 'Sin grupo de productos';
$messages['tree_open'] = 'Mostrar el árbol de grupos de productos';


$field = array();
$field['name'] = 'dbx_rrows';
$field['type'] = 'int';
$field['tpl'] = 'select-single-label';
$field['default'] = '30';
$field['label'] = 'No. página';
$field['rules'] = 'int';
$field['options'] = '10=10&20=20&30=30&50=50&100=100&0=Todos';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rsort';
$field['type'] = 'varchar';
$field['tpl'] = 'select-single-label';
$field['default'] = 'sorter';
$field['label'] = 'Orden';
$field['rules'] = 'parameter';
$field['options'] = 'sorter=Orden&sku=SKU&title=Artículo&price_gross=Precio&effective_tax_rate=IVA&effective_shipping_gross=Despacho&active=Activo';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rdesc';
$field['type'] = 'varchar';
$field['tpl'] = 'select-single-label';
$field['default'] = 'ASC';
$field['label'] = 'Dirección';
$field['rules'] = 'parameter';
$field['options'] = 'ASC=Ascendente&DESC=Descendente';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rwhere';
$field['type'] = 'varchar';
$field['tpl'] = 'dbx|search';
$field['default'] = '';
$field['label'] = 'Búsqueda';
$field['rules'] = 'parameter|max=100';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rselect';
$field['type'] = 'int';
$field['tpl'] = 'select-single-label';
$field['default'] = '0';
$field['label'] = 'Seleccionado';
$field['rules'] = 'int';
$field['options'] = '0=Todos&1=Seleccionado';
$fields[] = $field;
