<?php
$messages = array();
$messages['save_success'] = 'Daten wurden gespeichert';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Daten konnten nicht gespeichert werden';
$messages['bar_title'] = 'Produkte';
$messages['bar_subtitle'] = 'Produkte, Bestellungen, Rechtstexte und Widerrufe';
$messages['new_product'] = 'Neuer Artikel';
$messages['new_product_title'] = 'Neuen Artikel anlegen';
$messages['products_help'] = 'Hilfe: Produkte';
$messages['delete_confirm'] = 'Diesen Artikel wirklich löschen?';
$messages['report_info'] = 'Produkte suchen, prüfen und über Fenster bearbeiten.';
$messages['column_image'] = 'Bild';
$messages['column_product'] = 'Artikel';
$messages['column_product_groups'] = 'Artikelgruppen';
$messages['column_attributes'] = 'Attribute';
$messages['column_shipping_groups'] = 'Versandgruppen';
$messages['column_channel_groups'] = 'Channel-Gruppen';
$messages['column_channels'] = 'Channels';
$messages['column_price'] = 'Preis';
$messages['column_tax'] = 'MwSt.';
$messages['column_shipping'] = 'Versand';
$messages['column_status'] = 'Status';
$messages['no_results'] = 'Keine Produkte für diese Suche gefunden.';
$messages['no_image'] = 'kein Bild';
$messages['no_values'] = 'keine Werte';
$messages['status_active'] = 'Aktiv';
$messages['status_inactive'] = 'Inaktiv';
$messages['action_edit'] = 'Artikel bearbeiten: {title}';
$messages['action_view'] = 'Artikel ansehen: {title}';
$messages['action_delete_confirm'] = 'Artikel „{title}“ wirklich löschen?';
$messages['bulk_channel_placeholder'] = 'Channel';
$messages['bulk_group_placeholder'] = 'Produktgruppe';
$messages['bulk_action_placeholder'] = 'Aktion wählen';
$messages['bulk_delete'] = 'Ausgewählte Produkte löschen';
$messages['bulk_channel_add'] = 'Channel hinzufügen';
$messages['bulk_channel_remove'] = 'Channel entfernen';
$messages['bulk_channel_export'] = 'Channel exportieren';
$messages['bulk_group_set'] = 'Produktgruppe setzen';
$messages['bulk_title'] = 'Mehrfachaktion';
$messages['bulk_channel_title'] = 'Channel für Mehrfachaktion';
$messages['bulk_group_title'] = 'Produktgruppe für Mehrfachaktion';
$messages['bulk_confirm_title'] = 'Mehrfachaktion ausführen';
$messages['bulk_confirm_question'] = 'Aktion auf die ausgewählten Produkte anwenden?';
$messages['bulk_confirm_hint'] = 'Beim Löschen werden die Produkte in den Papierkorb verschoben. Für Channel- und Gruppenaktionen bitte das passende Auswahlfeld setzen.';
$messages['bulk_execute'] = 'Ausführen';
$messages['product_delete_success'] = 'Artikel gelöscht.';
$messages['product_delete_error'] = 'Artikel konnte nicht gelöscht werden.';
$messages['choose_action'] = 'Bitte wählen Sie eine Aktion aus.';
$messages['select_products'] = 'Bitte wählen Sie zuerst Produkte aus.';
$messages['choose_channel'] = 'Bitte wählen Sie einen Channel aus.';
$messages['choose_group'] = 'Bitte wählen Sie eine Produktgruppe aus.';
$messages['multi_deleted_one'] = '1 Produkt gelöscht.';
$messages['multi_deleted_many'] = '{count} Produkte gelöscht.';
$messages['channel_added'] = '{count} Produkte für Channel {channel} aktiviert.';
$messages['channel_removed'] = '{count} Produkte aus Channel {channel} entfernt.';
$messages['export_summary'] = '{ok} Export(e) erfolgreich, {failed} fehlgeschlagen.';
$messages['group_set'] = '{count} Produkte der Produktgruppe zugeordnet.';
$messages['token_error'] = 'Die Aktion wurde aus Sicherheitsgründen abgewiesen. Bitte laden Sie die Seite neu.';
$messages['tree_product_fallback'] = 'Artikel';
$messages['tree_group_fallback'] = 'Artikelgruppe';
$messages['tree_edit_product'] = 'Artikel bearbeiten';
$messages['tree_toggle_group'] = 'Gruppe ein- oder ausklappen';
$messages['tree_counts'] = '{groups} Gruppen, {products} Artikel';
$messages['tree_edit_groups'] = 'Artikelgruppen bearbeiten';
$messages['tree_search_placeholder'] = 'Artikelgruppe oder Artikel suchen';
$messages['tree_search_title'] = 'Baum durchsuchen';
$messages['tree_aria'] = 'Artikelgruppen-Baum';
$messages['tree_title'] = 'Artikelgruppen-Baum';
$messages['tree_subtitle'] = 'Artikel zuordnen, Gruppen verschieben.';
$messages['tree_edit_groups_button'] = 'Gruppen bearbeiten';
$messages['tree_close'] = 'Baum schließen';
$messages['tree_ungrouped'] = 'Ohne Artikelgruppe';
$messages['tree_open'] = 'Artikelgruppen-Baum anzeigen';


$field = array();
$field['name'] = 'dbx_rrows';
$field['type'] = 'int';
$field['tpl'] = 'select-single-label';
$field['default'] = '30';
$field['label'] = 'Anz. Seite';
$field['rules'] = 'int';
$field['options'] = '10=10&20=20&30=30&50=50&100=100&0=Alle';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rsort';
$field['type'] = 'varchar';
$field['tpl'] = 'select-single-label';
$field['default'] = 'sorter';
$field['label'] = 'Sortierung';
$field['rules'] = 'parameter';
$field['options'] = 'sorter=Sortierung&sku=SKU&title=Artikel&price_gross=Preis&effective_tax_rate=MwSt.&effective_shipping_gross=Versand&active=Aktiv';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rdesc';
$field['type'] = 'varchar';
$field['tpl'] = 'select-single-label';
$field['default'] = 'ASC';
$field['label'] = 'Richtung';
$field['rules'] = 'parameter';
$field['options'] = 'ASC=Aufsteigend&DESC=Absteigend';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rwhere';
$field['type'] = 'varchar';
$field['tpl'] = 'dbx|search';
$field['default'] = '';
$field['label'] = 'Suchen';
$field['rules'] = 'parameter|max=100';
$fields[] = $field;

$field = array();
$field['name'] = 'dbx_rselect';
$field['type'] = 'int';
$field['tpl'] = 'select-single-label';
$field['default'] = '0';
$field['label'] = 'Ausgewaehlte';
$field['rules'] = 'int';
$field['options'] = '0=Alle&1=Ausgewaehlte';
$fields[] = $field;
