#!/usr/bin/env python3
"""Build the dbxapp homepage image set and a compact original product film.

The three source images are generated separately. This build step creates the
web-ready WebP assets, a 48-second motion-design film and its own synthesized
soundtrack. The soundtrack is generated by this script and therefore does not
depend on third-party music rights.
"""

from __future__ import annotations

import argparse
import math
import subprocess
import wave
from functools import lru_cache
from pathlib import Path

import imageio_ffmpeg
import numpy as np
from PIL import Image, ImageDraw, ImageEnhance, ImageFont


VIDEO_SIZE = (1280, 720)
VIDEO_FPS = 24
VIDEO_DURATION = 48.0
SCENE_DURATION = VIDEO_DURATION / 3
FADE_DURATION = 1.25


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--hero", required=True, type=Path)
    parser.add_argument("--transform", required=True, type=Path)
    parser.add_argument("--modules", required=True, type=Path)
    parser.add_argument("--output-root", required=True, type=Path)
    return parser.parse_args()


@lru_cache(maxsize=16)
def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    filename = "segoeuib.ttf" if bold else "segoeui.ttf"
    path = Path("C:/Windows/Fonts") / filename
    return ImageFont.truetype(str(path), size)


def cover(source: Image.Image, size: tuple[int, int], scale: float = 1.0, shift: float = 0.0) -> Image.Image:
    source = source.convert("RGB")
    target_w, target_h = size
    ratio = max(target_w / source.width, target_h / source.height) * scale
    resized = source.resize(
        (max(target_w, round(source.width * ratio)), max(target_h, round(source.height * ratio))),
        Image.Resampling.LANCZOS,
    )
    available_x = max(0, resized.width - target_w)
    available_y = max(0, resized.height - target_h)
    left = round(available_x * min(1.0, max(0.0, 0.5 + shift)))
    top = round(available_y * 0.5)
    return resized.crop((left, top, left + target_w, top + target_h))


def save_web_assets(images: list[Image.Image], root: Path) -> dict[str, Path]:
    hero_dir = root / "files/media/img/hero"
    image_dir = root / "files/media/img/images"
    video_dir = root / "files/media/video"
    for directory in (hero_dir, image_dir, video_dir):
        directory.mkdir(parents=True, exist_ok=True)

    paths = {
        "hero": hero_dir / "dbxapp-platform-hero-20260728.webp",
        "transform": image_dir / "dbxapp-systeme-neu-denken-20260728.webp",
        "modules": image_dir / "dbxapp-modular-wachsen-20260728.webp",
        "poster": image_dir / "dbxapp-kurzfilm-poster-20260728.webp",
        "video": video_dir / "dbxapp-kurzfilm-20260728.mp4",
    }
    cover(images[0], (2560, 640)).save(paths["hero"], "WEBP", quality=88, method=6)
    cover(images[1], (1600, 900)).save(paths["transform"], "WEBP", quality=88, method=6)
    cover(images[2], (1600, 900)).save(paths["modules"], "WEBP", quality=88, method=6)
    cover(images[0], (1600, 900), scale=1.03).save(paths["poster"], "WEBP", quality=88, method=6)
    return paths


def text_alpha(local_time: float) -> float:
    fade_in = min(1.0, max(0.0, (local_time - 0.5) / 1.2))
    fade_out = min(1.0, max(0.0, (SCENE_DURATION - local_time - 0.5) / 1.2))
    return min(fade_in, fade_out)


def draw_brand(draw: ImageDraw.ImageDraw, alpha: int) -> None:
    x, y = 58, 45
    draw.text((x, y), "db", font=font(38, True), fill=(255, 255, 255, alpha))
    db_width = draw.textlength("db", font=font(38, True))
    draw.text((x + db_width, y), "X", font=font(42, True), fill=(238, 43, 55, alpha))
    x_width = draw.textlength("X", font=font(42, True))
    draw.text((x + db_width + x_width, y), "app", font=font(38, True), fill=(255, 255, 255, alpha))


def add_overlay(image: Image.Image, title: str, subtitle: str, alpha: float) -> Image.Image:
    rgba = image.convert("RGBA")
    alpha_line = Image.new("L", (rgba.width, 1))
    alpha_line.putdata([
        round(190 * max(0.0, 1.0 - x / (rgba.width * 0.72)))
        for x in range(rgba.width)
    ])
    shade = Image.new("RGBA", rgba.size, (1, 10, 27, 255))
    shade.putalpha(alpha_line.resize(rgba.size))
    rgba = Image.alpha_composite(rgba, shade)

    layer = Image.new("RGBA", rgba.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    a = round(255 * alpha)
    draw_brand(draw, max(170, a))
    draw.rounded_rectangle((58, 160, 66, 405), radius=4, fill=(238, 43, 55, a))
    draw.multiline_text(
        (92, 168),
        title,
        font=font(48, True),
        fill=(255, 255, 255, a),
        spacing=8,
    )
    draw.multiline_text(
        (94, 315),
        subtitle,
        font=font(23),
        fill=(210, 228, 250, a),
        spacing=6,
    )
    draw.text(
        (94, 641),
        "CMS  ·  SHOP  ·  ANWENDUNGEN  ·  WORKFLOWS  ·  KI",
        font=font(16, True),
        fill=(177, 207, 244, max(140, a)),
    )
    return Image.alpha_composite(rgba, layer).convert("RGB")


def scene_frame(images: list[Image.Image], second: float) -> Image.Image:
    scene_index = min(2, int(second // SCENE_DURATION))
    local = second - scene_index * SCENE_DURATION
    progress = min(1.0, max(0.0, local / SCENE_DURATION))
    shift = (-0.11 + progress * 0.18) if scene_index != 1 else (0.10 - progress * 0.2)
    frame = cover(images[scene_index], VIDEO_SIZE, scale=1.0 + progress * 0.055, shift=shift)

    if local > SCENE_DURATION - FADE_DURATION and scene_index < 2:
        next_progress = (local - (SCENE_DURATION - FADE_DURATION)) / FADE_DURATION
        next_frame = cover(images[scene_index + 1], VIDEO_SIZE, scale=1.0, shift=0.08)
        frame = Image.blend(frame, next_frame, next_progress)

    titles = (
        ("Eine Plattform.\nAlle Möglichkeiten.", "Website, Shop und Geschäftsanwendungen\narbeiten auf einer gemeinsamen Basis."),
        ("Bestehende Systeme\nneu denken.", "Funktionen leicht nachbilden,\nAbläufe vereinfachen und optimieren."),
        ("Modular starten.\nSicher wachsen.", "Ein Kern. Klare Rechte.\nErweiterbar nach tatsächlichem Bedarf."),
    )
    return add_overlay(frame, titles[scene_index][0], titles[scene_index][1], text_alpha(local))


def build_silent_video(images: list[Image.Image], output: Path) -> None:
    writer = imageio_ffmpeg.write_frames(
        str(output),
        VIDEO_SIZE,
        fps=VIDEO_FPS,
        codec="libx264",
        pix_fmt_in="rgb24",
        pix_fmt_out="yuv420p",
        quality=5,
        macro_block_size=16,
        output_params=["-preset", "medium", "-movflags", "+faststart"],
    )
    writer.send(None)
    try:
        frame_count = round(VIDEO_DURATION * VIDEO_FPS)
        for index in range(frame_count):
            writer.send(np.asarray(scene_frame(images, index / VIDEO_FPS)))
    finally:
        writer.close()


def add_tone(track: np.ndarray, start: float, duration: float, frequency: float, gain: float, sample_rate: int) -> None:
    first = round(start * sample_rate)
    count = min(round(duration * sample_rate), len(track) - first)
    if count <= 0:
        return
    t = np.arange(count, dtype=np.float64) / sample_rate
    attack = np.minimum(1.0, t / 0.025)
    release = np.minimum(1.0, (duration - t) / 0.12)
    envelope = np.maximum(0.0, np.minimum(attack, release))
    tone = np.sin(2 * math.pi * frequency * t)
    tone += 0.28 * np.sin(2 * math.pi * frequency * 2 * t)
    track[first:first + count] += gain * envelope * tone


def add_drum(track: np.ndarray, start: float, kind: str, sample_rate: int, rng: np.random.Generator) -> None:
    duration = {"kick": 0.26, "snare": 0.18, "hat": 0.07}[kind]
    first = round(start * sample_rate)
    count = min(round(duration * sample_rate), len(track) - first)
    if count <= 0:
        return
    t = np.arange(count, dtype=np.float64) / sample_rate
    if kind == "kick":
        wave_data = np.sin(2 * math.pi * (70 - 32 * t / duration) * t) * np.exp(-t * 18)
        gain = 0.52
    elif kind == "snare":
        wave_data = rng.normal(0, 1, count) * np.exp(-t * 23)
        gain = 0.16
    else:
        wave_data = rng.normal(0, 1, count) * np.exp(-t * 65)
        gain = 0.07
    track[first:first + count] += wave_data * gain


def build_original_music(output: Path) -> None:
    sample_rate = 44100
    count = round(VIDEO_DURATION * sample_rate)
    mono = np.zeros(count, dtype=np.float64)
    rng = np.random.default_rng(401)
    bpm = 120
    beat = 60 / bpm
    progression = (
        (146.83, 174.61, 220.00),
        (116.54, 146.83, 174.61),
        (130.81, 164.81, 196.00),
        (98.00, 123.47, 146.83),
    )

    for bar in range(math.ceil(VIDEO_DURATION / (beat * 4))):
        bar_start = bar * beat * 4
        chord = progression[bar % len(progression)]
        for note in chord:
            add_tone(mono, bar_start, beat * 4.15, note, 0.035, sample_rate)
        arpeggio = (chord[0] * 2, chord[1] * 2, chord[2] * 2, chord[1] * 2)
        for step in range(8):
            add_tone(mono, bar_start + step * beat / 2, beat * 0.42, arpeggio[step % 4], 0.055, sample_rate)

    for step in range(math.ceil(VIDEO_DURATION / (beat / 2))):
        moment = step * beat / 2
        add_drum(mono, moment, "hat", sample_rate, rng)
        if step % 4 in (0, 2):
            add_drum(mono, moment, "kick", sample_rate, rng)
        if step % 4 in (2,):
            add_drum(mono, moment, "snare", sample_rate, rng)

    fade = round(sample_rate * 1.8)
    mono[:fade] *= np.linspace(0, 1, fade)
    mono[-fade:] *= np.linspace(1, 0, fade)
    mono /= max(1.0, np.max(np.abs(mono)) / 0.84)
    right = np.roll(mono, 220) * 0.96
    stereo = np.column_stack((mono, right))
    pcm = np.int16(np.clip(stereo, -1, 1) * 32767)

    with wave.open(str(output), "wb") as wav:
        wav.setnchannels(2)
        wav.setsampwidth(2)
        wav.setframerate(sample_rate)
        wav.writeframes(pcm.tobytes())


def mux_video(silent: Path, music: Path, output: Path) -> None:
    command = [
        imageio_ffmpeg.get_ffmpeg_exe(),
        "-y",
        "-i", str(silent),
        "-i", str(music),
        "-c:v", "copy",
        "-c:a", "aac",
        "-b:a", "160k",
        "-shortest",
        "-movflags", "+faststart",
        str(output),
    ]
    subprocess.run(command, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)


def main() -> None:
    args = parse_args()
    images = [Image.open(path).convert("RGB") for path in (args.hero, args.transform, args.modules)]
    images = [ImageEnhance.Contrast(image).enhance(1.03) for image in images]
    paths = save_web_assets(images, args.output_root)
    temp_dir = args.output_root / "files/tmp/home-media-build"
    temp_dir.mkdir(parents=True, exist_ok=True)
    silent = temp_dir / "dbxapp-kurzfilm-silent.mp4"
    music = temp_dir / "dbxapp-kurzfilm-original.wav"
    build_silent_video(images, silent)
    build_original_music(music)
    mux_video(silent, music, paths["video"])
    silent.unlink(missing_ok=True)
    music.unlink(missing_ok=True)
    temp_dir.rmdir()
    for name, path in paths.items():
        print(f"{name}: {path}")


if __name__ == "__main__":
    main()
