<?php
$table['server']='dbxShop|dbxShop.db3';
$table['table']='shop_product_group';
$table['datadic']='shopProductGroup';
$table['primary']='id';
$table['language']='0';
$table['version']='0.1';
$table['autosync']='1';
$table['cache']='0';
$table['trash']='1';
$table['trace']='0';
$table['default_sort']='sorter ASC, title ASC';
$table['read']='*';
$table['create']='admin';
$table['update']='admin';
$table['delete']='admin';

$add_field = function($name, $type, $index, $length, $default, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']=$index;
   $field['length']=$length;
   $field['default']=$default;
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']=$extra['convert'] ?? '';
   $field['protect']=$extra['protect'] ?? '0';
   $field['group']=$extra['group'] ?? '';
   $field['mask']=$extra['mask'] ?? '';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$add_field('id','int','PRI','11','','ID','int','hidden');
$add_field('create_date','datetime','','-1','','Erstellt','datetime','hidden',array('convert'=>'date_time'));
$add_field('create_uid','int','','11','0','Erstellt von','int','hidden');
$add_field('update_date','datetime','','-1','','Aktualisiert','datetime','hidden',array('convert'=>'date_time'));
$add_field('update_uid','int','','11','0','Aktualisiert von','int','hidden');
$add_field('owner','int','','11','0','Owner','int','hidden');
$add_field('trash','int','','1','0','Trash','int','hidden');
$add_field('parent_id','int','MUL','11','0','Obergruppe','int','select-single-label');
$add_field('group_key','varchar','UNI','80','','Gruppen-Key','parameter|min=2|max=80','text-label');
$add_field('title','varchar','MUL','160','','Name','*|min=2|max=160','text-label');
$add_field('description','mediumtext','','-1','','Beschreibung','*|max=3000','textarea-label',array('data'=>'rows=4'));
$add_field('tax_class','varchar','MUL','40','mwst1','MwSt.-Satz','parameter|max=40','select-single-label');
$add_field('default_tax_rate','decimal','','5,2','19','Standard-MwSt. %','number','text-label');
$add_field('default_shipping_gross','decimal','','10,2','0','Standard-Versand brutto','number','text-label');
$add_field('display_variant','varchar','','80','gallery_grid','Darstellung','*|max=80','text-label');
$add_field('card_template','varchar','','120','product-card-default','Karten-Template','*|max=120','text-label');
$add_field('detail_template','varchar','','120','product-detail-default','Detail-Template','*|max=120','text-label');
$add_field('gallery_template','varchar','','120','image-gallery','Gallery-Template','*|max=120','text-label');
$add_field('gallery_visible_count','int','','11','3','Gallery Bilder sichtbar','int','text-label');
$add_field('gallery_image_size','varchar','','80','original','Gallery Bildgroesse','*|max=80','text-label');
$add_field('gallery_lightbox_width','varchar','','80','100vw','Lightbox Breite','*|max=80','text-label');
$add_field('gallery_overflow','varchar','','80','grid','Gallery Overflow','*|max=80','text-label');
$add_field('gallery_click','varchar','','80','lightbox','Gallery Klick','*|max=80','text-label');
$add_field('attribute_notes','mediumtext','','-1','','Attribut-Hinweise','max=3000','textarea-label',array('data'=>'rows=3'));
$add_field('ebay_category_id','varchar','','160','','eBay Kategorie','text|max=160','text-label');
$add_field('amazon_product_type','varchar','','160','','Amazon Product Type','text|max=160','text-label');
$add_field('kleinanzeigen_category_id','varchar','','160','','Kleinanzeigen Kategorie','text|max=160','text-label');
$add_field('mobile_category_id','varchar','','160','','mobile.de Kategorie','text|max=160','text-label');
$add_field('active','int','MUL','1','1','Aktiv','int','checkbox-label');
$add_field('sorter','int','MUL','11','100','Sortierung','int','text-label');
?>
