<?php
$table['server']='dbxShop|dbxShop.db3';
$table['table']='shop_product';
$table['datadic']='shopProduct';
$table['primary']='id';
$table['language']='0';
$table['version']='0.1';
$table['autosync']='1';
$table['cache']='0';
$table['trash']='1';
$table['trace']='0';
$table['update_sql']='';
$table['default_sort']='sorter ASC, title ASC';
$table['form-dd-table']='';
$table['read']='*';
$table['create']='admin';
$table['update']='admin';
$table['delete']='admin';

$add_field = function($name, $type, $index, $length, $default, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']=$index;
   $field['length']=$length;
   $field['default']=$default;
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']=$extra['convert'] ?? '';
   $field['protect']=$extra['protect'] ?? '0';
   $field['group']=$extra['group'] ?? '';
   $field['mask']=$extra['mask'] ?? '';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $field['js']=$extra['js'] ?? '';
   $field['prompt']=$extra['prompt'] ?? '';
   $fields[]=$field;
};

$add_field('id','int','PRI','11','','ID','int','hidden');
$add_field('create_date','datetime','','-1','','Erstellt','datetime','hidden',array('convert'=>'date_time'));
$add_field('create_uid','int','MUL','11','0','Erstellt von','int','hidden');
$add_field('update_date','datetime','','-1','','Aktualisiert','datetime','hidden',array('convert'=>'date_time'));
$add_field('update_uid','int','MUL','11','0','Aktualisiert von','int','hidden');
$add_field('owner','int','MUL','11','0','Owner','int','hidden');
$add_field('trash','int','MUL','1','0','Trash','int','hidden');
$add_field('sku','varchar','UNI','80','','Artikelnummer','parameter|min=2|max=80','text-label');
$add_field('slug','varchar','UNI','120','','URL-Name','parameter|min=2|max=120','text-label');
$add_field('title','varchar','MUL','180','','Titel','*|min=2|max=180','text-label');
$add_field('category','varchar','MUL','80','','Kategorie','parameter|max=80','select-single-label',array('options'=>'Software=Software&Dienstleistung=Dienstleistung&Merchandise=Merchandise'));
$add_field('product_group_id','int','MUL','11','0','Artikelgruppe','int','select-single-label');
$add_field('product_type','varchar','MUL','24','service','Produkttyp','parameter|max=24','select-single-label',array('options'=>'digital=Digital&service=Dienstleistung&physical=Physisch'));
$add_field('summary','varchar','','255','','Kurzbeschreibung','*|max=255','textarea-label',array('data'=>'rows=2'));
$add_field('description','mediumtext','','-1','','Beschreibung','*|max=5000','textarea-label',array('data'=>'rows=6'));
$add_field('price_gross','decimal','','10,2','0','Bruttopreis','decimal','text-label');
$add_field('currency','varchar','','3','EUR','Waehrung','parameter|max=3','text-label');
$add_field('tax_mode','varchar','MUL','24','group','MwSt.-Quelle','parameter|max=24','select-single-label',array('options'=>'group=Aus Gruppe&individual=Individuell'));
$add_field('tax_rate','decimal','','5,2','-1','MwSt. % individuell','decimal','text-label');
$add_field('shipping_mode','varchar','MUL','24','group','Versand-Quelle','parameter|max=24','select-single-label',array('options'=>'group=Aus Gruppe&individual=Individuell'));
$add_field('shipping_gross','decimal','','10,2','-1','Versand brutto individuell','decimal','text-label');
$add_field('delivery_time','varchar','','120','','Lieferzeit individuell','*|max=120','text-label');
$add_field('stock','int','','11','0','Lagerbestand','int','text-label');
$add_field('active','int','MUL','1','1','Aktiv','int','checkbox-label');
$add_field('sorter','int','MUL','11','100','Sortierung','int','text-label');
$add_field('badge','varchar','','80','','Badge','*|max=80','text-label');
$add_field('image_icon','varchar','','80','bi-box-seam','Icon','parameter|max=80','text-label');
$add_field('logo_variant','varchar','','80','','Logo-Variante','parameter|max=80','text-label');
?>
