<?php
$table['server']='dbxShop|dbxShop.db3';
$table['table']='shop_channel';
$table['datadic']='shopChannel';
$table['primary']='id';
$table['language']='0';
$table['version']='0.1';
$table['autosync']='1';
$table['cache']='0';
$table['trash']='1';
$table['trace']='0';
$table['default_sort']='sorter ASC, title ASC';
$table['read']='*';
$table['create']='admin';
$table['update']='admin';
$table['delete']='admin';

$addField = function($name, $type, $index, $length, $default, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']=$index;
   $field['length']=$length;
   $field['default']=$default;
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']='';
   $field['errormsg']='';
   $field['placeholder']='';
   $field['convert']='';
   $field['protect']='0';
   $field['group']='';
   $field['mask']='';
   $field['data']='';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$addField('id','int','PRI','11','','ID','int','hidden');
$addField('create_date','datetime','','-1','','Erstellt','datetime','hidden',array('convert'=>'date_time'));
$addField('create_uid','int','','11','0','Erstellt von','int','hidden');
$addField('update_date','datetime','','-1','','Aktualisiert','datetime','hidden',array('convert'=>'date_time'));
$addField('update_uid','int','','11','0','Aktualisiert von','int','hidden');
$addField('owner','int','','11','0','Owner','int','hidden');
$addField('trash','int','','1','0','Trash','int','hidden');
$addField('channel_key','varchar','UNI','80','','Channel-Key','parameter|min=2|max=80','text-label');
$addField('title','varchar','MUL','160','','Name','*|min=2|max=160','text-label');
$addField('description','text','','-1','','Beschreibung','text','textarea-label');
$addField('platform_type','varchar','MUL','40','custom','Plattform','parameter|max=40','text-label');
$addField('connection_mode','varchar','MUL','40','manual','Verbindung','parameter|max=40','text-label');
$addField('api_base_url','varchar','','255','','API-Basis-URL','url|max=255','text-label');
$addField('api_client_id','varchar','','255','','Client-ID','text|max=255','text-label');
$addField('api_client_secret','text','','-1','','Client-Secret','text','password-label');
$addField('api_access_token','text','','-1','','Access-Token','text','password-label');
$addField('api_refresh_token','text','','-1','','Refresh-Token','text','password-label');
$addField('api_username','varchar','','160','','API-Benutzer','text|max=160','text-label');
$addField('api_password','text','','-1','','API-Passwort','text','password-label');
$addField('marketplace_id','varchar','','120','','Marketplace-ID','text|max=120','text-label');
$addField('seller_id','varchar','','160','','Seller-ID','text|max=160','text-label');
$addField('account_id','varchar','','160','','Account-ID','text|max=160','text-label');
$addField('location_key','varchar','','160','','Location-Key','text|max=160','text-label');
$addField('category_id','varchar','','160','','Kategorie-ID','text|max=160','text-label');
$addField('payment_policy_id','varchar','','160','','Payment-Policy','text|max=160','text-label');
$addField('fulfillment_policy_id','varchar','','160','','Fulfillment-Policy','text|max=160','text-label');
$addField('return_policy_id','varchar','','160','','Return-Policy','text|max=160','text-label');
$addField('notification_destination','varchar','','255','','Notification-Ziel','text|max=255','text-label');
$addField('notification_topic','varchar','','160','','Notification-Topic','text|max=160','text-label');
$addField('api_scope','text','','-1','','API-Scopes','text','textarea-label');
$addField('webhook_secret','text','','-1','','Webhook-Secret','text','password-label');
$addField('export_enabled','int','MUL','1','0','Export aktiv','int','checkbox-label');
$addField('order_import_enabled','int','MUL','1','0','Order-Import aktiv','int','checkbox-label');
$addField('test_status','varchar','','40','','Teststatus','text|max=40','text-label');
$addField('test_message','text','','-1','','Testmeldung','text','textarea-label');
$addField('last_test_date','datetime','','-1','','Letzter Test','datetime','text-label',array('convert'=>'date_time'));
$addField('active','int','MUL','1','1','Aktiv','int','checkbox-label');
$addField('sorter','int','MUL','11','100','Sortierung','int','text-label');
?>
