<?php
$table['server']='dbxShop|dbxShop.db3';
$table['table']='shop_order';
$table['datadic']='shopOrder';
$table['primary']='id';
$table['language']='0';
$table['version']='0.1';
$table['autosync']='1';
$table['cache']='0';
$table['trash']='1';
$table['trace']='0';
$table['default_sort']='create_date DESC';
$table['read']='admin';
$table['create']='*';
$table['update']='admin';
$table['delete']='admin';
$table['read_owner']='owner,admin';

$addField = function($name, $type, $index, $length, $default, $label, $rules, $tpl, $extra = array()) use (&$fields) {
   $field=array();
   $field['name']=$name;
   $field['type']=$type;
   $field['index']=$index;
   $field['length']=$length;
   $field['default']=$default;
   $field['label']=$label;
   $field['rules']=$rules;
   $field['tooltip']=$extra['tooltip'] ?? '';
   $field['errormsg']=$extra['errormsg'] ?? '';
   $field['placeholder']=$extra['placeholder'] ?? '';
   $field['convert']=$extra['convert'] ?? '';
   $field['protect']=$extra['protect'] ?? '0';
   $field['group']=$extra['group'] ?? '';
   $field['mask']=$extra['mask'] ?? '';
   $field['data']=$extra['data'] ?? '';
   $field['options']=$extra['options'] ?? '';
   $field['tpl']=$tpl;
   $fields[]=$field;
};

$addField('id','int','PRI','11','','ID','int','hidden');
$addField('create_date','datetime','MUL','-1','','Erstellt','datetime','hidden',array('convert'=>'date_time'));
$addField('create_uid','int','MUL','11','0','Erstellt von','int','hidden');
$addField('update_date','datetime','','-1','','Aktualisiert','datetime','hidden',array('convert'=>'date_time'));
$addField('update_uid','int','','11','0','Aktualisiert von','int','hidden');
$addField('owner','int','MUL','11','0','Owner','int','hidden');
$addField('trash','int','MUL','1','0','Trash','int','hidden');
$addField('order_no','varchar','UNI','40','','Bestellnummer','parameter|max=40','text-label');
$addField('uid','int','MUL','11','0','Benutzer','int','text-label');
$addField('status','varchar','MUL','24','new','Status','parameter|max=24','select-single-label',array('options'=>'new=Neu&payment_pending=Zahlung offen&paid=Bezahlt&processing=In Bearbeitung&shipped=Versendet&done=Abgeschlossen&cancelled=Storniert'));
$addField('customer_name','varchar','','180','','Name','*|max=180','text-label');
$addField('customer_email','varchar','','180','','E-Mail','email|max=180','text-label');
$addField('customer_phone','varchar','','80','','Telefon','text|max=80','text-label');
$addField('shipping_address','mediumtext','','-1','','Lieferadresse','*|max=2000','textarea-label',array('data'=>'rows=4'));
$addField('total_gross','decimal','','10,2','0','Summe brutto','number','text-label');
$addField('currency','varchar','','3','EUR','Waehrung','parameter|max=3','text-label');
$addField('channel_key','varchar','MUL','40','shop','Channel','parameter|max=40','text-label');
$addField('payment_provider','varchar','MUL','80','','Zahlungsanbieter','parameter|max=80','text-label');
$addField('payment_status','varchar','MUL','40','open','Zahlungsstatus','parameter|max=40','select-single-label',array('options'=>'open=Offen&created=Erstellt&processing=Wird verarbeitet&pending=In Pruefung&completed=Abgeschlossen&paid=Bezahlt&failed=Fehlgeschlagen&cancelled=Abgebrochen&refunded=Erstattet'));
$addField('payment_reference','varchar','MUL','180','','Zahlungsreferenz','parameter|max=180','text-label');
$addField('invoice_no','varchar','MUL','60','','Rechnungsnummer','parameter|max=60','text-label');
$addField('invoice_date','date','MUL','-1','','Rechnungsdatum','date','text-label',array('convert'=>'date'));
$addField('invoice_pdf_path','varchar','','255','','Rechnungs-PDF','parameter|max=255','text-label');
$addField('invoice_pdf_date','datetime','','-1','','PDF erstellt am','datetime','text-label',array('convert'=>'date_time'));
$addField('stock_reserved','int','MUL','1','0','Bestand reserviert','int','checkbox-label');
$addField('stock_released','int','MUL','1','0','Bestand zurueckgebucht','int','checkbox-label');
$addField('stock_released_date','datetime','','-1','','Bestand zurueckgebucht am','datetime','text-label',array('convert'=>'date_time'));
$addField('shipping_status','varchar','MUL','40','open','Versandstatus','parameter|max=40','select-single-label',array('options'=>'open=Offen&ready=Bereit&shipped=Versendet&delivered=Zugestellt&returned=Retoure'));
$addField('shipping_provider','varchar','','120','','Versanddienstleister','*|max=120','text-label');
$addField('tracking_no','varchar','MUL','180','','Trackingnummer','*|max=180','text-label');
$addField('tracking_url','varchar','','255','','Tracking-URL','url|max=255','text-label');
$addField('shipped_date','datetime','MUL','-1','','Versendet am','datetime','text-label',array('convert'=>'date_time'));
$addField('payment_payload','mediumtext','','-1','','Zahlungsdaten','*','textarea-label',array('data'=>'rows=6'));
$addField('legal_snapshot','mediumtext','','-1','','Rechtstext-Snapshot','*','textarea-label',array('data'=>'rows=6'));
$addField('withdrawal_snapshot','mediumtext','','-1','','Widerruf-Snapshot','*','textarea-label',array('data'=>'rows=6'));
$addField('note','mediumtext','','-1','','Notiz','*|max=5000','textarea-label',array('data'=>'rows=5'));
?>
