<?php
$messages = array();
$messages['save_success'] = 'Data was saved';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Data could not be saved';
$messages['dd_not_found'] = 'DD not found: {dd}.';
$messages['position_not_found'] = 'Field position not found: {position}.';
$messages['edit_new'] = 'Edit a new field for DD {dd}.';
$messages['edit_existing'] = 'Edit field {field}.';
$messages['field_saved'] = 'Field {field} was saved.';
$messages['field_save_error'] = 'Field {field} could not be saved.';
$messages['field_check'] = 'Please check field {field}.';
$messages['field_not_found'] = 'Field not found.';
$messages['field_deleted'] = 'Field deleted: {field}.';
$messages['field_delete_error'] = 'Field could not be deleted: {field}.';
$messages['invalid_field_name'] = 'Invalid field name: {field}.';
$messages['duplicate_field_name'] = 'Duplicate field name: {field}.';
$messages['invalid_order'] = 'Invalid order.';
$messages['order_saved'] = 'Field order was saved.';
$messages['order_save_error'] = 'Field order could not be saved.';
$messages['fd_module_missing'] = 'No module was specified.';
$messages['fd_not_found'] = 'FD not found: {fd}.';
$messages['fd_not_readable'] = 'FD not found or not readable: {fd}.';
$messages['fd_position_not_found'] = 'Field position not found: {position}.';
$messages['fd_frame_title'] = 'Edit FD: {fd}';
$messages['fd_edit_new'] = 'Edit a new field for FD {fd}.';
$messages['fd_edit_existing'] = 'Edit field {field}.';
$messages['fd_field_saved'] = 'Field {field} was saved in FD {fd}.';
$messages['fd_field_save_error'] = 'Field {field} could not be saved in FD {fd}.';
$messages['fd_field_check'] = 'Please check field {field}.';
$messages['fd_field_not_found'] = 'Field not found.';
$messages['fd_field_deleted'] = 'Field deleted: {field}.';
$messages['fd_field_delete_error'] = 'Field could not be deleted: {field}.';
$messages['fd_invalid_field_name'] = 'Invalid field name: {field}.';
$messages['fd_duplicate_field_name'] = 'Duplicate field name: {field}.';
$messages['fd_invalid_order'] = 'Invalid order.';
$messages['fd_order_saved'] = 'The FD field order was saved.';
$messages['fd_order_save_error'] = 'The FD field order could not be saved.';
$messages['create_info'] = 'Specify the complete source DD and target FD.';
$messages['label_source_module'] = 'Source module';
$messages['error_source_module'] = 'Enter a valid source module.';
$messages['label_source_dd'] = 'Source DD';
$messages['error_source_dd'] = 'Enter a valid source DD.';
$messages['label_target_module'] = 'Target module';
$messages['error_target_module'] = 'Enter a valid target module.';
$messages['label_target_fd'] = 'Target FD';
$messages['error_target_fd'] = 'Enter a valid target FD.';
$messages['label_overwrite'] = 'Overwrite existing FD file';
$messages['required_fields'] = 'Please check the required fields marked in red.';
$messages['target_exists_field'] = 'The FD already exists. Select the checkbox to overwrite it.';
$messages['target_exists'] = 'The target FD already exists.';
$messages['source_no_fields_field'] = 'The source DD has no field definitions or could not be read.';
$messages['source_invalid'] = 'The source DD could not be used.';
$messages['fd_created'] = 'FD {fd} was created from DD {dd}.';
$messages['edit_fd_action'] = 'Edit FD';
$messages['fd_write_error'] = 'The FD could not be written.';
$messages['fd_write_field_error'] = 'The FD file could not be written.';


/**
 * =========================================================
 * DBX ADMIN DDEDIT FIELD FD
 * =========================================================
 *
 * Felddefinitionen fuer das Bearbeiten einzelner $fields[]-Eintraege einer DD-Datei.
 * Die Feldreihenfolge selbst wird spaeter separat ueber dbxReport/Drag&Drop gespeichert.
 *
 * Verwendung:
 *   $oForm->_fd = 'dbxAdmin|<name-ohne-.fd.php>'; 
 *   $oForm->add_flds();
 *
 * Diese Datei liefert ausschliesslich Felddefinitionen fuer dbxForm.
 * Sie ist keine DB-DD-Datei und erzeugt keine DB-Struktur.
 */

$fields = array();

$field = array();
$field['name'] = 'modul';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'Module';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'dd';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'DD';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'field_pos';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '32';
$field['default'] = '';
$field['label'] = 'Position';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'old_name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Previous field name';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Field name';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = 'DBX-/DB field name. Must be clear.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'type';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '40';
$field['default'] = 'varchar';
$field['label'] = 'Field type';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   'varchar' => 'varchar',
   'char' => 'char',
   'text' => 'text',
   'mediumtext' => 'mediumtext',
   'longtext' => 'longtext',
   'int' => 'int',
   'integer' => 'integer',
   'bigint' => 'bigint',
   'smallint' => 'smallint',
   'mediumint' => 'mediumint',
   'tinyint' => 'tinyint',
   'decimal' => 'decimal',
   'float' => 'float',
   'double' => 'double',
   'date' => 'date',
   'datetime' => 'datetime',
   'timestamp' => 'timestamp',
   'time' => 'time',
   'bool' => 'bool',
   'boolean' => 'boolean',
   'json' => 'json',
   'blob' => 'blob',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'index';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '20';
$field['default'] = '';
$field['label'] = 'Index';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '' => 'no index',
   'PRI' => 'PRI / primary',
   'MUL' => 'MUL / multiple',
   'INDEX' => 'INDEX',
   'UNIQUE' => 'UNIQUE',
   'FULLTEXT' => 'FULLTEXT',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'length';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '32';
$field['default'] = '';
$field['label'] = 'Length';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '255';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'default';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Default';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'label';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Label';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'rules';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Rules';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = 'parameter';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'tooltip';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Tooltip';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'errormsg';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Error message';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'placeholder';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Placeholder';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'convert';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'Conversion';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'protect';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Protection';
$field['rules'] = 'int';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '0' => '0 / editable',
   '1' => '1 / protected',
   '2' => '2 / hidden',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'group';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Group';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'mask';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Mask';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'data';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Data';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'options';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Options';
$field['rules'] = 'text';
$field['tooltip'] = 'Options for selects, such as key=value&key2=value2 or own DBXConvention.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'tpl';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '120';
$field['default'] = '';
$field['label'] = 'Template';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '' => 'empty / default',
   'text-label' => 'text-label',
   'integer-label' => 'integer-label',
   'select-single-label' => 'select-single-label',
   'select-single' => 'select-single',
   'checkbox-label' => 'checkbox-label',
   'hidden' => 'hidden',
   'textarea-label' => 'textarea-label',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'js';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'JS';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'prompt';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Prompt';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;
