<?php
$messages = array();
$messages['dd_not_found'] = 'DD nicht gefunden: {dd}.';
$messages['position_not_found'] = 'Feldposition nicht gefunden: {position}.';
$messages['edit_new'] = 'Neues Feld für DD {dd} bearbeiten.';
$messages['edit_existing'] = 'Feld {field} bearbeiten.';
$messages['field_saved'] = 'Feld {field} wurde gespeichert.';
$messages['field_save_error'] = 'Feld {field} konnte nicht gespeichert werden.';
$messages['field_check'] = 'Bitte Feld {field} prüfen.';
$messages['field_not_found'] = 'Feld nicht gefunden.';
$messages['field_deleted'] = 'Feld gelöscht: {field}.';
$messages['field_delete_error'] = 'Feld konnte nicht gelöscht werden: {field}.';
$messages['invalid_field_name'] = 'Ungültiger Feldname: {field}.';
$messages['duplicate_field_name'] = 'Feldname doppelt: {field}.';
$messages['invalid_order'] = 'Ungültige Reihenfolge.';
$messages['order_saved'] = 'Feldreihenfolge wurde gespeichert.';
$messages['order_save_error'] = 'Feldreihenfolge konnte nicht gespeichert werden.';
$messages['fd_module_missing'] = 'Kein Modul angegeben.';
$messages['fd_not_found'] = 'FD nicht gefunden: {fd}.';
$messages['fd_not_readable'] = 'FD nicht gefunden oder nicht lesbar: {fd}.';
$messages['fd_position_not_found'] = 'Feldposition nicht gefunden: {position}.';
$messages['fd_frame_title'] = 'FD bearbeiten: {fd}';
$messages['fd_edit_new'] = 'Neues Feld für FD {fd} bearbeiten.';
$messages['fd_edit_existing'] = 'Feld {field} bearbeiten.';
$messages['fd_field_saved'] = 'Feld {field} wurde in FD {fd} gespeichert.';
$messages['fd_field_save_error'] = 'Feld {field} konnte in FD {fd} nicht gespeichert werden.';
$messages['fd_field_check'] = 'Bitte Feld {field} prüfen.';
$messages['fd_field_not_found'] = 'Feld nicht gefunden.';
$messages['fd_field_deleted'] = 'Feld gelöscht: {field}.';
$messages['fd_field_delete_error'] = 'Feld konnte nicht gelöscht werden: {field}.';
$messages['fd_invalid_field_name'] = 'Ungültiger Feldname: {field}.';
$messages['fd_duplicate_field_name'] = 'Feldname doppelt: {field}.';
$messages['fd_invalid_order'] = 'Ungültige Reihenfolge.';
$messages['fd_order_saved'] = 'FD-Feldreihenfolge wurde gespeichert.';
$messages['fd_order_save_error'] = 'FD-Feldreihenfolge konnte nicht gespeichert werden.';
$messages['create_info'] = 'Quell-DD und Ziel-FD vollständig angeben.';
$messages['label_source_module'] = 'Quell-Modul';
$messages['error_source_module'] = 'Bitte ein gültiges Quell-Modul angeben.';
$messages['label_source_dd'] = 'Quell-DD';
$messages['error_source_dd'] = 'Bitte eine gültige Quell-DD angeben.';
$messages['label_target_module'] = 'Ziel-Modul';
$messages['error_target_module'] = 'Bitte ein gültiges Ziel-Modul angeben.';
$messages['label_target_fd'] = 'Ziel-FD';
$messages['error_target_fd'] = 'Bitte eine gültige Ziel-FD angeben.';
$messages['label_overwrite'] = 'Bestehende FD-Datei überschreiben';
$messages['required_fields'] = 'Bitte die rot markierten Pflichtfelder prüfen.';
$messages['target_exists_field'] = 'Die FD existiert bereits. Zum Überschreiben bitte die Checkbox aktivieren.';
$messages['target_exists'] = 'Die Ziel-FD existiert bereits.';
$messages['source_no_fields_field'] = 'Die Quell-DD hat keine Felddefinitionen oder konnte nicht gelesen werden.';
$messages['source_invalid'] = 'Die Quell-DD konnte nicht verwendet werden.';
$messages['fd_created'] = 'FD {fd} wurde aus DD {dd} erstellt.';
$messages['edit_fd_action'] = 'FD bearbeiten';
$messages['fd_write_error'] = 'FD konnte nicht geschrieben werden.';
$messages['fd_write_field_error'] = 'Die FD-Datei konnte nicht geschrieben werden.';


/**
 * =========================================================
 * DBX ADMIN DDEDIT FIELD FD
 * =========================================================
 *
 * Felddefinitionen fuer das Bearbeiten einzelner $fields[]-Eintraege einer DD-Datei.
 * Die Feldreihenfolge selbst wird spaeter separat ueber dbxReport/Drag&Drop gespeichert.
 *
 * Verwendung:
 *   $oForm->_fd = 'dbxAdmin|<name-ohne-.fd.php>'; 
 *   $oForm->add_flds();
 *
 * Diese Datei liefert ausschliesslich Felddefinitionen fuer dbxForm.
 * Sie ist keine DB-DD-Datei und erzeugt keine DB-Struktur.
 */

$fields = array();

$field = array();
$field['name'] = 'modul';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'Modul';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'dd';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'DD';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'field_pos';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '32';
$field['default'] = '';
$field['label'] = 'Position';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'old_name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Alter Feldname';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Feldname';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = 'DBX-/DB-Feldname. Muss eindeutig sein.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'type';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '40';
$field['default'] = 'varchar';
$field['label'] = 'Feldtyp';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   'varchar' => 'varchar',
   'char' => 'char',
   'text' => 'text',
   'mediumtext' => 'mediumtext',
   'longtext' => 'longtext',
   'int' => 'int',
   'integer' => 'integer',
   'bigint' => 'bigint',
   'smallint' => 'smallint',
   'mediumint' => 'mediumint',
   'tinyint' => 'tinyint',
   'decimal' => 'decimal',
   'float' => 'float',
   'double' => 'double',
   'date' => 'date',
   'datetime' => 'datetime',
   'timestamp' => 'timestamp',
   'time' => 'time',
   'bool' => 'bool',
   'boolean' => 'boolean',
   'json' => 'json',
   'blob' => 'blob',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'index';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '20';
$field['default'] = '';
$field['label'] = 'Index';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '' => 'kein Index',
   'PRI' => 'PRI / Primaer',
   'MUL' => 'MUL / Mehrfach',
   'INDEX' => 'INDEX',
   'UNIQUE' => 'UNIQUE',
   'FULLTEXT' => 'FULLTEXT',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'length';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '32';
$field['default'] = '';
$field['label'] = 'Laenge';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '255';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'default';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Default';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'label';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Label';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'rules';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Regeln';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = 'parameter';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'tooltip';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Tooltip';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'errormsg';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Fehlermeldung';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'placeholder';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Placeholder';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'convert';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'Convert';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'protect';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Schutz';
$field['rules'] = 'int';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '0' => '0 / editierbar',
   '1' => '1 / geschuetzt',
   '2' => '2 / versteckt',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'group';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Gruppe';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'mask';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Maske';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'data';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Data';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'options';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Optionen';
$field['rules'] = 'text';
$field['tooltip'] = 'Optionen fuer Selects, z. B. key=value&key2=value2 oder eigene DBX-Konvention.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'tpl';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '120';
$field['default'] = '';
$field['label'] = 'Template';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '' => 'leer / Standard',
   'text-label' => 'text-label',
   'integer-label' => 'integer-label',
   'select-single-label' => 'select-single-label',
   'select-single' => 'select-single',
   'checkbox-label' => 'checkbox-label',
   'hidden' => 'hidden',
   'textarea-label' => 'textarea-label',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'js';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'JS';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'prompt';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Prompt';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;
