<?php
$messages = array();
$messages['dd_not_found'] = 'No se encontró el DD: {dd}.';
$messages['position_not_found'] = 'No se encontró la posición del campo: {position}.';
$messages['edit_new'] = 'Editar un campo nuevo para el DD {dd}.';
$messages['edit_existing'] = 'Editar el campo {field}.';
$messages['field_saved'] = 'Se guardó el campo {field}.';
$messages['field_save_error'] = 'No se pudo guardar el campo {field}.';
$messages['field_check'] = 'Compruebe el campo {field}.';
$messages['field_not_found'] = 'No se encontró el campo.';
$messages['field_deleted'] = 'Campo eliminado: {field}.';
$messages['field_delete_error'] = 'No se pudo eliminar el campo: {field}.';
$messages['invalid_field_name'] = 'Nombre de campo no válido: {field}.';
$messages['duplicate_field_name'] = 'Nombre de campo duplicado: {field}.';
$messages['invalid_order'] = 'El orden no es válido.';
$messages['order_saved'] = 'Se guardó el orden de los campos.';
$messages['order_save_error'] = 'No se pudo guardar el orden de los campos.';
$messages['fd_module_missing'] = 'No se ha indicado ningún módulo.';
$messages['fd_not_found'] = 'No se ha encontrado la FD: {fd}.';
$messages['fd_not_readable'] = 'No se ha encontrado la FD o no se puede leer: {fd}.';
$messages['fd_position_not_found'] = 'No se ha encontrado la posición del campo: {position}.';
$messages['fd_frame_title'] = 'Editar FD: {fd}';
$messages['fd_edit_new'] = 'Editar un campo nuevo para la FD {fd}.';
$messages['fd_edit_existing'] = 'Editar el campo {field}.';
$messages['fd_field_saved'] = 'El campo {field} se ha guardado en la FD {fd}.';
$messages['fd_field_save_error'] = 'No se ha podido guardar el campo {field} en la FD {fd}.';
$messages['fd_field_check'] = 'Compruebe el campo {field}.';
$messages['fd_field_not_found'] = 'No se ha encontrado el campo.';
$messages['fd_field_deleted'] = 'Campo eliminado: {field}.';
$messages['fd_field_delete_error'] = 'No se ha podido eliminar el campo: {field}.';
$messages['fd_invalid_field_name'] = 'Nombre de campo no válido: {field}.';
$messages['fd_duplicate_field_name'] = 'Nombre de campo duplicado: {field}.';
$messages['fd_invalid_order'] = 'El orden no es válido.';
$messages['fd_order_saved'] = 'Se ha guardado el orden de los campos de la FD.';
$messages['fd_order_save_error'] = 'No se ha podido guardar el orden de los campos de la FD.';
$messages['create_info'] = 'Indique la DD de origen y la FD de destino completas.';
$messages['label_source_module'] = 'Módulo de origen';
$messages['error_source_module'] = 'Introduzca un módulo de origen válido.';
$messages['label_source_dd'] = 'DD de origen';
$messages['error_source_dd'] = 'Introduzca una DD de origen válida.';
$messages['label_target_module'] = 'Módulo de destino';
$messages['error_target_module'] = 'Introduzca un módulo de destino válido.';
$messages['label_target_fd'] = 'FD de destino';
$messages['error_target_fd'] = 'Introduzca una FD de destino válida.';
$messages['label_overwrite'] = 'Sobrescribir el archivo FD existente';
$messages['required_fields'] = 'Compruebe los campos obligatorios marcados en rojo.';
$messages['target_exists_field'] = 'La FD ya existe. Active la casilla para sobrescribirla.';
$messages['target_exists'] = 'La FD de destino ya existe.';
$messages['source_no_fields_field'] = 'La DD de origen no contiene definiciones de campos o no se ha podido leer.';
$messages['source_invalid'] = 'No se ha podido utilizar la DD de origen.';
$messages['fd_created'] = 'La FD {fd} se ha creado a partir de la DD {dd}.';
$messages['edit_fd_action'] = 'Editar FD';
$messages['fd_write_error'] = 'No se ha podido escribir la FD.';
$messages['fd_write_field_error'] = 'No se ha podido escribir el archivo FD.';


/**
 * =========================================================
 * DBX ADMIN DDEDIT FIELD FD
 * =========================================================
 *
 * Felddefinitionen fuer das Bearbeiten einzelner $fields[]-Eintraege einer DD-Datei.
 * Die Feldreihenfolge selbst wird spaeter separat ueber dbxReport/Drag&Drop gespeichert.
 *
 * Verwendung:
 *   $oForm->_fd = 'dbxAdmin|<name-ohne-.fd.php>'; 
 *   $oForm->add_flds();
 *
 * Diese Datei liefert ausschliesslich Felddefinitionen fuer dbxForm.
 * Sie ist keine DB-DD-Datei und erzeugt keine DB-Struktur.
 */

$fields = array();

$field = array();
$field['name'] = 'modul';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'Módulo';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'dd';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'DD';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'field_pos';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '32';
$field['default'] = '';
$field['label'] = 'Posición';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'old_name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Nombre anterior del campo';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Nombre del campo';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = 'DBX-/DB nombre de campo. Debe ser claro.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'type';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '40';
$field['default'] = 'varchar';
$field['label'] = 'Tipo de campo';
$field['rules'] = 'parameter|min=1';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   'varchar' => 'varchar',
   'char' => 'char',
   'text' => 'text',
   'mediumtext' => 'mediumtext',
   'longtext' => 'longtext',
   'int' => 'int',
   'integer' => 'integer',
   'bigint' => 'bigint',
   'smallint' => 'smallint',
   'mediumint' => 'mediumint',
   'tinyint' => 'tinyint',
   'decimal' => 'decimal',
   'float' => 'float',
   'double' => 'double',
   'date' => 'date',
   'datetime' => 'datetime',
   'timestamp' => 'timestamp',
   'time' => 'time',
   'bool' => 'bool',
   'boolean' => 'boolean',
   'json' => 'json',
   'blob' => 'blob',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'index';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '20';
$field['default'] = '';
$field['label'] = 'Índice';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '' => 'sin índice',
   'PRI' => 'PRI / primario',
   'MUL' => 'MUL / múltiple',
   'INDEX' => 'INDEX',
   'UNIQUE' => 'UNIQUE',
   'FULLTEXT' => 'FULLTEXT',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'length';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '32';
$field['default'] = '';
$field['label'] = 'Longitud';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '255';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'default';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Valor predeterminado';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'label';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Etiqueta';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'rules';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Reglas';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = 'parameter';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'tooltip';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Descripción emergente';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'errormsg';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Mensaje de error';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'placeholder';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Marcador de posición';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'convert';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '80';
$field['default'] = '';
$field['label'] = 'Conversión';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'protect';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Protección';
$field['rules'] = 'int';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '0' => '0 / editable',
   '1' => '1 / protegido',
   '2' => '2 / oculto',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'group';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Grupo';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'mask';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '160';
$field['default'] = '';
$field['label'] = 'Máscara';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'data';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Datos';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'options';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Opciones';
$field['rules'] = 'text';
$field['tooltip'] = 'Opciones para seleccionar, tales como key=value ventaja2=value2 o propia DBXConvención.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'tpl';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '120';
$field['default'] = '';
$field['label'] = 'Plantilla';
$field['rules'] = 'parameter';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = array(
   '' => 'vacío / predeterminado',
   'text-label' => 'text-label',
   'integer-label' => 'integer-label',
   'select-single-label' => 'select-single-label',
   'select-single' => 'select-single',
   'checkbox-label' => 'checkbox-label',
   'hidden' => 'hidden',
   'textarea-label' => 'textarea-label',
);
$field['tpl'] = 'select-single-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'js';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'JS';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;

$field = array();
$field['name'] = 'prompt';
$field['type'] = 'varchar';
$field['index'] = '';
$field['length'] = '-1';
$field['default'] = '';
$field['label'] = 'Prompt';
$field['rules'] = 'text';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['convert'] = '';
$field['protect'] = '0';
$field['group'] = '';
$field['mask'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$field['js'] = '';
$field['prompt'] = '';
$fields[] = $field;
