<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['bar_title'] = 'Recursos ausentes';
$messages['bar_subtitle'] = 'Archivos y solicitudes que no se pudieron encontrar';
$messages['column_created'] = 'Creado';
$messages['column_updated'] = 'Actualizado';
$messages['column_count'] = 'Cantidad';
$messages['column_missing'] = 'Recurso ausente';
$messages['column_request'] = 'Página solicitante';
$messages['row_delete_success'] = 'Se eliminó la entrada.';
$messages['row_delete_error'] = 'No se pudo eliminar la entrada.';
$messages['delete_tab_success'] = 'Se vació la tabla de recursos ausentes.';
$messages['delete_tab_error'] = 'No se pudo vaciar la tabla de recursos ausentes.';
$messages['validation_error'] = 'Revise los datos introducidos.';
$messages['delete_tab_label'] = 'Vaciar entradas';
$messages['delete_tab_title'] = 'Vaciar tabla';
$messages['delete_tab_confirm'] = '¿Desea realmente eliminar todas las entradas de recursos ausentes?';
$messages['delete_tab_tooltip'] = 'Eliminar todas las entradas de recursos ausentes';
$messages['action_delete_selected'] = 'Eliminar seleccionadas';
$messages['multi_delete_one'] = 'Se eliminó 1 entrada.';
$messages['multi_delete_many'] = 'Se eliminaron {count} entradas.';
$messages['multi_delete_partial'] = 'Se eliminaron {deleted} entradas; {failed} fallaron.';
$messages['multi_delete_failed'] = 'No se pudieron eliminar las entradas.';
$messages['report_action_confirm_title'] = 'Confirmar acción';

// Report Formular fuer die Missing Tabelle im dbxAdmin Modul.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Por página';
$field['rules']='int';
$field['tooltip']='Número por página';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=Todos';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='update_date';
$field['label']='Orden';
$field['rules']='parameter';
$field['tooltip']='Orden de clasificación';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&count=Cantidad&update_date=Actualizado&create_date=Creado&missing=Recurso ausente';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Dirección';
$field['rules']='parameter';
$field['tooltip']='Orden ascendente o descendente';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Ascendente&DESC=Descendente';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Búsqueda';
$field['rules']='sqlsearch';
$field['tooltip']='Datos de búsqueda';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Seleccionado';
$field['rules']='int';
$field['tooltip']='Mostrar conjuntos de datos seleccionados';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=Todos&1=Seleccionado';
$fields[]=$field;
