<?php
$messages = array();
$messages['save_success'] = 'Daten wurden gespeichert';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Daten konnten nicht gespeichert werden';
$messages['bar_title'] = 'Fehlende Ressourcen';
$messages['bar_subtitle'] = 'Nicht gefundene Dateien und Aufrufe';
$messages['column_created'] = 'Erstellt';
$messages['column_updated'] = 'Aktualisiert';
$messages['column_count'] = 'Anzahl';
$messages['column_missing'] = 'Fehlende Ressource';
$messages['column_request'] = 'Aufrufende Seite';
$messages['row_delete_success'] = 'Eintrag gelöscht.';
$messages['row_delete_error'] = 'Eintrag konnte nicht gelöscht werden.';
$messages['delete_tab_success'] = 'Tabelle der fehlenden Ressourcen geleert.';
$messages['delete_tab_error'] = 'Tabelle der fehlenden Ressourcen konnte nicht geleert werden.';
$messages['validation_error'] = 'Bitte prüfen Sie die Eingaben.';
$messages['delete_tab_label'] = 'Einträge leeren';
$messages['delete_tab_title'] = 'Tabelle leeren';
$messages['delete_tab_confirm'] = 'Wirklich alle Einträge zu fehlenden Ressourcen löschen?';
$messages['delete_tab_tooltip'] = 'Alle Einträge zu fehlenden Ressourcen löschen';
$messages['action_delete_selected'] = 'Ausgewählte löschen';
$messages['multi_delete_one'] = '1 Eintrag gelöscht.';
$messages['multi_delete_many'] = '{count} Einträge gelöscht.';
$messages['multi_delete_partial'] = '{deleted} Einträge gelöscht, {failed} fehlgeschlagen.';
$messages['multi_delete_failed'] = 'Einträge konnten nicht gelöscht werden.';
$messages['report_action_confirm_title'] = 'Aktion bestätigen';

// Report Formular fuer die Missing Tabelle im dbxAdmin Modul.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Pro Seite';
$field['rules']='int';
$field['tooltip']='Anzahl je Seite';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=alle';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='update_date';
$field['label']='Sortierung';
$field['rules']='parameter';
$field['tooltip']='Sortierreihenfolge';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&count=Count&update_date=Update&create_date=Create&missing=Missing';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Auf/Ab';
$field['rules']='parameter';
$field['tooltip']='Aufsteigend oder Absteigend';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Aufsteigend&DESC=Absteigend';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Suchen';
$field['rules']='sqlsearch';
$field['tooltip']='Daten durchsuchen';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Ausgewaehlte';
$field['rules']='int';
$field['tooltip']='Ausgewaehlte Datensaetze anzeigen';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=Alle&1=Ausgewaehlte';
$fields[]=$field;
