<?php
$messages = array();
$messages['bar_title'] = 'Trace / Historie';
$messages['bar_subtitle'] = 'Änderungshistorie';
$messages['column_created'] = 'Erstellt';
$messages['column_action'] = 'Aktion';
$messages['column_dd'] = 'DD';
$messages['column_record'] = 'Datensatz';
$messages['column_owner'] = 'Eigentümer';
$messages['column_change'] = 'Änderung';
$messages['row_delete_success'] = 'Zeile gelöscht.';
$messages['row_delete_error'] = 'Zeile konnte nicht gelöscht werden.';
$messages['delete_tab_success'] = 'Datenbank-Tabelle geleert und optimiert.';
$messages['delete_tab_partial'] = 'Datenbank-Tabelle geleert. Die Optimierung konnte nicht ausgeführt werden.';
$messages['delete_tab_error'] = 'Datenbank-Tabelle konnte nicht geleert werden.';
$messages['validation_error'] = 'Bitte prüfen Sie die Eingaben.';
$messages['delete_tab_label'] = 'Tabelle leeren';
$messages['delete_tab_title'] = 'Trace-Tabelle leeren';
$messages['delete_tab_confirm'] = 'Die komplette Trace-Tabelle wirklich leeren?';
$messages['delete_tab_tooltip'] = 'Datenbank-Tabelle leeren';
$messages['action_delete_selected'] = 'Ausgewählte löschen';
$messages['multi_delete_one'] = '1 Datensatz gelöscht.';
$messages['multi_delete_many'] = '{count} Datensätze gelöscht.';
$messages['multi_delete_partial'] = '{deleted} Datensätze gelöscht, {failed} fehlgeschlagen.';
$messages['multi_delete_failed'] = 'Löschen fehlgeschlagen.';
$messages['report_action_confirm_title'] = 'Aktion bestätigen';

// Report Formular fuer dbxTrace.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Anz.Seite';
$field['rules']='int';
$field['tooltip']='Anzahl je Seite';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=alle';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='create_date';
$field['label']='Sortierung';
$field['rules']='parameter';
$field['tooltip']='Sortierreihenfolge';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&create_date=Create&action=Action&dd=DD&record_id=Record&owner=Owner';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Auf/Ab';
$field['rules']='parameter';
$field['tooltip']='Aufsteigend oder Absteigend';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Aufsteigend&DESC=Absteigend';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Suchen';
$field['rules']='sqlsearch';
$field['tooltip']='Daten durchsuchen';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Ausgewaehlte';
$field['rules']='int';
$field['tooltip']='Ausgewaehlte Datensaetze anzeigen';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=Alle&1=Ausgewaehlte';
$fields[]=$field;
