<?php
$messages = array();
$messages['bar_title'] = 'System messages';
$messages['bar_subtitle'] = 'Application log and error log';
$messages['column_created'] = 'Created';
$messages['column_level'] = 'Level';
$messages['column_status'] = 'Status';
$messages['column_context'] = 'Context';
$messages['column_module'] = 'Module';
$messages['column_action'] = 'Action';
$messages['column_process'] = 'Process';
$messages['column_user'] = 'User';
$messages['column_message'] = 'Message';
$messages['row_delete_success'] = 'The message was deleted.';
$messages['row_delete_error'] = 'The message could not be deleted.';
$messages['delete_tab_success'] = 'The message table was emptied.';
$messages['delete_tab_error'] = 'The message table could not be emptied.';
$messages['error_log_empty'] = 'The PHP error log is already empty.';
$messages['error_log_deleted'] = 'The PHP error log was deleted.';
$messages['error_log_delete_error'] = 'The PHP error log could not be deleted.';
$messages['validation_error'] = 'Please check your entries.';
$messages['level_error_only'] = 'Errors only';
$messages['level_error_warning'] = 'Errors and warnings';
$messages['level_all'] = 'All messages';
$messages['delete_tab_label'] = 'Clear messages';
$messages['delete_tab_title'] = 'Empty message table';
$messages['delete_tab_confirm'] = 'Do you really want to delete all system messages?';
$messages['delete_tab_tooltip'] = 'Delete all system messages';
$messages['action_delete_selected'] = 'Delete selected';
$messages['multi_delete_one'] = '1 message was deleted.';
$messages['multi_delete_many'] = '{count} messages were deleted.';
$messages['multi_delete_partial'] = '{deleted} messages were deleted; {failed} failed.';
$messages['multi_delete_failed'] = 'The messages could not be deleted.';
$messages['report_action_confirm_title'] = 'Confirm action';

// Report Formular fuer dbxSysMsg.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Per page';
$field['rules']='int';
$field['tooltip']='Number per page';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=all';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='create_date';
$field['label']='Sorting';
$field['rules']='parameter';
$field['tooltip']='Sorting order';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&create_date=Created&level=Level&status=Status&about=Context&modul=Module&action=Action&work=Process&xuser=User';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Direction';
$field['rules']='parameter';
$field['tooltip']='Ascending or descending';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Ascending&DESC=Descending';
$fields[]=$field;

$field['name']='dbx_rstatus';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='16';
$field['default']='';
$field['label']='Type';
$field['rules']='parameter';
$field['tooltip']='Filter message type';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='all=All&debug=Debug&info=Info&login=Login&notice=Notice&warning=Warning&security=Security&error=Error&fatal=Fatal';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Search';
$field['rules']='sqlsearch';
$field['tooltip']='Search data';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Selected';
$field['rules']='int';
$field['tooltip']='Show selected datasets';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=All&1=Selected';
$fields[]=$field;
