<?php
$messages = array();
$messages['bar_title'] = 'System-Meldungen';
$messages['bar_subtitle'] = 'Log und Fehlerprotokoll';
$messages['column_created'] = 'Erstellt';
$messages['column_level'] = 'Stufe';
$messages['column_status'] = 'Status';
$messages['column_context'] = 'Bereich';
$messages['column_module'] = 'Modul';
$messages['column_action'] = 'Aktion';
$messages['column_process'] = 'Vorgang';
$messages['column_user'] = 'Benutzer';
$messages['column_message'] = 'Meldung';
$messages['row_delete_success'] = 'Meldung gelöscht.';
$messages['row_delete_error'] = 'Meldung konnte nicht gelöscht werden.';
$messages['delete_tab_success'] = 'Meldungstabelle geleert.';
$messages['delete_tab_error'] = 'Meldungstabelle konnte nicht geleert werden.';
$messages['error_log_empty'] = 'Das PHP-Fehlerprotokoll ist bereits leer.';
$messages['error_log_deleted'] = 'Das PHP-Fehlerprotokoll wurde gelöscht.';
$messages['error_log_delete_error'] = 'Das PHP-Fehlerprotokoll konnte nicht gelöscht werden.';
$messages['validation_error'] = 'Bitte prüfen Sie die Eingaben.';
$messages['level_error_only'] = 'Nur Fehler';
$messages['level_error_warning'] = 'Fehler und Warnungen';
$messages['level_all'] = 'Alle Meldungen';
$messages['delete_tab_label'] = 'Meldungen leeren';
$messages['delete_tab_title'] = 'Meldungstabelle leeren';
$messages['delete_tab_confirm'] = 'Wirklich alle System-Meldungen löschen?';
$messages['delete_tab_tooltip'] = 'Alle System-Meldungen löschen';
$messages['action_delete_selected'] = 'Ausgewählte löschen';
$messages['multi_delete_one'] = '1 Meldung gelöscht.';
$messages['multi_delete_many'] = '{count} Meldungen gelöscht.';
$messages['multi_delete_partial'] = '{deleted} Meldungen gelöscht, {failed} fehlgeschlagen.';
$messages['multi_delete_failed'] = 'Meldungen konnten nicht gelöscht werden.';
$messages['report_action_confirm_title'] = 'Aktion bestätigen';

// Report Formular fuer dbxSysMsg.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Pro Seite';
$field['rules']='int';
$field['tooltip']='Anzahl je Seite';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=alle';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='create_date';
$field['label']='Sortierung';
$field['rules']='parameter';
$field['tooltip']='Sortierreihenfolge';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&create_date=Create&level=Level&status=Status&about=Bereich&modul=Modul&action=Action&work=Work&xuser=User';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Auf/Ab';
$field['rules']='parameter';
$field['tooltip']='Aufsteigend oder Absteigend';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Aufsteigend&DESC=Absteigend';
$fields[]=$field;

$field['name']='dbx_rstatus';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='16';
$field['default']='';
$field['label']='Art';
$field['rules']='parameter';
$field['tooltip']='Meldungsart filtern';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='all=Alle&debug=Debug&info=Info&login=Login&notice=Notice&warning=Warning&security=Security&error=Error&fatal=Fatal';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Suchen';
$field['rules']='sqlsearch';
$field['tooltip']='Daten durchsuchen';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Ausgewaehlte';
$field['rules']='int';
$field['tooltip']='Ausgewaehlte Datensaetze anzeigen';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=Alle&1=Ausgewaehlte';
$fields[]=$field;
