<?php
$messages = array();
$messages['bar_title'] = 'Missing resources';
$messages['bar_subtitle'] = 'Files and requests that could not be found';
$messages['column_created'] = 'Created';
$messages['column_updated'] = 'Updated';
$messages['column_count'] = 'Count';
$messages['column_missing'] = 'Missing resource';
$messages['column_request'] = 'Requesting page';
$messages['row_delete_success'] = 'The entry was deleted.';
$messages['row_delete_error'] = 'The entry could not be deleted.';
$messages['delete_tab_success'] = 'The missing-resources table was emptied.';
$messages['delete_tab_error'] = 'The missing-resources table could not be emptied.';
$messages['validation_error'] = 'Please check your entries.';
$messages['delete_tab_label'] = 'Clear entries';
$messages['delete_tab_title'] = 'Empty table';
$messages['delete_tab_confirm'] = 'Do you really want to delete all missing-resource entries?';
$messages['delete_tab_tooltip'] = 'Delete all missing-resource entries';
$messages['action_delete_selected'] = 'Delete selected';
$messages['multi_delete_one'] = '1 entry was deleted.';
$messages['multi_delete_many'] = '{count} entries were deleted.';
$messages['multi_delete_partial'] = '{deleted} entries were deleted; {failed} failed.';
$messages['multi_delete_failed'] = 'The entries could not be deleted.';
$messages['report_action_confirm_title'] = 'Confirm action';

// Report Formular fuer die Missing Tabelle im dbxAdmin Modul.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Per page';
$field['rules']='int';
$field['tooltip']='Number per page';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=all';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='update_date';
$field['label']='Sorting';
$field['rules']='parameter';
$field['tooltip']='Sorting order';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&count=Count&update_date=Updated&create_date=Created&missing=Missing resource';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Direction';
$field['rules']='parameter';
$field['tooltip']='Ascending or descending';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Ascending&DESC=Descending';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Search';
$field['rules']='sqlsearch';
$field['tooltip']='Search data';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Selected';
$field['rules']='int';
$field['tooltip']='Show selected datasets';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=All&1=Selected';
$fields[]=$field;
