<?php
$messages = array();
$messages['bar_title'] = 'Traza / Historial';
$messages['bar_subtitle'] = 'Historial de cambios';
$messages['column_created'] = 'Creado';
$messages['column_action'] = 'Acción';
$messages['column_dd'] = 'DD';
$messages['column_record'] = 'Registro';
$messages['column_owner'] = 'Propietario';
$messages['column_change'] = 'Cambio';
$messages['row_delete_success'] = 'Se eliminó la fila.';
$messages['row_delete_error'] = 'No se pudo eliminar la fila.';
$messages['delete_tab_success'] = 'La tabla de la base de datos se vació y optimizó.';
$messages['delete_tab_partial'] = 'La tabla de la base de datos se vació. No se pudo completar la optimización.';
$messages['delete_tab_error'] = 'No se pudo vaciar la tabla de la base de datos.';
$messages['validation_error'] = 'Revise los datos introducidos.';
$messages['delete_tab_label'] = 'Vaciar tabla';
$messages['delete_tab_title'] = 'Vaciar tabla de trazas';
$messages['delete_tab_confirm'] = '¿Desea realmente vaciar toda la tabla de trazas?';
$messages['delete_tab_tooltip'] = 'Vaciar tabla de la base de datos';
$messages['action_delete_selected'] = 'Eliminar seleccionados';
$messages['multi_delete_one'] = 'Se eliminó 1 registro.';
$messages['multi_delete_many'] = 'Se eliminaron {count} registros.';
$messages['multi_delete_partial'] = 'Se eliminaron {deleted} registros; {failed} fallaron.';
$messages['multi_delete_failed'] = 'La eliminación falló.';
$messages['report_action_confirm_title'] = 'Confirmar acción';

// Report Formular fuer dbxTrace.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Número';
$field['rules']='int';
$field['tooltip']='Número por página';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=Todos';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='create_date';
$field['label']='Orden';
$field['rules']='parameter';
$field['tooltip']='Orden de clasificación';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&create_date=Creado&action=Acción&dd=DD&record_id=Registro&owner=Propietario';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Dirección';
$field['rules']='parameter';
$field['tooltip']='Orden ascendente o descendente';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Ascendente&DESC=Descendente';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Búsqueda';
$field['rules']='sqlsearch';
$field['tooltip']='Datos de búsqueda';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Seleccionado';
$field['rules']='int';
$field['tooltip']='Mostrar conjuntos de datos seleccionados';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=Todos&1=Seleccionado';
$fields[]=$field;
