<?php
$messages = array();
$messages['bar_title'] = 'Sessions';
$messages['bar_subtitle'] = 'Aktive und gespeicherte Sitzungen';
$messages['column_access'] = 'Zugriff';
$messages['column_user'] = 'Benutzer';
$messages['column_ip'] = 'IP';
$messages['column_design'] = 'Design';
$messages['column_page'] = 'Seite';
$messages['column_module'] = 'Modul';
$messages['column_edit'] = 'Bearbeiten';
$messages['column_color'] = 'Farbe';
$messages['column_language'] = 'Sprache';
$messages['column_requests'] = 'Aufrufe';
$messages['row_delete_success'] = 'Session gelöscht.';
$messages['row_delete_error'] = 'Session konnte nicht gelöscht werden.';
$messages['delete_tab_success'] = 'Session-Tabelle geleert.';
$messages['delete_tab_error'] = 'Session-Tabelle konnte nicht geleert werden.';
$messages['validation_error'] = 'Bitte prüfen Sie die Eingaben.';
$messages['delete_tab_label'] = 'Sessions leeren';
$messages['delete_tab_title'] = 'Session-Tabelle leeren';
$messages['delete_tab_confirm'] = 'Wirklich alle gespeicherten Sessions löschen?';
$messages['delete_tab_tooltip'] = 'Alle gespeicherten Sessions löschen';
$messages['action_delete_selected'] = 'Ausgewählte löschen';
$messages['multi_delete_one'] = '1 Session gelöscht.';
$messages['multi_delete_many'] = '{count} Sessions gelöscht.';
$messages['multi_delete_partial'] = '{deleted} Sessions gelöscht, {failed} fehlgeschlagen.';
$messages['multi_delete_failed'] = 'Sessions konnten nicht gelöscht werden.';
$messages['report_action_confirm_title'] = 'Aktion bestätigen';

// Report Formular für die Session Tabelle in dbxAdmin Modul Auswahl der Spalten, Sortierung, Anzahl je Seite, Suche, etc.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='10';
$field['label']='Pro Seite';
$field['rules']='int';
$field['tooltip']='Anzahl je Seite';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=alle';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='id';
$field['label']='Sortierung';
$field['rules']='sqlsearch';
$field['tooltip']='Sortierreihenfolge';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=id&userid=Benutzer&modul=Modul&run1=Run1&run2=Run2&request_counter=Zugriffe&update_date=Zugriff';
$fields[]=$field;


$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Auf/Ab';
$field['rules']='parameter';
$field['tooltip']='Aufsteigend oder Absteigend';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Aufsteigend&DESC=Absteigend';
$fields[]=$field;


$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='32';
$field['default']='';
$field['label']='Suchen';
$field['rules']='parameter';
$field['tooltip']='Daten durchsuchen';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Ausgewählte';
$field['rules']='parameter';
$field['tooltip']='Ausgewählte Datensätze anzeigen';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=Alle&1=Ausgewählte';
$fields[]=$field;
