<?php
$messages = array();
$messages['bar_title'] = 'Sessions';
$messages['bar_subtitle'] = 'Active and stored sessions';
$messages['column_access'] = 'Last access';
$messages['column_user'] = 'User';
$messages['column_ip'] = 'IP';
$messages['column_design'] = 'Design';
$messages['column_page'] = 'Page';
$messages['column_module'] = 'Module';
$messages['column_edit'] = 'Edit mode';
$messages['column_color'] = 'Color';
$messages['column_language'] = 'Language';
$messages['column_requests'] = 'Requests';
$messages['row_delete_success'] = 'The session was deleted.';
$messages['row_delete_error'] = 'The session could not be deleted.';
$messages['delete_tab_success'] = 'The session table was emptied.';
$messages['delete_tab_error'] = 'The session table could not be emptied.';
$messages['validation_error'] = 'Please check your entries.';
$messages['delete_tab_label'] = 'Clear sessions';
$messages['delete_tab_title'] = 'Empty session table';
$messages['delete_tab_confirm'] = 'Do you really want to delete all stored sessions?';
$messages['delete_tab_tooltip'] = 'Delete all stored sessions';
$messages['action_delete_selected'] = 'Delete selected';
$messages['multi_delete_one'] = '1 session was deleted.';
$messages['multi_delete_many'] = '{count} sessions were deleted.';
$messages['multi_delete_partial'] = '{deleted} sessions were deleted; {failed} failed.';
$messages['multi_delete_failed'] = 'The sessions could not be deleted.';
$messages['report_action_confirm_title'] = 'Confirm action';

// Report Formular für die Session Tabelle in dbxAdmin Modul Auswahl der Spalten, Sortierung, Anzahl je Seite, Suche, etc.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='10';
$field['label']='Per page';
$field['rules']='int';
$field['tooltip']='Number per page';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=all';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='id';
$field['label']='Sorting';
$field['rules']='sqlsearch';
$field['tooltip']='Sorting order';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&userid=User&modul=Module&run1=Run1&run2=Run2&request_counter=Requests&update_date=Last access';
$fields[]=$field;


$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Direction';
$field['rules']='parameter';
$field['tooltip']='Ascending or descending';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Ascending&DESC=Descending';
$fields[]=$field;


$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='32';
$field['default']='';
$field['label']='Search';
$field['rules']='parameter';
$field['tooltip']='Search data';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Selected';
$field['rules']='parameter';
$field['tooltip']='Show selected records';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=All&1=Selected';
$fields[]=$field;
