<?php
$messages = array();
$messages['bar_title'] = 'Mensajes del sistema';
$messages['bar_subtitle'] = 'Registro de la aplicación y registro de errores';
$messages['column_created'] = 'Creado';
$messages['column_level'] = 'Nivel';
$messages['column_status'] = 'Estado';
$messages['column_context'] = 'Contexto';
$messages['column_module'] = 'Módulo';
$messages['column_action'] = 'Acción';
$messages['column_process'] = 'Proceso';
$messages['column_user'] = 'Usuario';
$messages['column_message'] = 'Mensaje';
$messages['row_delete_success'] = 'Se eliminó el mensaje.';
$messages['row_delete_error'] = 'No se pudo eliminar el mensaje.';
$messages['delete_tab_success'] = 'Se vació la tabla de mensajes.';
$messages['delete_tab_error'] = 'No se pudo vaciar la tabla de mensajes.';
$messages['error_log_empty'] = 'El registro de errores de PHP ya está vacío.';
$messages['error_log_deleted'] = 'Se eliminó el registro de errores de PHP.';
$messages['error_log_delete_error'] = 'No se pudo eliminar el registro de errores de PHP.';
$messages['validation_error'] = 'Revise los datos introducidos.';
$messages['level_error_only'] = 'Solo errores';
$messages['level_error_warning'] = 'Errores y advertencias';
$messages['level_all'] = 'Todos los mensajes';
$messages['delete_tab_label'] = 'Vaciar mensajes';
$messages['delete_tab_title'] = 'Vaciar tabla de mensajes';
$messages['delete_tab_confirm'] = '¿Desea realmente eliminar todos los mensajes del sistema?';
$messages['delete_tab_tooltip'] = 'Eliminar todos los mensajes del sistema';
$messages['action_delete_selected'] = 'Eliminar seleccionados';
$messages['multi_delete_one'] = 'Se eliminó 1 mensaje.';
$messages['multi_delete_many'] = 'Se eliminaron {count} mensajes.';
$messages['multi_delete_partial'] = 'Se eliminaron {deleted} mensajes; {failed} fallaron.';
$messages['multi_delete_failed'] = 'No se pudieron eliminar los mensajes.';
$messages['report_action_confirm_title'] = 'Confirmar acción';

// Report Formular fuer dbxSysMsg.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Por página';
$field['rules']='int';
$field['tooltip']='Número por página';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=Todos';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='create_date';
$field['label']='Orden';
$field['rules']='parameter';
$field['tooltip']='Orden de clasificación';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&create_date=Creado&level=Nivel&status=Estado&about=Contexto&modul=Módulo&action=Acción&work=Proceso&xuser=Usuario';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Dirección';
$field['rules']='parameter';
$field['tooltip']='Orden ascendente o descendente';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Ascendente&DESC=Descendente';
$fields[]=$field;

$field['name']='dbx_rstatus';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='16';
$field['default']='';
$field['label']='Tipo';
$field['rules']='parameter';
$field['tooltip']='Tipo de mensaje de filtro';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='all=Todos&debug=Debug&info=Info&login=Iniciar sesión&notice=Aviso&warning=Advertencia&security=Seguridad&error=Error&fatal=Fatal';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Búsqueda';
$field['rules']='sqlsearch';
$field['tooltip']='Datos de búsqueda';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Seleccionado';
$field['rules']='int';
$field['tooltip']='Mostrar conjuntos de datos seleccionados';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=Todos&1=Seleccionado';
$fields[]=$field;
