<?php
$messages = array();
$messages['bar_title'] = 'Trace / History';
$messages['bar_subtitle'] = 'Change history';
$messages['column_created'] = 'Created';
$messages['column_action'] = 'Action';
$messages['column_dd'] = 'DD';
$messages['column_record'] = 'Record';
$messages['column_owner'] = 'Owner';
$messages['column_change'] = 'Change';
$messages['row_delete_success'] = 'The row was deleted.';
$messages['row_delete_error'] = 'The row could not be deleted.';
$messages['delete_tab_success'] = 'The database table was emptied and optimized.';
$messages['delete_tab_partial'] = 'The database table was emptied. Optimization could not be completed.';
$messages['delete_tab_error'] = 'The database table could not be emptied.';
$messages['validation_error'] = 'Please check your entries.';
$messages['delete_tab_label'] = 'Empty table';
$messages['delete_tab_title'] = 'Empty trace table';
$messages['delete_tab_confirm'] = 'Do you really want to empty the complete trace table?';
$messages['delete_tab_tooltip'] = 'Empty database table';
$messages['action_delete_selected'] = 'Delete selected';
$messages['multi_delete_one'] = '1 record was deleted.';
$messages['multi_delete_many'] = '{count} records were deleted.';
$messages['multi_delete_partial'] = '{deleted} records were deleted; {failed} failed.';
$messages['multi_delete_failed'] = 'Deletion failed.';
$messages['report_action_confirm_title'] = 'Confirm action';

// Report Formular fuer dbxTrace.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='15';
$field['label']='Number';
$field['rules']='int';
$field['tooltip']='Number per page';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=all';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='32';
$field['default']='create_date';
$field['label']='Sorting';
$field['rules']='parameter';
$field['tooltip']='Sorting order';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&create_date=Created&action=Action&dd=DD&record_id=Record&owner=Owner';
$fields[]=$field;

$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Direction';
$field['rules']='parameter';
$field['tooltip']='Ascending or descending';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Ascending&DESC=Descending';
$fields[]=$field;

$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='64';
$field['default']='';
$field['label']='Search';
$field['rules']='sqlsearch';
$field['tooltip']='Search data';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Selected';
$field['rules']='int';
$field['tooltip']='Show selected datasets';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=All&1=Selected';
$fields[]=$field;
