<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['bar_title'] = 'Sesiones';
$messages['bar_subtitle'] = 'Sesiones activas y guardadas';
$messages['column_access'] = 'Último acceso';
$messages['column_user'] = 'Usuario';
$messages['column_ip'] = 'IP';
$messages['column_design'] = 'Diseño';
$messages['column_page'] = 'Página';
$messages['column_module'] = 'Módulo';
$messages['column_edit'] = 'Modo de edición';
$messages['column_color'] = 'Color';
$messages['column_language'] = 'Idioma';
$messages['column_requests'] = 'Solicitudes';
$messages['row_delete_success'] = 'Se eliminó la sesión.';
$messages['row_delete_error'] = 'No se pudo eliminar la sesión.';
$messages['delete_tab_success'] = 'Se vació la tabla de sesiones.';
$messages['delete_tab_error'] = 'No se pudo vaciar la tabla de sesiones.';
$messages['validation_error'] = 'Revise los datos introducidos.';
$messages['delete_tab_label'] = 'Vaciar sesiones';
$messages['delete_tab_title'] = 'Vaciar tabla de sesiones';
$messages['delete_tab_confirm'] = '¿Desea realmente eliminar todas las sesiones guardadas?';
$messages['delete_tab_tooltip'] = 'Eliminar todas las sesiones guardadas';
$messages['action_delete_selected'] = 'Eliminar seleccionadas';
$messages['multi_delete_one'] = 'Se eliminó 1 sesión.';
$messages['multi_delete_many'] = 'Se eliminaron {count} sesiones.';
$messages['multi_delete_partial'] = 'Se eliminaron {deleted} sesiones; {failed} fallaron.';
$messages['multi_delete_failed'] = 'No se pudieron eliminar las sesiones.';
$messages['report_action_confirm_title'] = 'Confirmar acción';

// Report Formular für die Session Tabelle in dbxAdmin Modul Auswahl der Spalten, Sortierung, Anzahl je Seite, Suche, etc.

$field['name']='dbx_rrows';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='10';
$field['label']='Por página';
$field['rules']='int';
$field['tooltip']='Número por página';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='1=1&10=10&15=15&20=20&25=25&50=50&100=100&0=Todos';
$fields[]=$field;

$field['name']='dbx_rsort';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='id';
$field['label']='Orden';
$field['rules']='sqlsearch';
$field['tooltip']='Orden de clasificación';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='id=ID&userid=Usuario&modul=Módulo&run1=Run1&run2=Run2&request_counter=Solicitudes&update_date=Último acceso';
$fields[]=$field;


$field['name']='dbx_rdesc';
$field['type']='varchar';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='DESC';
$field['label']='Dirección';
$field['rules']='parameter';
$field['tooltip']='Orden ascendente o descendente';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='ASC=Ascendente&DESC=Descendente';
$fields[]=$field;


$field['name']='dbx_rwhere';
$field['type']='varchar';
$field['tpl']='dbx|search';
$field['index']='';
$field['length']='32';
$field['default']='';
$field['label']='Búsqueda';
$field['rules']='parameter';
$field['tooltip']='Datos de búsqueda';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='';
$fields[]=$field;

$field['name']='dbx_rselect';
$field['type']='int';
$field['tpl']='select-single-label';
$field['index']='';
$field['length']='6';
$field['default']='0';
$field['label']='Seleccionado';
$field['rules']='parameter';
$field['tooltip']='Mostrar registros seleccionados';
$field['errormsg']='';
$field['placeholder']='';
$field['convert']='';
$field['protect']='0';
$field['mask']='';
$field['data']='';
$field['options']='0=Todos&1=Seleccionado';
$fields[]=$field;
