<?php
$messages = array();
$messages['save_success'] = 'Daten wurden gespeichert';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Daten konnten nicht gespeichert werden';
$messages['bar_title'] = 'Datenbank-Server';
$messages['bar_subtitle'] = 'Datenbank-Server verwalten';
$messages['new_server'] = 'Neuer Server';
$messages['new_server_title'] = 'Neuen DB-Server anlegen';
$messages['edit_server'] = 'DB-Server bearbeiten';
$messages['edit_server_title'] = 'DB-Server bearbeiten: {server}';
$messages['column_server'] = 'Server';
$messages['column_database'] = 'Datenbank';
$messages['column_host'] = 'Host';
$messages['column_type'] = 'Typ';
$messages['column_status'] = 'Status';
$messages['column_default'] = 'Standard';
$messages['column_tables'] = 'Tabellen';
$messages['column_connected'] = 'Verbunden';
$messages['status_active'] = 'Aktiv';
$messages['status_inactive'] = 'Deaktiviert';
$messages['yes'] = 'Ja';
$messages['no'] = 'Nein';
$messages['connection_check'] = 'Verbindung prüfen';
$messages['no_change'] = 'Keine Änderung';
$messages['check_input'] = 'Bitte die Eingaben prüfen ({fields}).';
$messages['server_deleted'] = 'Server ({server}) wurde gelöscht.';
$messages['server_delete_error'] = 'Server ({server}) konnte nicht gelöscht werden.';
$messages['server_name_missing'] = 'Servername fehlt.';
$messages['server_exists'] = 'Server ({server}) existiert bereits.';
$messages['sqlite_config_error'] = 'Modul-SQLite (*.db3) gehört nicht in die System-Config. Dateien liegen unter dbx/modules/*/db/.';
$messages['server_disabled_test_skipped'] = 'Server ist deaktiviert; der Verbindungstest wurde übersprungen.';
$messages['connection_failed'] = 'Verbindung nicht möglich.';
$messages['config_save_error'] = 'Config konnte nicht gespeichert werden.';
$messages['config_saved_connected'] = 'Config gespeichert, Server ({server}) verbunden.';
$messages['tables_info'] = 'Datenbanktabellen von {server}';
$messages['create_table_info'] = 'Neue Datenbanktabelle anlegen.';
$messages['new_table'] = 'Neue Datenbanktabelle';
$messages['new_table_title'] = 'Neue Datenbanktabelle erstellen';
$messages['create_dd_title'] = 'DataDictionary für diese Datenbanktabelle erstellen';
$messages['column_table'] = 'Tabelle';
$messages['column_count'] = 'Datensätze';
$messages['column_datadic'] = 'DataDictionary';
$messages['label_table'] = 'Tabelle';
$messages['table_created'] = 'Die Tabelle {table} wurde auf Server {server} in Datenbank {database} erstellt.';
$messages['table_create_error'] = 'Die Tabelle {table} konnte auf Server {server} in Datenbank {database} nicht erstellt werden.';
$messages['check_input_plain'] = 'Bitte prüfen Sie Ihre Eingabe.';
$messages['server_disabled'] = 'Server ({server}) ist deaktiviert.';
$messages['server_connected'] = 'Server ({server}) wurde verbunden.';
$messages['server_connect_error'] = 'Server ({server}) konnte nicht verbunden werden.';

// Felddefinition fuer DB-Server in dbx/modules/dbx/cfg/config.php.

$field = array();
$field['name'] = 'old_name';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = '';
$field['label'] = 'Alter Servername';
$field['rules'] = 'parameter|max=64';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = '';
$field['label'] = 'Servername';
$field['rules'] = 'parameter|min=1|max=64';
$field['tooltip'] = 'Interner Name des Datenbankservers.';
$field['errormsg'] = 'Bitte einen gueltigen Servernamen ohne Sonderzeichen eingeben.';
$field['placeholder'] = 'dbxApp';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'activ';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '1';
$field['label'] = 'Aktiv';
$field['rules'] = 'int';
$field['tooltip'] = 'Nur aktive SQL-Server werden verbunden. Modul-SQLite (*.db3) ist immer aktiv.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '1=Aktiv&0=Deaktiviert';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'type';
$field['type'] = 'varchar';
$field['length'] = '16';
$field['default'] = 'mysql';
$field['label'] = 'Datenbanktyp';
$field['rules'] = 'parameter|min=1|max=16';
$field['tooltip'] = 'PDO-Datenbanktyp.';
$field['errormsg'] = 'Bitte einen gueltigen Datenbanktyp auswaehlen.';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = 'mysql=MySQL&pgsql=PostgreSQL&sqlsrv=SQL Server&oci=Oracle&firebird=Firebird&cubrid=Cubrid&dblib=DBLib&ibm=IBM DB2&informix=Informix&odbc=ODBC';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'host';
$field['type'] = 'varchar';
$field['length'] = '255';
$field['default'] = '127.0.0.1';
$field['label'] = 'Host / Pfad';
$field['rules'] = 'varchar|max=255';
$field['tooltip'] = 'Host oder IP des SQL-Servers.';
$field['errormsg'] = 'Bitte Host oder Pfad pruefen.';
$field['placeholder'] = '127.0.0.1';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'dbname';
$field['type'] = 'varchar';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Datenbank';
$field['rules'] = 'varchar|min=1|max=128';
$field['tooltip'] = 'Name der Datenbank auf dem SQL-Server.';
$field['errormsg'] = 'Bitte einen gueltigen Datenbanknamen eingeben.';
$field['placeholder'] = 'dbx';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'user';
$field['type'] = 'varchar';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Benutzer';
$field['rules'] = 'varchar|max=128';
$field['tooltip'] = 'Datenbankbenutzer.';
$field['errormsg'] = 'Bitte Benutzer pruefen.';
$field['placeholder'] = 'root';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'pass';
$field['type'] = 'varchar';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Passwort';
$field['rules'] = 'varchar|max=255';
$field['tooltip'] = 'Datenbankpasswort.';
$field['errormsg'] = 'Bitte Passwort pruefen.';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'password-label';
$fields[] = $field;

$field = array();
$field['name'] = 'port';
$field['type'] = 'int';
$field['length'] = '8';
$field['default'] = '';
$field['label'] = 'Port';
$field['rules'] = 'int';
$field['tooltip'] = 'Port des Datenbankservers, leer fuer Standard.';
$field['errormsg'] = 'Bitte eine Portnummer eingeben.';
$field['placeholder'] = '3306';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'is_default';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Standard-Server';
$field['rules'] = 'int';
$field['tooltip'] = 'Diesen Server als Standardserver verwenden.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '0=Nein&1=Ja';
$field['tpl'] = 'select-single-label';
$fields[] = $field;
