<?php
$messages = array();
$messages['save_success'] = 'Los datos se guardaron';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Los datos no se pudieron guardar';
$messages['bar_title'] = 'Servidores de base de datos';
$messages['bar_subtitle'] = 'Administrar servidores de base de datos';
$messages['new_server'] = 'Nuevo servidor';
$messages['new_server_title'] = 'Crear un nuevo servidor de base de datos';
$messages['edit_server'] = 'Editar servidor de base de datos';
$messages['edit_server_title'] = 'Editar servidor de base de datos: {server}';
$messages['column_server'] = 'Servidor';
$messages['column_database'] = 'Base de datos';
$messages['column_host'] = 'Host';
$messages['column_type'] = 'Tipo';
$messages['column_status'] = 'Estado';
$messages['column_default'] = 'Predeterminado';
$messages['column_tables'] = 'Tablas';
$messages['column_connected'] = 'Conectado';
$messages['status_active'] = 'Activo';
$messages['status_inactive'] = 'Desactivado';
$messages['yes'] = 'Sí';
$messages['no'] = 'No';
$messages['connection_check'] = 'Comprobar conexión';
$messages['no_change'] = 'Sin cambios';
$messages['check_input'] = 'Compruebe los datos introducidos ({fields}).';
$messages['server_deleted'] = 'Se eliminó el servidor ({server}).';
$messages['server_delete_error'] = 'No se pudo eliminar el servidor ({server}).';
$messages['server_name_missing'] = 'Falta el nombre del servidor.';
$messages['server_exists'] = 'El servidor ({server}) ya existe.';
$messages['sqlite_config_error'] = 'Las bases SQLite de módulos (*.db3) no pertenecen a la configuración del sistema. Sus archivos se encuentran en dbx/modules/*/db/.';
$messages['server_disabled_test_skipped'] = 'El servidor está desactivado; se omitió la prueba de conexión.';
$messages['connection_failed'] = 'No se pudo establecer la conexión.';
$messages['config_save_error'] = 'No se pudo guardar la configuración.';
$messages['config_saved_connected'] = 'Se guardó la configuración y se conectó el servidor ({server}).';
$messages['tables_info'] = 'Tablas de base de datos en {server}';
$messages['create_table_info'] = 'Crear una tabla de base de datos nueva.';
$messages['new_table'] = 'Nueva tabla de base de datos';
$messages['new_table_title'] = 'Crear una tabla de base de datos nueva';
$messages['create_dd_title'] = 'Crear un DataDictionary para esta tabla de base de datos';
$messages['column_table'] = 'Tabla';
$messages['column_count'] = 'Registros';
$messages['column_datadic'] = 'DataDictionary';
$messages['label_table'] = 'Tabla';
$messages['table_created'] = 'La tabla {table} se ha creado en el servidor {server}, base de datos {database}.';
$messages['table_create_error'] = 'No se ha podido crear la tabla {table} en el servidor {server}, base de datos {database}.';
$messages['check_input_plain'] = 'Compruebe los datos introducidos.';
$messages['server_disabled'] = 'El servidor ({server}) está desactivado.';
$messages['server_connected'] = 'Se conectó el servidor ({server}).';
$messages['server_connect_error'] = 'No se pudo conectar el servidor ({server}).';

// Felddefinition fuer DB-Server in dbx/modules/dbx/cfg/config.php.

$field = array();
$field['name'] = 'old_name';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = '';
$field['label'] = 'Nombre anterior del servidor';
$field['rules'] = 'parameter|max=64';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = '';
$field['label'] = 'Nombre del servidor';
$field['rules'] = 'parameter|min=1|max=64';
$field['tooltip'] = 'Nombre interno del servidor de bases de datos.';
$field['errormsg'] = 'Por favor, introduzca un nombre de servidor válido sin caracteres especiales.';
$field['placeholder'] = 'dbxApp';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'activ';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '1';
$field['label'] = 'Activo';
$field['rules'] = 'int';
$field['tooltip'] = 'Sólo los servidores SQL activos están conectados. El módulo-SQLite (*.db3) siempre está activo.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '1=Activo&0=Desactivado';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'type';
$field['type'] = 'varchar';
$field['length'] = '16';
$field['default'] = 'mysql';
$field['label'] = 'Tipo de base de datos';
$field['rules'] = 'parameter|min=1|max=16';
$field['tooltip'] = 'Tipo de base de datos PDO.';
$field['errormsg'] = 'Seleccione un tipo de base de datos válido.';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = 'mysql=MySQL&pgsql=PostgreSQL&sqlsrv=SQL Server&oci=Oracle&firebird=Firebird&cubrid=Cubrid&dblib=DBLib&ibm=IBM DB2&informix=Informix&odbc=ODBC';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'host';
$field['type'] = 'varchar';
$field['length'] = '255';
$field['default'] = '127.0.0.1';
$field['label'] = 'Host / ruta';
$field['rules'] = 'varchar|max=255';
$field['tooltip'] = 'Host o IP del servidor SQL.';
$field['errormsg'] = 'Por favor, compruebe el host o el camino.';
$field['placeholder'] = '127.0.0.1';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'dbname';
$field['type'] = 'varchar';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Base de datos';
$field['rules'] = 'varchar|min=1|max=128';
$field['tooltip'] = 'Nombre de la base de datos en el servidor SQL.';
$field['errormsg'] = 'Por favor ingrese un nombre de base válido.';
$field['placeholder'] = 'dbx';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'user';
$field['type'] = 'varchar';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Usuario';
$field['rules'] = 'varchar|max=128';
$field['tooltip'] = 'usuarios de bases de datos.';
$field['errormsg'] = 'Por favor, compruebe los usuarios.';
$field['placeholder'] = 'root';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'pass';
$field['type'] = 'varchar';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Contraseña';
$field['rules'] = 'varchar|max=255';
$field['tooltip'] = 'contraseña de base de datos.';
$field['errormsg'] = 'Por favor, revise la contraseña.';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'password-label';
$fields[] = $field;

$field = array();
$field['name'] = 'port';
$field['type'] = 'int';
$field['length'] = '8';
$field['default'] = '';
$field['label'] = 'Puerto';
$field['rules'] = 'int';
$field['tooltip'] = 'Puerto del servidor de bases de datos, vacío para estándar.';
$field['errormsg'] = 'Por favor, introduzca un número de puerto.';
$field['placeholder'] = '3306';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'is_default';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Servidor predeterminado';
$field['rules'] = 'int';
$field['tooltip'] = 'Utilice este servidor como servidor estándar.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '0=No&1=Sí';
$field['tpl'] = 'select-single-label';
$fields[] = $field;
