<?php
$messages = array();
$messages['save_success'] = 'Data was saved';
$messages['save_succeass'] = $messages['save_success'];
$messages['save_error'] = 'Data could not be saved';
$messages['bar_title'] = 'Database servers';
$messages['bar_subtitle'] = 'Manage database servers';
$messages['new_server'] = 'New server';
$messages['new_server_title'] = 'Create a new database server';
$messages['edit_server'] = 'Edit database server';
$messages['edit_server_title'] = 'Edit database server: {server}';
$messages['column_server'] = 'Server';
$messages['column_database'] = 'Database';
$messages['column_host'] = 'Host';
$messages['column_type'] = 'Type';
$messages['column_status'] = 'Status';
$messages['column_default'] = 'Default';
$messages['column_tables'] = 'Tables';
$messages['column_connected'] = 'Connected';
$messages['status_active'] = 'Active';
$messages['status_inactive'] = 'Disabled';
$messages['yes'] = 'Yes';
$messages['no'] = 'No';
$messages['connection_check'] = 'Check connection';
$messages['no_change'] = 'No changes';
$messages['check_input'] = 'Please check the input ({fields}).';
$messages['server_deleted'] = 'Server ({server}) was deleted.';
$messages['server_delete_error'] = 'Server ({server}) could not be deleted.';
$messages['server_name_missing'] = 'Server name is missing.';
$messages['server_exists'] = 'Server ({server}) already exists.';
$messages['sqlite_config_error'] = 'Module SQLite databases (*.db3) do not belong in the system configuration. Their files are stored under dbx/modules/*/db/.';
$messages['server_disabled_test_skipped'] = 'The server is disabled; the connection test was skipped.';
$messages['connection_failed'] = 'Connection failed.';
$messages['config_save_error'] = 'The configuration could not be saved.';
$messages['config_saved_connected'] = 'Configuration saved and server ({server}) connected.';
$messages['tables_info'] = 'Database tables on {server}';
$messages['create_table_info'] = 'Create a new database table.';
$messages['new_table'] = 'New database table';
$messages['new_table_title'] = 'Create a new database table';
$messages['create_dd_title'] = 'Create a DataDictionary for this database table';
$messages['column_table'] = 'Table';
$messages['column_count'] = 'Records';
$messages['column_datadic'] = 'DataDictionary';
$messages['label_table'] = 'Table';
$messages['table_created'] = 'Table {table} was created on server {server} in database {database}.';
$messages['table_create_error'] = 'Table {table} could not be created on server {server} in database {database}.';
$messages['check_input_plain'] = 'Please check your input.';
$messages['server_disabled'] = 'Server ({server}) is disabled.';
$messages['server_connected'] = 'Server ({server}) was connected.';
$messages['server_connect_error'] = 'Server ({server}) could not be connected.';

// Felddefinition fuer DB-Server in dbx/modules/dbx/cfg/config.php.

$field = array();
$field['name'] = 'old_name';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = '';
$field['label'] = 'Old server name';
$field['rules'] = 'parameter|max=64';
$field['tooltip'] = '';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'hidden';
$fields[] = $field;

$field = array();
$field['name'] = 'name';
$field['type'] = 'varchar';
$field['length'] = '64';
$field['default'] = '';
$field['label'] = 'Server name';
$field['rules'] = 'parameter|min=1|max=64';
$field['tooltip'] = 'Internal name of the database server.';
$field['errormsg'] = 'Please enter a valid server name without special characters.';
$field['placeholder'] = 'dbxApp';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'activ';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '1';
$field['label'] = 'Active';
$field['rules'] = 'int';
$field['tooltip'] = 'Only active SQL servers are connected. Module-SQLite (*.db3) is always active.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '1=Active&0=Deactivated';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'type';
$field['type'] = 'varchar';
$field['length'] = '16';
$field['default'] = 'mysql';
$field['label'] = 'Database type';
$field['rules'] = 'parameter|min=1|max=16';
$field['tooltip'] = 'PDO database type.';
$field['errormsg'] = 'Please select a valid database type.';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = 'mysql=MySQL&pgsql=PostgreSQL&sqlsrv=SQL Server&oci=Oracle&firebird=Firebird&cubrid=Cubrid&dblib=DBLib&ibm=IBM DB2&informix=Informix&odbc=ODBC';
$field['tpl'] = 'select-single-label';
$fields[] = $field;

$field = array();
$field['name'] = 'host';
$field['type'] = 'varchar';
$field['length'] = '255';
$field['default'] = '127.0.0.1';
$field['label'] = 'Host / Path';
$field['rules'] = 'varchar|max=255';
$field['tooltip'] = 'Host or IP of the SQL server.';
$field['errormsg'] = 'Please check host or path.';
$field['placeholder'] = '127.0.0.1';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'dbname';
$field['type'] = 'varchar';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'Database';
$field['rules'] = 'varchar|min=1|max=128';
$field['tooltip'] = 'Name of the database on the SQL server.';
$field['errormsg'] = 'Please enter a valid database name.';
$field['placeholder'] = 'dbx';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'user';
$field['type'] = 'varchar';
$field['length'] = '128';
$field['default'] = '';
$field['label'] = 'User';
$field['rules'] = 'varchar|max=128';
$field['tooltip'] = 'database users.';
$field['errormsg'] = 'Please check users.';
$field['placeholder'] = 'root';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'pass';
$field['type'] = 'varchar';
$field['length'] = '255';
$field['default'] = '';
$field['label'] = 'Password';
$field['rules'] = 'varchar|max=255';
$field['tooltip'] = 'database password.';
$field['errormsg'] = 'Please check the password.';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'password-label';
$fields[] = $field;

$field = array();
$field['name'] = 'port';
$field['type'] = 'int';
$field['length'] = '8';
$field['default'] = '';
$field['label'] = 'Port';
$field['rules'] = 'int';
$field['tooltip'] = 'Port of the database server, empty for standard.';
$field['errormsg'] = 'Please enter a port number.';
$field['placeholder'] = '3306';
$field['data'] = '';
$field['options'] = '';
$field['tpl'] = 'text-label';
$fields[] = $field;

$field = array();
$field['name'] = 'is_default';
$field['type'] = 'int';
$field['length'] = '1';
$field['default'] = '0';
$field['label'] = 'Default server';
$field['rules'] = 'int';
$field['tooltip'] = 'Use this server as a standard server.';
$field['errormsg'] = '';
$field['placeholder'] = '';
$field['data'] = '';
$field['options'] = '0=No&1=Yes';
$field['tpl'] = 'select-single-label';
$fields[] = $field;
